version: "3"
services:

  finbotdb:
    image: "postgres:12"
    container_name: finbotdb
    restart: always
    shm_size: 256MB
    environment:
      POSTGRES_PORT: 5432
      POSTGRES_DB: finbot
      POSTGRES_USER: finbot
      POSTGRES_PASSWORD: finbot
    ports:
      - "5432:5432"
    volumes:
      - .finbotdb:/var/lib/postgresql/data

  finbotrmq:
    image: "rabbitmq:3-management-alpine"
    container_name: finbotrmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: finbot
      RABBITMQ_DEFAULT_PASS: finbot

  finbotwsrv:
    image: "finbot/runtime-selenium:latest"
    container_name: finbotwsrv
    working_dir: /finbot
    command: bash -c "source docker.env.sh && make run-finbotwsrv-dev"
    tty: true
    ports:
      - "5001:5001"
    volumes:
      - .:/finbot
    environment:
      FINBOT_ENV: ${FINBOT_ENV}
      FINBOT_WAIT_DEPS: "db"

  snapwsrv:
    image: "finbot/runtime:latest"
    container_name: snapwsrv
    depends_on:
      - finbotdb
      - finbotwsrv
    working_dir: /finbot
    command: bash -c "source docker.env.sh && make finbot-wait && make run-snapwsrv-dev"
    tty: true
    ports:
      - "5000:5000"
    volumes:
      - .:/finbot
    environment:
      FINBOT_ENV: ${FINBOT_ENV}
      FINBOT_WAIT_DEPS: "db,finbot"

  histwsrv:
    image: "finbot/runtime:latest"
    container_name: histwsrv
    depends_on:
      - finbotdb
    working_dir: /finbot
    command: bash -c "source docker.env.sh && make finbot-wait && make run-histwsrv-dev"
    tty: true
    ports:
      - "5002:5002"
    volumes:
      - .:/finbot
    environment:
      FINBOT_ENV: ${FINBOT_ENV}
      FINBOT_WAIT_DEPS: "db"

  schedsrv:
    image: "finbot/runtime:latest"
    container_name: schedsrv
    depends_on:
      - finbotdb
      - workersrv
    working_dir: /finbot
    command: bash -c "source docker.env.sh && make finbot-wait && make run-schedsrv-dev"
    tty: true
    volumes:
      - .:/finbot
    environment:
      FINBOT_ENV: ${FINBOT_ENV}
      FINBOT_WAIT_DEPS: "db,worker"

  workersrv:
    image: "finbot/runtime:latest"
    container_name: workersrv
    depends_on:
      - finbotdb
      - finbotrmq
      - snapwsrv
      - histwsrv
    working_dir: /finbot
    command: bash -c "source docker.env.sh && make finbot-wait && make run-workersrv-dev"
    tty: true
    volumes:
      - .:/finbot
    environment:
      FINBOT_ENV: ${FINBOT_ENV}
      FINBOT_WAIT_DEPS: "db,rmq,snap,hist"

  appwsrv:
    image: "finbot/runtime:latest"
    container_name: appwsrv
    depends_on:
      - finbotdb
      - finbotwsrv
      - workersrv
    working_dir: /finbot
    command: bash -c "source docker.env.sh && make finbot-wait && make run-appwsrv-dev"
    tty: true
    ports:
      - "5003:5003"
    volumes:
      - .:/finbot
    environment:
      FINBOT_ENV: ${FINBOT_ENV}
      FINBOT_WAIT_DEPS: "db,finbot,worker"

  webapp:
    image: "node:16-buster"
    container_name: webapp
    depends_on:
      - appwsrv
    volumes:
      - .:/finbot
    working_dir: /finbot
    command: bash -c "source docker.env.sh && tools/run-webapp.sh"
    tty: true
    ports:
      - "5005:5005"
    environment:
      FINBOT_ENV: ${FINBOT_ENV}

  operator:
    image: "finbot/runtime-selenium:latest"
    container_name: operator
    depends_on:
      - finbotdb
    working_dir: /finbot
    command: bash -c "source docker.env.sh && sleep infinity"
    stdin_open: true
    tty: true
    volumes:
      - .:/finbot

volumes:
    .finbotdb:
    .:
