version: "3"
services:

  finbotdb:
    image: "postgres:12"
    env_file:
      - envs/prod.env
      - envs/secrets.prod.env
    restart: always
    shm_size: 256MB
    ports:
      - "5432:5432"
    volumes:
      - .finbotdb:/var/lib/postgresql/data

  finbotrmq:
    image: "rabbitmq:3-management-alpine"
    env_file:
      - envs/prod.env
      - envs/secrets.prod.env

  finbotwsrv:
    image: "finbotapp/runtime-playwright:latest"
    env_file:
      - envs/prod.env
      - envs/secrets.prod.env
    working_dir: /finbot
    command: bash -c "./tools/run finbotwsrv"
    volumes:
      - .intake_data:/intake_data

  snapwsrv:
    image: "finbotapp/runtime:latest"
    env_file:
      - envs/prod.env
      - envs/secrets.prod.env
    depends_on:
      - finbotdb
      - finbotwsrv
    working_dir: /finbot
    command: bash -c "./tools/run snapwsrv"
    environment:
      FINBOT_WAIT_DEPS: "finbotdb,finbotwsrv"

  histwsrv:
    image: "finbotapp/runtime:latest"
    env_file:
      - envs/prod.env
      - envs/secrets.prod.env
    depends_on:
      - finbotdb
    working_dir: /finbot
    command: bash -c "./tools/run histwsrv"
    environment:
      FINBOT_WAIT_DEPS: "finbotdb"

  schedsrv:
    image: "finbotapp/runtime:latest"
    env_file:
      - envs/prod.env
      - envs/secrets.prod.env
    depends_on:
      - finbotdb
      - workersrv
    working_dir: /finbot
    command: bash -c "./tools/run schedsrv"
    environment:
      FINBOT_WAIT_DEPS: "finbotdb,workersrv"

  workersrv:
    image: "finbotapp/runtime:latest"
    env_file:
      - envs/prod.env
      - envs/secrets.prod.env
    depends_on:
      - finbotdb
      - finbotrmq
      - snapwsrv
      - histwsrv
    working_dir: /finbot
    command: bash -c "./tools/run workersrv"
    environment:
      FINBOT_WAIT_DEPS: "finbotdb,finbotrmq,snapwsrv,histwsrv"

  appwsrv:
    image: "finbotapp/runtime:latest"
    env_file:
      - envs/prod.env
      - envs/secrets.prod.env
    depends_on:
      - finbotdb
      - finbotwsrv
      - workersrv
    working_dir: /finbot
    command: bash -c "./tools/run appwsrv"
    ports:
      - "5003:5003"
    volumes:
      - .:/finbot
    environment:
      FINBOT_WAIT_DEPS: "finbotdb,finbotwsrv,workersrv"

  webapp:
    image: "finbotapp/webapp:latest"
    env_file:
      - envs/prod.env
      - envs/secrets.prod.env
    depends_on:
      - appwsrv
    working_dir: /webapp
    ports:
      - "5005:5005"
    volumes:
      - ./envs/env-config.prod.js:/usr/share/nginx/html/env-config.js
