version: "3"
services:

  finbotdb:
    image: "postgres:12"
    env_file:
      - envs/dev.env
      - envs/secrets.dev.env
      - envs/dev-overrides.env
    shm_size: 256MB
    ports:
      - "5432:5432"
    volumes:
      - .finbotdb:/var/lib/postgresql/data

  finbotrmq:
    image: "rabbitmq:3-management-alpine"
    env_file:
      - envs/dev.env
      - envs/secrets.dev.env
      - envs/dev-overrides.env
    ports:
      - "5672:5672"
      - "15672:15672"

  finbotwsrv:
    image: "finbotapp/runtime-dev:latest"
    env_file:
      - envs/dev.env
      - envs/secrets.dev.env
      - envs/dev-overrides.env
    working_dir: /finbot
    command: bash -c "./tools/run finbotwsrv"
    tty: true
    ports:
      - "5001:5001"
    volumes:
      - .:/finbot
      - .intake_data:/intake_data

  schedsrv:
    image: "finbotapp/runtime-dev:latest"
    env_file:
      - envs/dev.env
      - envs/secrets.dev.env
      - envs/dev-overrides.env
    depends_on:
      - finbotdb
      - workersrv
    working_dir: /finbot
    command: bash -c "tools/autorestart finbot/ ./tools/run schedsrv"
    tty: true
    volumes:
      - .:/finbot
    environment:
      FINBOT_WAIT_DEPS: "${FINBOT_WAIT_DEPS:-finbotdb,workersrv}"

  workersrv:
    image: "finbotapp/runtime-dev:latest"
    env_file:
      - envs/dev.env
      - envs/secrets.dev.env
      - envs/dev-overrides.env
    depends_on:
      - finbotdb
      - finbotrmq
    working_dir: /finbot
    command: bash -c "tools/autorestart finbot/ ./tools/run workersrv"
    tty: true
    volumes:
      - .:/finbot
    environment:
      FINBOT_WAIT_DEPS: "${FINBOT_WAIT_DEPS:-finbotdb,finbotrmq}"

  appwsrv:
    image: "finbotapp/runtime-dev:latest"
    env_file:
      - envs/dev.env
      - envs/secrets.dev.env
      - envs/dev-overrides.env
    depends_on:
      - finbotdb
      - finbotwsrv
      - workersrv
    working_dir: /finbot
    command: bash -c "./tools/run appwsrv"
    tty: true
    ports:
      - "5003:5003"
    volumes:
      - .:/finbot
    environment:
      FINBOT_WAIT_DEPS: "${FINBOT_WAIT_DEPS:-finbotdb,finbotwsrv,workersrv}"

  operator:
    image: "finbotapp/runtime-dev:latest"
    env_file:
      - envs/dev.env
      - envs/secrets.dev.env
      - envs/dev-overrides.env
    profiles:
      - operator
    container_name: operator
    depends_on:
      - finbotdb
    working_dir: /finbot
    command: sleep infinity
    stdin_open: true
    tty: true
    volumes:
      - .:/finbot

  webapp:
    image: "node:16-buster"
    env_file:
      - envs/dev.env
      - envs/secrets.dev.env
      - envs/dev-overrides.env
    profiles:
      - webapp
    depends_on:
      - appwsrv
    volumes:
      - .:/finbot
    working_dir: /finbot
    command: bash -c "tools/run webapp"
    tty: true
    ports:
      - "5005:5005"
