version: "3"
services:

  finbotdb:
    image: "postgres:12"
    env_file:
      - envs/prod.env
      - envs/secrets.prod.env
    restart: always
    shm_size: 256MB
    volumes:
      - .finbotdb:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  schedsrv:
    image: "finbotapp/runtime:latest"
    env_file:
      - envs/prod.env
      - envs/secrets.prod.env
    depends_on:
      - finbotdb
      - workersrv_temporal
    working_dir: /finbot
    command: bash -c "./tools/run schedsrv"
    environment:
      FINBOT_WAIT_DEPS: "finbotdb,workersrv[temporal]"

  workersrv_temporal:
    image: "finbotapp/runtime-playwright:latest"
    env_file:
      - envs/prod.env
      - envs/secrets.prod.env
    depends_on:
      - finbotdb
      - temporal
    working_dir: /finbot
    command: bash -c "tools/run workersrv[temporal]"
    environment:
      FINBOT_WAIT_DEPS: "finbotdb,temporal"

  appwsrv:
    image: "finbotapp/runtime:latest"
    env_file:
      - envs/prod.env
      - envs/secrets.prod.env
    depends_on:
      - finbotdb
      - workersrv_temporal
    working_dir: /finbot
    command: bash -c "./tools/run appwsrv"
    ports:
      - "5003:5003"
    volumes:
      - .:/finbot
    environment:
      FINBOT_WAIT_DEPS: "finbotdb,workersrv[temporal]"

  temporal:
    image: temporalio/auto-setup:1.27
    env_file:
      - envs/prod.env
      - envs/secrets.prod.env
    container_name: temporal
    depends_on:
      finbotdb:
        condition: service_healthy
    ports:
      - 7233:7233
    volumes:
      - ./envs/temporal/dynamicconfig:/etc/temporal/config/dynamicconfig

  temporal-admin-tools:
    image: temporalio/admin-tools:1.27
    env_file:
      - envs/prod.env
      - envs/secrets.prod.env
    container_name: temporal-admin-tools
    depends_on:
      - temporal
    stdin_open: true
    tty: true

  temporal-ui:
    image: temporalio/ui:v2.37.4
    env_file:
      - envs/prod.env
      - envs/secrets.prod.env
    container_name: temporal-ui
    depends_on:
      - temporal
    ports:
      - 5006:8080

  webapp:
    image: "finbotapp/webapp:latest"
    env_file:
      - envs/prod.env
      - envs/secrets.prod.env
    depends_on:
      - appwsrv
    working_dir: /webapp
    ports:
      - "5005:5005"
    volumes:
      - ./envs/env-config.prod.js:/usr/share/nginx/html/finbot/env-config.js
