version: "3"
services:

  finbotdb:
    image: "postgres:12"
    container_name: finbotdb
    restart: always
    shm_size: 256MB
    environment:
        POSTGRES_PORT: 5432
        POSTGRES_DB: finbot
        POSTGRES_USER: finbot
        POSTGRES_PASSWORD: finbot
    ports:
      - "5432:5432"
    volumes:
      - .finbotdb:/var/lib/postgresql/data

  finbotwsrv:
    build:
      context: .
      dockerfile: finbotwsrv.Dockerfile
    depends_on:
      - finbotdb
      - dev
    container_name: finbotwsrv
    working_dir: /finbot
    command: sh -c "make finbotdb-wait && make run-finbotwsrv-dev"
    tty: true
    ports:
      - "5001:5001"
    volumes:
      - .:/finbot
    environment:
      FINBOT_DB_HOSTNAME: finbotdb

  snapwsrv:
    build:
      context: .
      dockerfile: snapwsrv.Dockerfile
    container_name: snapwsrv
    depends_on: 
      - finbotdb
      - finbotwsrv
      - dev
    working_dir: /finbot
    command: sh -c "make finbotdb-wait && make run-snapwsrv-dev"
    tty: true
    ports:
      - "5000:5000"
    volumes:
      - .:/finbot
    environment:
      FINBOT_FINBOTWSRV_ENDPOINT: "http://finbotwsrv:5001"
      FINBOT_DB_HOSTNAME: finbotdb

  histwsrv:
    build:
      context: .
      dockerfile: histwsrv.Dockerfile
    container_name: histwsrv
    depends_on: 
      - finbotdb
      - dev
    working_dir: /finbot
    command: sh -c "make finbotdb-wait && make run-histwsrv-dev"
    tty: true
    ports:
      - "5002:5002"
    volumes:
      - .:/finbot
    environment:
      FINBOT_DB_HOSTNAME: finbotdb

  schedsrv:
    build:
      context: .
      dockerfile: schedsrv.Dockerfile
    container_name: schedsrv
    depends_on: 
      - snapwsrv
      - histwsrv
      - dev
    working_dir: /finbot
    command: sh -c "make finbotdb-wait && /usr/bin/wait && make run-schedsrv-dev"
    tty: true
    volumes:
      - .:/finbot
    environment:
      WAIT_HOSTS: histwsrv:5002, snapwsrv:5000
      FINBOT_DB_HOSTNAME: finbotdb
      FINBOT_SNAPWSRV_ENDPOINT: "http://snapwsrv:5000"
      FINBOT_HISTWSRV_ENDPOINT: "http://histwsrv:5002"

  appwsrv:
    build:
      context: .
      dockerfile: appwsrv.Dockerfile
    container_name: appwsrv
    depends_on: 
      - finbotdb
      - finbotwsrv
      - dev
    working_dir: /finbot
    command: sh -c "make finbotdb-wait && make run-appwsrv-dev"
    tty: true
    ports:
      - "5003:5003"
    volumes:
      - .:/finbot
    environment:
      FINBOT_DB_HOSTNAME: finbotdb
      FINBOT_FINBOTWSRV_ENDPOINT: "http://finbotwsrv:5001"

  webapp:
    image: "node:13-alpine3.10"
    container_name: webapp
    depends_on: 
      - appwsrv
      - dev
    volumes:
      - ./webapp:/webapp
    working_dir: /webapp
    command: sh -c "npm install && npm start"
    tty: true
    ports:
      - "5005:5005"

  dev:
    build:
      context: .
      dockerfile: dev.Dockerfile
    container_name: dev
    depends_on: 
      - finbotdb
    working_dir: /finbot
    command: sleep infinity
    stdin_open: true
    tty: true
    volumes:
      - .:/finbot
    environment:
      FINBOT_DB_HOSTNAME: finbotdb

volumes:
    .finbotdb:
    .:
