#!/usr/bin/env bash
SELF_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"


function help {
  echo "finbot control utility"
  echo
  echo "Usage:"
  echo "  $0 [COMMAND]"
  echo
  echo "Commands: "
  echo "  init: "
  echo "  start: "
  echo "  stop: "
}

command=$1
if [[ -z "${command}" ]]
then
  help
  exit 1
fi

shift 1
./tools/finbotctl-${command} $@
