#!/usr/bin/env bash
function help {
  echo "finbot control utility"
  echo
  echo "Usage:"
  echo "  $0 [COMMAND]"
  echo
  echo "Commands: "
  echo "  init: "
  echo "  start: "
  echo "  stop: "
}

command=$1
if [[ -z "${command}" ]]
then
  help
  exit 1
fi

shift 1
./tools/finbotctl-${command} "$@"
