#!/usr/bin/env bash
function usage {
  echo "finbot control utility"
  echo
  echo "Usage:"
  echo "  $0 [COMMAND]"
  echo
  echo "Commands: "
  echo "  init: "
  echo "  start: "
  echo "  stop: "
  echo "  restart: "
}

command="${1}"
if [[ -z "${command}" ]]
then
  usage
  exit 1
fi

command_script="./tools/finbotctl-${command}"
if [[ ! -f "${command_script}" ]]
then
  echo "!! invalid command: ${command}"
  echo
  usage
  exit 1
fi

shift 1
"./tools/finbotctl-${command}" "$@"
