[tool.ruff]
select = ["E", "F", "Q", "I"]
exclude = [
    'migrations/',
    'venv/',
    'webapp/'
]
line-length = 120
target-version = "py312"

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
