[tool.ruff]
exclude = [
    'migrations/',
    'venv/',
    'webapp/'
]
line-length = 120
target-version = "py312"

[tool.ruff.lint]
select = ["E", "F", "Q", "I"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
