export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';

export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

export const SET_SCHEMA = 'SET_SCHEMA';
export const SET_SELECTED_PROVIDER = 'SET_SELECTED_PROVIDER';
export const INITIALIZE_PROVIDERS = 'INITIALIZE_PROVIDERS';
export const VALIDATION_LINKING_FAIL = 'VALIDATION_LINKING_FAIL';
export const LINKING_ACCOUNT_SUCCESS = 'LINKING_ACCOUNT_SUCCESS';
export const SET_LOADING = 'SET_LOADING';
export const VALIDATION_SUCCESS = 'VALIDATION_SUCCESS';
