import random

FAKE_BANK_NAMES = [
    "Apex National Bank",
    "Liberty Savings Bank",
    "Horizon Trust Bank",
    "Summit Federal Bank",
    "Zenith Community Bank",
    "Pinnacle Bank of Commerce",
    "Golden Gate Bank",
    "Triumph National Bank",
    "Infinity Trust Bank",
    "Radiant Savings Bank",
    "Prosperity National Bank",
    "Unity Federal Bank",
    "Diamond Trust Bank",
    "Prime Community Bank",
    "Vanguard Savings Bank",
    "Heritage National Bank",
    "Crestview Bank",
    "Patriot Trust Bank",
    "Legacy Federal Bank",
    "Beacon Savings Bank",
    "Sovereign Trust Bank",
    "New Era Bank",
    "Integrity National Bank",
    "Crystal Clear Bank",
    "Guardian Savings Bank",
    "True North Bank",
    "Sterling Federal Bank",
    "Millennium Trust Bank",
    "Paramount Savings Bank",
    "Starlight National Bank",
    "Blue Horizon Bank",
    "Keystone Trust Bank",
    "Ascend Federal Bank",
    "Evergreen National Bank",
    "Noble Savings Bank",
    "Victory Trust Bank",
    "Endeavor Bank",
    "Infinity Federal Bank",
    "Nexus Trust Bank",
    "Titan National Bank",
    "Crystal Peak Bank",
    "Unity Savings Bank",
    "Horizon National Bank",
    "Liberty Federal Bank",
    "Apex Trust Bank",
    "Stellar National Bank",
    "Lighthouse Savings Bank",
    "Radiant Trust Bank",
    "Zenith Federal Bank",
    "Summit National Bank",
]


FAKE_INVESTMENT_BANK_NAMES = [
    "Apex Investment Bank",
    "Zenith Capital Partners",
    "Summit Securities",
    "Vanguard Investment Bank",
    "Liberty Capital Management",
    "Heritage Securities",
    "Radiant Capital Advisors",
    "Prime Investment Bank",
    "Evergreen Capital Group",
    "Prosperity Capital Advisors",
    "Unity Securities",
    "Diamond Investment Bank",
    "Prime Capital Partners",
    "Horizon Investment Bank",
    "Legacy Capital Management",
    "Patriot Investment Bank",
    "Triumph Capital Advisors",
    "Noble Securities",
    "Victory Capital Partners",
    "Beacon Investment Bank",
    "Starlight Capital Management",
    "Crestview Securities",
    "Endeavor Investment Bank",
    "Equinox Capital Advisors",
    "Blue Horizon Investment Bank",
    "Golden Gate Securities",
    "Radiance Capital Group",
    "Apex Capital Advisors",
    "Unity Investment Bank",
    "Zenith Capital Bank",
    "Lighthouse Investment Bank",
    "Ascend Capital Partners",
    "Essential Plus Capital",
    "Legacy Plus Investment Bank",
    "Prosperity Plus Capital Advisors",
    "Prime Plus Securities",
    "Radiant Plus Investment Bank",
    "Sterling Capital Partners",
    "True Vision Investment Bank",
    "Global Wealth Securities",
    "Secure Future Capital",
    "Titan Capital Group",
    "Crystal Clear Investment Bank",
    "New Era Capital Advisors",
    "Sovereign Wealth Securities",
    "Millennium Investment Bank",
    "Pinnacle Capital Advisors",
    "Evergreen Investment Bank",
    "Guardian Capital Partners",
    "Victory Securities",
]


FAKE_CHECKING_ACCOUNT_NAMES = [
    "Advantage Checking",
    "Premier Checking",
    "Secure Checking",
    "Essential Checking",
    "Choice Checking",
    "Prestige Checking",
    "Freedom Checking",
    "Simple Checking",
    "Infinity Checking",
    "Classic Checking",
    "Preferred Checking",
    "Horizon Checking",
    "Elite Checking",
    "Heritage Checking",
    "Value Checking",
    "Sterling Checking",
    "Crystal Checking",
    "Prosperity Checking",
    "Titan Checking",
    "Unity Checking",
    "Prime Checking",
    "Radiant Checking",
    "Prosper Checking",
    "Patriot Checking",
    "Legacy Checking",
    "Keystone Checking",
    "Millennium Checking",
    "Triumph Checking",
    "Vanguard Checking",
    "Guardian Checking",
    "Noble Checking",
    "Pinnacle Checking",
    "Victory Checking",
    "Starlight Checking",
    "Evergreen Checking",
    "True North Checking",
    "Beacon Checking",
    "Apex Checking",
    "Golden Checking",
    "Summit Checking",
    "Radiance Checking",
    "Crestview Checking",
    "Endeavor Checking",
    "Equinox Checking",
    "Blue Horizon Checking",
    "Unity Savings Checking",
    "Zenith Checking",
    "Lighthouse Checking",
    "Ascend Checking",
    "Essential Plus Checking",
]


FAKE_SAVINGS_ACCOUNT_NAMES = [
    "Advantage Savings",
    "Premier Savings",
    "Secure Savings",
    "Essential Savings",
    "Choice Savings",
    "Prestige Savings",
    "Freedom Savings",
    "Simple Savings",
    "Infinity Savings",
    "Classic Savings",
    "Preferred Savings",
    "Horizon Savings",
    "Elite Savings",
    "Heritage Savings",
    "Value Savings",
    "Sterling Savings",
    "Crystal Savings",
    "Prosperity Savings",
    "Titan Savings",
    "Unity Savings",
    "Prime Savings",
    "Radiant Savings",
    "Prosper Savings",
    "Patriot Savings",
    "Legacy Savings",
    "Keystone Savings",
    "Millennium Savings",
    "Triumph Savings",
    "Vanguard Savings",
    "Guardian Savings",
    "Noble Savings",
    "Pinnacle Savings",
    "Victory Savings",
    "Starlight Savings",
    "Evergreen Savings",
    "True North Savings",
    "Beacon Savings",
    "Apex Savings",
    "Golden Savings",
    "Summit Savings",
    "Radiance Savings",
    "Crestview Savings",
    "Endeavor Savings",
    "Equinox Savings",
    "Blue Horizon Savings",
    "Zenith Savings",
    "Lighthouse Savings",
    "Ascend Savings",
    "Essential Plus Savings",
    "Legacy Plus Savings",
]


FAKE_PENSION_FUND_NAMES = [
    "Golden Years Pension Fund",
    "Secure Future Retirement Fund",
    "Legacy Pension Trust",
    "Horizon Retirement Fund",
    "Prosperity Pension Plan",
    "Summit Retirement Fund",
    "Liberty Pension Fund",
    "Heritage Retirement Fund",
    "Apex Pension Plan",
    "Unity Pension Trust",
    "Diamond Retirement Fund",
    "Prime Pension Fund",
    "Evergreen Retirement Plan",
    "Vanguard Pension Trust",
    "Radiant Retirement Fund",
    "Prosper Pension Trust",
    "Patriot Retirement Fund",
    "Legacy Pension Fund",
    "Keystone Retirement Plan",
    "Millennium Pension Trust",
    "Triumph Retirement Fund",
    "Vanguard Pension Fund",
    "Guardian Retirement Plan",
    "Noble Pension Trust",
    "Pinnacle Retirement Fund",
    "Victory Pension Plan",
    "Starlight Retirement Fund",
    "Evergreen Pension Trust",
    "True North Retirement Fund",
    "Beacon Pension Plan",
    "Apex Retirement Trust",
    "Golden Gate Pension Fund",
    "Summit Pension Plan",
    "Radiance Retirement Fund",
    "Crestview Pension Trust",
    "Endeavor Retirement Fund",
    "Equinox Pension Plan",
    "Blue Horizon Retirement Fund",
    "Unity Pension Fund",
    "Zenith Retirement Trust",
    "Lighthouse Pension Plan",
    "Ascend Retirement Fund",
    "Essential Plus Pension Fund",
    "Legacy Plus Retirement Plan",
    "Prosperity Plus Pension Fund",
    "Prime Plus Retirement Trust",
    "Radiant Plus Pension Fund",
    "Sterling Retirement Trust",
    "True Vision Pension Fund",
]


FAKE_CRYPTO_EXCHANGE_NAMES = [
    "CryptoNova Exchange",
    "QuantumCoin Exchange",
    "LunaTrade",
    "GalaxyCrypto Exchange",
    "NebulaCoin Exchange",
    "StellarBit Exchange",
    "HyperChain Exchange",
    "ZenithCrypto Market",
    "PioneerCoin Exchange",
    "FusionCrypt Exchange",
    "EclipseCrypto",
    "HorizonCoin Exchange",
    "NovaBit Exchange",
    "SolarisCrypto Exchange",
    "NexusCoin Market",
    "InfinityCrypto Exchange",
    "QuantumBit Trade",
    "SpectraCoin Exchange",
    "LunaChain Exchange",
    "VertexCrypto Market",
    "MeteorCoin Exchange",
    "AstroBit Exchange",
    "CosmosCrypto Exchange",
    "OrionCoin Market",
    "StarlightCrypto",
    "PulsarCoin Exchange",
    "NebulaTrade",
    "PhoenixCrypto Exchange",
    "AetherCoin Market",
    "CelestialCrypto Exchange",
    "NovaChain Exchange",
    "GalaxyBit Trade",
    "StarshipCrypto",
    "CometCoin Exchange",
    "HyperNova Exchange",
    "OrbitCrypto Exchange",
    "LuminousCoin Market",
    "InfinityBit Exchange",
    "QuasarCrypto",
    "StellarNova Exchange",
    "FusionBit Market",
    "AstroCoin Exchange",
    "GalacticCrypto",
    "EclipseCoin Exchange",
    "NebulaBit Market",
    "HyperCoin Exchange",
    "StellarChain Exchange",
    "LunaNova Crypto",
    "QuantumChain Market",
    "CelestialCoin Exchange",
]


def get_fake_bank_name() -> str:
    return random.choice(FAKE_BANK_NAMES) + " (Personal Banking)"


def get_fake_investment_bank_name() -> str:
    return random.choice(FAKE_INVESTMENT_BANK_NAMES) + " (Investment)"


def get_fake_checking_account_name() -> str:
    return random.choice(FAKE_CHECKING_ACCOUNT_NAMES)


def get_fake_savings_account_name() -> str:
    return random.choice(FAKE_SAVINGS_ACCOUNT_NAMES)


def get_fake_pension_fund_name() -> str:
    return random.choice(FAKE_PENSION_FUND_NAMES)


def get_fake_crypto_exchange_name() -> str:
    return random.choice(FAKE_CRYPTO_EXCHANGE_NAMES)
