/* tslint:disable */
/* eslint-disable */
/**
 * Finbot application service
 * API documentation for appwsrv
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ChatRequest,
  HTTPValidationError,
} from '../models/index';
import {
    ChatRequestFromJSON,
    ChatRequestToJSON,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
} from '../models/index';

export interface ChatOperationRequest {
    chatRequest: ChatRequest;
}

/**
 * ChatAssistantApi - interface
 * 
 * @export
 * @interface ChatAssistantApiInterface
 */
export interface ChatAssistantApiInterface {
    /**
     * Stream a chat response as Server-Sent Events.  Stateless: the client posts the full prior history with each request. The server does not persist conversations.
     * @summary Chat
     * @param {ChatRequest} chatRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ChatAssistantApiInterface
     */
    chatRaw(requestParameters: ChatOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>>;

    /**
     * Stream a chat response as Server-Sent Events.  Stateless: the client posts the full prior history with each request. The server does not persist conversations.
     * Chat
     */
    chat(requestParameters: ChatOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any>;

}

/**
 * 
 */
export class ChatAssistantApi extends runtime.BaseAPI implements ChatAssistantApiInterface {

    /**
     * Stream a chat response as Server-Sent Events.  Stateless: the client posts the full prior history with each request. The server does not persist conversations.
     * Chat
     */
    async chatRaw(requestParameters: ChatOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['chatRequest'] == null) {
            throw new runtime.RequiredError(
                'chatRequest',
                'Required parameter "chatRequest" was null or undefined when calling chat().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/chat/`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ChatRequestToJSON(requestParameters['chatRequest']),
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Stream a chat response as Server-Sent Events.  Stateless: the client posts the full prior history with each request. The server does not persist conversations.
     * Chat
     */
    async chat(requestParameters: ChatOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.chatRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
