/* tslint:disable */
/* eslint-disable */
/**
 * Finbot application service
 * API documentation for appwsrv
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from "../runtime";
import type { GetAccountsFormattingRulesResponse } from "../models/index";
import {
  GetAccountsFormattingRulesResponseFromJSON,
  GetAccountsFormattingRulesResponseToJSON,
} from "../models/index";

/**
 * FormattingRulesApi - interface
 *
 * @export
 * @interface FormattingRulesApiInterface
 */
export interface FormattingRulesApiInterface {
  /**
   * Get accounts formatting rules
   * @summary Get Accounts Formatting Rules
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof FormattingRulesApiInterface
   */
  getAccountsFormattingRulesRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<GetAccountsFormattingRulesResponse>>;

  /**
   * Get accounts formatting rules
   * Get Accounts Formatting Rules
   */
  getAccountsFormattingRules(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<GetAccountsFormattingRulesResponse>;
}

/**
 *
 */
export class FormattingRulesApi
  extends runtime.BaseAPI
  implements FormattingRulesApiInterface
{
  /**
   * Get accounts formatting rules
   * Get Accounts Formatting Rules
   */
  async getAccountsFormattingRulesRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<GetAccountsFormattingRulesResponse>> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token("HTTPBearer", []);

      if (tokenString) {
        headerParameters["Authorization"] = `Bearer ${tokenString}`;
      }
    }
    const response = await this.request(
      {
        path: `/formatting_rules/accounts/`,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      GetAccountsFormattingRulesResponseFromJSON(jsonValue),
    );
  }

  /**
   * Get accounts formatting rules
   * Get Accounts Formatting Rules
   */
  async getAccountsFormattingRules(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<GetAccountsFormattingRulesResponse> {
    const response = await this.getAccountsFormattingRulesRaw(initOverrides);
    return await response.value();
  }
}
