/* tslint:disable */
/* eslint-disable */
/**
 * Finbot application service
 * API documentation for appwsrv
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  HTTPValidationError,
  ResolveSecurityResponse,
  SearchSecuritiesResponse,
} from '../models/index';
import {
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
    ResolveSecurityResponseFromJSON,
    ResolveSecurityResponseToJSON,
    SearchSecuritiesResponseFromJSON,
    SearchSecuritiesResponseToJSON,
} from '../models/index';

export interface ResolveSecurityRequest {
    symbol: string;
}

export interface SearchSecuritiesRequest {
    q: string;
    kind?: SearchSecuritiesKindEnum;
    limit?: number;
}

/**
 * SecuritiesApi - interface
 * 
 * @export
 * @interface SecuritiesApiInterface
 */
export interface SecuritiesApiInterface {
    /**
     * Resolve a security by its Yahoo Finance symbol
     * @summary Resolve Security
     * @param {string} symbol 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SecuritiesApiInterface
     */
    resolveSecurityRaw(requestParameters: ResolveSecurityRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResolveSecurityResponse>>;

    /**
     * Resolve a security by its Yahoo Finance symbol
     * Resolve Security
     */
    resolveSecurity(requestParameters: ResolveSecurityRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResolveSecurityResponse>;

    /**
     * Search Yahoo Finance securities by symbol or name
     * @summary Search Securities
     * @param {string} q 
     * @param {'equity' | 'etf' | 'mutualfund' | 'index' | 'future' | 'currency' | 'cryptocurrency'} [kind] 
     * @param {number} [limit] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SecuritiesApiInterface
     */
    searchSecuritiesRaw(requestParameters: SearchSecuritiesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SearchSecuritiesResponse>>;

    /**
     * Search Yahoo Finance securities by symbol or name
     * Search Securities
     */
    searchSecurities(requestParameters: SearchSecuritiesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SearchSecuritiesResponse>;

}

/**
 * 
 */
export class SecuritiesApi extends runtime.BaseAPI implements SecuritiesApiInterface {

    /**
     * Resolve a security by its Yahoo Finance symbol
     * Resolve Security
     */
    async resolveSecurityRaw(requestParameters: ResolveSecurityRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResolveSecurityResponse>> {
        if (requestParameters['symbol'] == null) {
            throw new runtime.RequiredError(
                'symbol',
                'Required parameter "symbol" was null or undefined when calling resolveSecurity().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['symbol'] != null) {
            queryParameters['symbol'] = requestParameters['symbol'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/securities/resolve/`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResolveSecurityResponseFromJSON(jsonValue));
    }

    /**
     * Resolve a security by its Yahoo Finance symbol
     * Resolve Security
     */
    async resolveSecurity(requestParameters: ResolveSecurityRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResolveSecurityResponse> {
        const response = await this.resolveSecurityRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Search Yahoo Finance securities by symbol or name
     * Search Securities
     */
    async searchSecuritiesRaw(requestParameters: SearchSecuritiesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SearchSecuritiesResponse>> {
        if (requestParameters['q'] == null) {
            throw new runtime.RequiredError(
                'q',
                'Required parameter "q" was null or undefined when calling searchSecurities().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['q'] != null) {
            queryParameters['q'] = requestParameters['q'];
        }

        if (requestParameters['kind'] != null) {
            queryParameters['kind'] = requestParameters['kind'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/securities/search/`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SearchSecuritiesResponseFromJSON(jsonValue));
    }

    /**
     * Search Yahoo Finance securities by symbol or name
     * Search Securities
     */
    async searchSecurities(requestParameters: SearchSecuritiesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SearchSecuritiesResponse> {
        const response = await this.searchSecuritiesRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const SearchSecuritiesKindEnum = {
    Equity: 'equity',
    Etf: 'etf',
    Mutualfund: 'mutualfund',
    Index: 'index',
    Future: 'future',
    Currency: 'currency',
    Cryptocurrency: 'cryptocurrency'
} as const;
export type SearchSecuritiesKindEnum = typeof SearchSecuritiesKindEnum[keyof typeof SearchSecuritiesKindEnum];
