/* tslint:disable */
/* eslint-disable */
/**
 * Finbot application service
 * API documentation for appwsrv
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from "../runtime";
import type { HealthResponse, SystemReportResponse } from "../models/index";
import {
  HealthResponseFromJSON,
  HealthResponseToJSON,
  SystemReportResponseFromJSON,
  SystemReportResponseToJSON,
} from "../models/index";

/**
 * SystemApi - interface
 *
 * @export
 * @interface SystemApiInterface
 */
export interface SystemApiInterface {
  /**
   * Get system report
   * @summary Get System Report
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof SystemApiInterface
   */
  getSystemReportRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<SystemReportResponse>>;

  /**
   * Get system report
   * Get System Report
   */
  getSystemReport(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<SystemReportResponse>;

  /**
   * Is server healthy
   * @summary Healthy
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof SystemApiInterface
   */
  isHealthyRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<HealthResponse>>;

  /**
   * Is server healthy
   * Healthy
   */
  isHealthy(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<HealthResponse>;
}

/**
 *
 */
export class SystemApi extends runtime.BaseAPI implements SystemApiInterface {
  /**
   * Get system report
   * Get System Report
   */
  async getSystemReportRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<SystemReportResponse>> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/system_report/`,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      SystemReportResponseFromJSON(jsonValue),
    );
  }

  /**
   * Get system report
   * Get System Report
   */
  async getSystemReport(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<SystemReportResponse> {
    const response = await this.getSystemReportRaw(initOverrides);
    return await response.value();
  }

  /**
   * Is server healthy
   * Healthy
   */
  async isHealthyRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<HealthResponse>> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/healthy/`,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      HealthResponseFromJSON(jsonValue),
    );
  }

  /**
   * Is server healthy
   * Healthy
   */
  async isHealthy(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<HealthResponse> {
    const response = await this.isHealthyRaw(initOverrides);
    return await response.value();
  }
}
