/* tslint:disable */
/* eslint-disable */
/**
 * Finbot application service
 * API documentation for appwsrv
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  GetCashFlowSummaryResponse,
  GetCashFlowTimeSeriesResponse,
  GetEarningsReportResponse,
  GetHoldingsReportResponse,
  GetSavingsRateReportResponse,
  GetSpendingBreakdownResponse,
  GetTransactionResponse,
  GetTransactionsReportResponse,
  HTTPValidationError,
} from '../models/index';
import {
    GetCashFlowSummaryResponseFromJSON,
    GetCashFlowSummaryResponseToJSON,
    GetCashFlowTimeSeriesResponseFromJSON,
    GetCashFlowTimeSeriesResponseToJSON,
    GetEarningsReportResponseFromJSON,
    GetEarningsReportResponseToJSON,
    GetHoldingsReportResponseFromJSON,
    GetHoldingsReportResponseToJSON,
    GetSavingsRateReportResponseFromJSON,
    GetSavingsRateReportResponseToJSON,
    GetSpendingBreakdownResponseFromJSON,
    GetSpendingBreakdownResponseToJSON,
    GetTransactionResponseFromJSON,
    GetTransactionResponseToJSON,
    GetTransactionsReportResponseFromJSON,
    GetTransactionsReportResponseToJSON,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
} from '../models/index';

export interface GetTransactionRequest {
    transactionId: number;
}

export interface GetUserAccountCashFlowSummaryRequest {
    fromTime?: Date | null;
    toTime?: Date | null;
}

export interface GetUserAccountCashFlowTimeSeriesRequest {
    fromTime?: Date | null;
    toTime?: Date | null;
    frequency?: string;
    linkedAccountId?: number | null;
}

export interface GetUserAccountSavingsRateRequest {
    comparisonMonth?: string | null;
}

export interface GetUserAccountSpendingBreakdownRequest {
    fromTime?: Date | null;
    toTime?: Date | null;
}

export interface GetUserAccountTransactionsReportRequest {
    fromTime?: Date | null;
    toTime?: Date | null;
    linkedAccountId?: Array<number> | null;
    transactionType?: Array<string> | null;
    spendingCategory?: Array<string> | null;
    limit?: number;
    offset?: number;
}

/**
 * UserAccountsReportsApi - interface
 * 
 * @export
 * @interface UserAccountsReportsApiInterface
 */
export interface UserAccountsReportsApiInterface {
    /**
     * Get a single transaction by ID
     * @summary Get Transaction
     * @param {number} transactionId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UserAccountsReportsApiInterface
     */
    getTransactionRaw(requestParameters: GetTransactionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetTransactionResponse>>;

    /**
     * Get a single transaction by ID
     * Get Transaction
     */
    getTransaction(requestParameters: GetTransactionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetTransactionResponse>;

    /**
     * Get cash flow summary by transaction category
     * @summary Get Cash Flow Summary
     * @param {Date} [fromTime] 
     * @param {Date} [toTime] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UserAccountsReportsApiInterface
     */
    getUserAccountCashFlowSummaryRaw(requestParameters: GetUserAccountCashFlowSummaryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetCashFlowSummaryResponse>>;

    /**
     * Get cash flow summary by transaction category
     * Get Cash Flow Summary
     */
    getUserAccountCashFlowSummary(requestParameters: GetUserAccountCashFlowSummaryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetCashFlowSummaryResponse>;

    /**
     * Get time-bucketed cash flow data
     * @summary Get Cash Flow Time Series
     * @param {Date} [fromTime] 
     * @param {Date} [toTime] 
     * @param {string} [frequency] 
     * @param {number} [linkedAccountId] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UserAccountsReportsApiInterface
     */
    getUserAccountCashFlowTimeSeriesRaw(requestParameters: GetUserAccountCashFlowTimeSeriesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetCashFlowTimeSeriesResponse>>;

    /**
     * Get time-bucketed cash flow data
     * Get Cash Flow Time Series
     */
    getUserAccountCashFlowTimeSeries(requestParameters: GetUserAccountCashFlowTimeSeriesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetCashFlowTimeSeriesResponse>;

    /**
     * Get earnings report
     * @summary Get Earnings Report
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UserAccountsReportsApiInterface
     */
    getUserAccountEarningsReportRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetEarningsReportResponse>>;

    /**
     * Get earnings report
     * Get Earnings Report
     */
    getUserAccountEarningsReport(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetEarningsReportResponse>;

    /**
     * Get holdings report
     * @summary Get Holdings Report
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UserAccountsReportsApiInterface
     */
    getUserAccountHoldingsReportRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetHoldingsReportResponse>>;

    /**
     * Get holdings report
     * Get Holdings Report
     */
    getUserAccountHoldingsReport(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetHoldingsReportResponse>;

    /**
     * Get monthly savings rate (current month vs comparison month)
     * @summary Get Savings Rate
     * @param {string} [comparisonMonth] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UserAccountsReportsApiInterface
     */
    getUserAccountSavingsRateRaw(requestParameters: GetUserAccountSavingsRateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetSavingsRateReportResponse>>;

    /**
     * Get monthly savings rate (current month vs comparison month)
     * Get Savings Rate
     */
    getUserAccountSavingsRate(requestParameters: GetUserAccountSavingsRateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetSavingsRateReportResponse>;

    /**
     * Get spending totals grouped by PFC primary category
     * @summary Get Spending Breakdown
     * @param {Date} [fromTime] 
     * @param {Date} [toTime] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UserAccountsReportsApiInterface
     */
    getUserAccountSpendingBreakdownRaw(requestParameters: GetUserAccountSpendingBreakdownRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetSpendingBreakdownResponse>>;

    /**
     * Get spending totals grouped by PFC primary category
     * Get Spending Breakdown
     */
    getUserAccountSpendingBreakdown(requestParameters: GetUserAccountSpendingBreakdownRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetSpendingBreakdownResponse>;

    /**
     * Get paginated transactions report
     * @summary Get Transactions Report
     * @param {Date} [fromTime] 
     * @param {Date} [toTime] 
     * @param {Array<number>} [linkedAccountId] 
     * @param {Array<string>} [transactionType] 
     * @param {Array<string>} [spendingCategory] 
     * @param {number} [limit] 
     * @param {number} [offset] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UserAccountsReportsApiInterface
     */
    getUserAccountTransactionsReportRaw(requestParameters: GetUserAccountTransactionsReportRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetTransactionsReportResponse>>;

    /**
     * Get paginated transactions report
     * Get Transactions Report
     */
    getUserAccountTransactionsReport(requestParameters: GetUserAccountTransactionsReportRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetTransactionsReportResponse>;

}

/**
 * 
 */
export class UserAccountsReportsApi extends runtime.BaseAPI implements UserAccountsReportsApiInterface {

    /**
     * Get a single transaction by ID
     * Get Transaction
     */
    async getTransactionRaw(requestParameters: GetTransactionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetTransactionResponse>> {
        if (requestParameters['transactionId'] == null) {
            throw new runtime.RequiredError(
                'transactionId',
                'Required parameter "transactionId" was null or undefined when calling getTransaction().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/reports/transactions/{transaction_id}/`.replace(`{${"transaction_id"}}`, encodeURIComponent(String(requestParameters['transactionId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetTransactionResponseFromJSON(jsonValue));
    }

    /**
     * Get a single transaction by ID
     * Get Transaction
     */
    async getTransaction(requestParameters: GetTransactionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetTransactionResponse> {
        const response = await this.getTransactionRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get cash flow summary by transaction category
     * Get Cash Flow Summary
     */
    async getUserAccountCashFlowSummaryRaw(requestParameters: GetUserAccountCashFlowSummaryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetCashFlowSummaryResponse>> {
        const queryParameters: any = {};

        if (requestParameters['fromTime'] != null) {
            queryParameters['from_time'] = (requestParameters['fromTime'] as any).toISOString();
        }

        if (requestParameters['toTime'] != null) {
            queryParameters['to_time'] = (requestParameters['toTime'] as any).toISOString();
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/reports/cash-flow/summary/`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetCashFlowSummaryResponseFromJSON(jsonValue));
    }

    /**
     * Get cash flow summary by transaction category
     * Get Cash Flow Summary
     */
    async getUserAccountCashFlowSummary(requestParameters: GetUserAccountCashFlowSummaryRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetCashFlowSummaryResponse> {
        const response = await this.getUserAccountCashFlowSummaryRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get time-bucketed cash flow data
     * Get Cash Flow Time Series
     */
    async getUserAccountCashFlowTimeSeriesRaw(requestParameters: GetUserAccountCashFlowTimeSeriesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetCashFlowTimeSeriesResponse>> {
        const queryParameters: any = {};

        if (requestParameters['fromTime'] != null) {
            queryParameters['from_time'] = (requestParameters['fromTime'] as any).toISOString();
        }

        if (requestParameters['toTime'] != null) {
            queryParameters['to_time'] = (requestParameters['toTime'] as any).toISOString();
        }

        if (requestParameters['frequency'] != null) {
            queryParameters['frequency'] = requestParameters['frequency'];
        }

        if (requestParameters['linkedAccountId'] != null) {
            queryParameters['linked_account_id'] = requestParameters['linkedAccountId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/reports/cash-flow/time-series/`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetCashFlowTimeSeriesResponseFromJSON(jsonValue));
    }

    /**
     * Get time-bucketed cash flow data
     * Get Cash Flow Time Series
     */
    async getUserAccountCashFlowTimeSeries(requestParameters: GetUserAccountCashFlowTimeSeriesRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetCashFlowTimeSeriesResponse> {
        const response = await this.getUserAccountCashFlowTimeSeriesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get earnings report
     * Get Earnings Report
     */
    async getUserAccountEarningsReportRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetEarningsReportResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/reports/earnings/`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetEarningsReportResponseFromJSON(jsonValue));
    }

    /**
     * Get earnings report
     * Get Earnings Report
     */
    async getUserAccountEarningsReport(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetEarningsReportResponse> {
        const response = await this.getUserAccountEarningsReportRaw(initOverrides);
        return await response.value();
    }

    /**
     * Get holdings report
     * Get Holdings Report
     */
    async getUserAccountHoldingsReportRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetHoldingsReportResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/reports/holdings/`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetHoldingsReportResponseFromJSON(jsonValue));
    }

    /**
     * Get holdings report
     * Get Holdings Report
     */
    async getUserAccountHoldingsReport(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetHoldingsReportResponse> {
        const response = await this.getUserAccountHoldingsReportRaw(initOverrides);
        return await response.value();
    }

    /**
     * Get monthly savings rate (current month vs comparison month)
     * Get Savings Rate
     */
    async getUserAccountSavingsRateRaw(requestParameters: GetUserAccountSavingsRateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetSavingsRateReportResponse>> {
        const queryParameters: any = {};

        if (requestParameters['comparisonMonth'] != null) {
            queryParameters['comparison_month'] = requestParameters['comparisonMonth'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/reports/savings-rate/`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetSavingsRateReportResponseFromJSON(jsonValue));
    }

    /**
     * Get monthly savings rate (current month vs comparison month)
     * Get Savings Rate
     */
    async getUserAccountSavingsRate(requestParameters: GetUserAccountSavingsRateRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetSavingsRateReportResponse> {
        const response = await this.getUserAccountSavingsRateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get spending totals grouped by PFC primary category
     * Get Spending Breakdown
     */
    async getUserAccountSpendingBreakdownRaw(requestParameters: GetUserAccountSpendingBreakdownRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetSpendingBreakdownResponse>> {
        const queryParameters: any = {};

        if (requestParameters['fromTime'] != null) {
            queryParameters['from_time'] = (requestParameters['fromTime'] as any).toISOString();
        }

        if (requestParameters['toTime'] != null) {
            queryParameters['to_time'] = (requestParameters['toTime'] as any).toISOString();
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/reports/spending/breakdown/`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetSpendingBreakdownResponseFromJSON(jsonValue));
    }

    /**
     * Get spending totals grouped by PFC primary category
     * Get Spending Breakdown
     */
    async getUserAccountSpendingBreakdown(requestParameters: GetUserAccountSpendingBreakdownRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetSpendingBreakdownResponse> {
        const response = await this.getUserAccountSpendingBreakdownRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get paginated transactions report
     * Get Transactions Report
     */
    async getUserAccountTransactionsReportRaw(requestParameters: GetUserAccountTransactionsReportRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetTransactionsReportResponse>> {
        const queryParameters: any = {};

        if (requestParameters['fromTime'] != null) {
            queryParameters['from_time'] = (requestParameters['fromTime'] as any).toISOString();
        }

        if (requestParameters['toTime'] != null) {
            queryParameters['to_time'] = (requestParameters['toTime'] as any).toISOString();
        }

        if (requestParameters['linkedAccountId'] != null) {
            queryParameters['linked_account_id'] = requestParameters['linkedAccountId'];
        }

        if (requestParameters['transactionType'] != null) {
            queryParameters['transaction_type'] = requestParameters['transactionType'];
        }

        if (requestParameters['spendingCategory'] != null) {
            queryParameters['spending_category'] = requestParameters['spendingCategory'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/reports/transactions/`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetTransactionsReportResponseFromJSON(jsonValue));
    }

    /**
     * Get paginated transactions report
     * Get Transactions Report
     */
    async getUserAccountTransactionsReport(requestParameters: GetUserAccountTransactionsReportRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetTransactionsReportResponse> {
        const response = await this.getUserAccountTransactionsReportRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
