/* tslint:disable */
/* eslint-disable */
/**
 * Finbot application service
 * API documentation for appwsrv
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  DismissNotificationResponse,
  GetNotificationsResponse,
  HTTPValidationError,
  MarkNotificationsReadRequest,
  MarkNotificationsReadResponse,
} from '../models/index';
import {
    DismissNotificationResponseFromJSON,
    DismissNotificationResponseToJSON,
    GetNotificationsResponseFromJSON,
    GetNotificationsResponseToJSON,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
    MarkNotificationsReadRequestFromJSON,
    MarkNotificationsReadRequestToJSON,
    MarkNotificationsReadResponseFromJSON,
    MarkNotificationsReadResponseToJSON,
} from '../models/index';

export interface DismissAllNotificationsRequest {
    userAccountId: number;
}

export interface DismissNotificationRequest {
    userAccountId: number;
    notificationId: number;
}

export interface GetNotificationsRequest {
    userAccountId: number;
    limit?: number;
}

export interface MarkNotificationsReadOperationRequest {
    userAccountId: number;
    markNotificationsReadRequest: MarkNotificationsReadRequest;
}

/**
 * UserAccountsNotificationsApi - interface
 * 
 * @export
 * @interface UserAccountsNotificationsApiInterface
 */
export interface UserAccountsNotificationsApiInterface {
    /**
     * Dismiss every notification currently in the panel
     * @summary Dismiss All Notifications
     * @param {number} userAccountId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UserAccountsNotificationsApiInterface
     */
    dismissAllNotificationsRaw(requestParameters: DismissAllNotificationsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DismissNotificationResponse>>;

    /**
     * Dismiss every notification currently in the panel
     * Dismiss All Notifications
     */
    dismissAllNotifications(requestParameters: DismissAllNotificationsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DismissNotificationResponse>;

    /**
     * Dismiss a notification.  Dismissing also closes its aggregation window: should the same problem happen again, it is reported as a new notification rather than quietly incrementing this one.
     * @summary Dismiss Notification
     * @param {number} userAccountId 
     * @param {number} notificationId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UserAccountsNotificationsApiInterface
     */
    dismissNotificationRaw(requestParameters: DismissNotificationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DismissNotificationResponse>>;

    /**
     * Dismiss a notification.  Dismissing also closes its aggregation window: should the same problem happen again, it is reported as a new notification rather than quietly incrementing this one.
     * Dismiss Notification
     */
    dismissNotification(requestParameters: DismissNotificationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DismissNotificationResponse>;

    /**
     * Get in-app notifications for this user account
     * @summary Get Notifications
     * @param {number} userAccountId 
     * @param {number} [limit] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UserAccountsNotificationsApiInterface
     */
    getNotificationsRaw(requestParameters: GetNotificationsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetNotificationsResponse>>;

    /**
     * Get in-app notifications for this user account
     * Get Notifications
     */
    getNotifications(requestParameters: GetNotificationsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetNotificationsResponse>;

    /**
     * Mark notifications as read, or all of them when no ids are given
     * @summary Mark Notifications Read
     * @param {number} userAccountId 
     * @param {MarkNotificationsReadRequest} markNotificationsReadRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UserAccountsNotificationsApiInterface
     */
    markNotificationsReadRaw(requestParameters: MarkNotificationsReadOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MarkNotificationsReadResponse>>;

    /**
     * Mark notifications as read, or all of them when no ids are given
     * Mark Notifications Read
     */
    markNotificationsRead(requestParameters: MarkNotificationsReadOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MarkNotificationsReadResponse>;

}

/**
 * 
 */
export class UserAccountsNotificationsApi extends runtime.BaseAPI implements UserAccountsNotificationsApiInterface {

    /**
     * Dismiss every notification currently in the panel
     * Dismiss All Notifications
     */
    async dismissAllNotificationsRaw(requestParameters: DismissAllNotificationsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DismissNotificationResponse>> {
        if (requestParameters['userAccountId'] == null) {
            throw new runtime.RequiredError(
                'userAccountId',
                'Required parameter "userAccountId" was null or undefined when calling dismissAllNotifications().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/accounts/{user_account_id}/notifications/dismiss-all/`.replace(`{${"user_account_id"}}`, encodeURIComponent(String(requestParameters['userAccountId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DismissNotificationResponseFromJSON(jsonValue));
    }

    /**
     * Dismiss every notification currently in the panel
     * Dismiss All Notifications
     */
    async dismissAllNotifications(requestParameters: DismissAllNotificationsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DismissNotificationResponse> {
        const response = await this.dismissAllNotificationsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Dismiss a notification.  Dismissing also closes its aggregation window: should the same problem happen again, it is reported as a new notification rather than quietly incrementing this one.
     * Dismiss Notification
     */
    async dismissNotificationRaw(requestParameters: DismissNotificationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DismissNotificationResponse>> {
        if (requestParameters['userAccountId'] == null) {
            throw new runtime.RequiredError(
                'userAccountId',
                'Required parameter "userAccountId" was null or undefined when calling dismissNotification().'
            );
        }

        if (requestParameters['notificationId'] == null) {
            throw new runtime.RequiredError(
                'notificationId',
                'Required parameter "notificationId" was null or undefined when calling dismissNotification().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/accounts/{user_account_id}/notifications/{notification_id}/dismiss/`.replace(`{${"user_account_id"}}`, encodeURIComponent(String(requestParameters['userAccountId']))).replace(`{${"notification_id"}}`, encodeURIComponent(String(requestParameters['notificationId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DismissNotificationResponseFromJSON(jsonValue));
    }

    /**
     * Dismiss a notification.  Dismissing also closes its aggregation window: should the same problem happen again, it is reported as a new notification rather than quietly incrementing this one.
     * Dismiss Notification
     */
    async dismissNotification(requestParameters: DismissNotificationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DismissNotificationResponse> {
        const response = await this.dismissNotificationRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get in-app notifications for this user account
     * Get Notifications
     */
    async getNotificationsRaw(requestParameters: GetNotificationsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetNotificationsResponse>> {
        if (requestParameters['userAccountId'] == null) {
            throw new runtime.RequiredError(
                'userAccountId',
                'Required parameter "userAccountId" was null or undefined when calling getNotifications().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/accounts/{user_account_id}/notifications/`.replace(`{${"user_account_id"}}`, encodeURIComponent(String(requestParameters['userAccountId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetNotificationsResponseFromJSON(jsonValue));
    }

    /**
     * Get in-app notifications for this user account
     * Get Notifications
     */
    async getNotifications(requestParameters: GetNotificationsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetNotificationsResponse> {
        const response = await this.getNotificationsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Mark notifications as read, or all of them when no ids are given
     * Mark Notifications Read
     */
    async markNotificationsReadRaw(requestParameters: MarkNotificationsReadOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MarkNotificationsReadResponse>> {
        if (requestParameters['userAccountId'] == null) {
            throw new runtime.RequiredError(
                'userAccountId',
                'Required parameter "userAccountId" was null or undefined when calling markNotificationsRead().'
            );
        }

        if (requestParameters['markNotificationsReadRequest'] == null) {
            throw new runtime.RequiredError(
                'markNotificationsReadRequest',
                'Required parameter "markNotificationsReadRequest" was null or undefined when calling markNotificationsRead().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/accounts/{user_account_id}/notifications/mark-read/`.replace(`{${"user_account_id"}}`, encodeURIComponent(String(requestParameters['userAccountId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: MarkNotificationsReadRequestToJSON(requestParameters['markNotificationsReadRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MarkNotificationsReadResponseFromJSON(jsonValue));
    }

    /**
     * Mark notifications as read, or all of them when no ids are given
     * Mark Notifications Read
     */
    async markNotificationsRead(requestParameters: MarkNotificationsReadOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MarkNotificationsReadResponse> {
        const response = await this.markNotificationsReadRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
