"""drop distributed tracing table

Revision ID: 4305433d5c7a
Revises: 7add1f3d40ce
Create Date: 2023-02-27 16:22:50.817943

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4305433d5c7a'
down_revision = '7add1f3d40ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('finbot_distributed_traces')
    op.drop_column('finbot_user_accounts_history_entries', 'trace_guid')
    op.drop_column('finbot_user_accounts_snapshots', 'trace_guid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('finbot_user_accounts_snapshots', sa.Column('trace_guid', sa.VARCHAR(length=36), autoincrement=False, nullable=True))
    op.add_column('finbot_user_accounts_history_entries', sa.Column('trace_guid', sa.VARCHAR(length=36), autoincrement=False, nullable=True))
    op.create_table('finbot_distributed_traces',
    sa.Column('guid', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('path', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('user_data', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('start_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('end_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('guid', 'path', 'name', name='finbot_distributed_traces_pkey')
    )
    # ### end Alembic commands ###
