"""Plaid settings

Revision ID: 4ff5c47e587d
Revises: 418d0d0013a2
Create Date: 2021-01-03 13:36:30.118478

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ff5c47e587d'
down_revision = '418d0d0013a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('finbot_user_accounts_plaid_settings',
    sa.Column('user_account_id', sa.Integer(), nullable=False),
    sa.Column('env', sa.String(length=32), nullable=False),
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.Column('public_key', sa.String(length=64), nullable=False),
    sa.Column('secret_key', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['user_account_id'], ['finbot_user_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_account_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('finbot_user_accounts_plaid_settings')
    # ### end Alembic commands ###
