"""add trace to snapshot and report

Revision ID: 66e9a9d27434
Revises: c035a811d69a
Create Date: 2021-04-05 11:03:11.311130

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66e9a9d27434'
down_revision = 'c035a811d69a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('finbot_user_accounts_history_entries', sa.Column('trace_guid', sa.String(length=36), nullable=True))
    op.add_column('finbot_user_accounts_snapshots', sa.Column('trace_guid', sa.String(length=36), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('finbot_user_accounts_snapshots', 'trace_guid')
    op.drop_column('finbot_user_accounts_history_entries', 'trace_guid')
    # ### end Alembic commands ###
