"""add twilio settings

Revision ID: b97ac7612883
Revises: 7d3d027c4bbb
Create Date: 2021-04-09 20:34:28.275449

"""
from alembic import op
import sqlalchemy as sa

from finbot.core.dbutils import JSONEncoded


# revision identifiers, used by Alembic.
revision = 'b97ac7612883'
down_revision = '7d3d027c4bbb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('finbot_user_accounts_settings', sa.Column('twilio_settings', JSONEncoded(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('finbot_user_accounts_settings', 'twilio_settings')
    # ### end Alembic commands ###
