/* tslint:disable */
/* eslint-disable */
/**
 * Finbot application service
 * API documentation for appwsrv
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const AccountType = {
    Depository: 'depository',
    Credit: 'credit',
    Loan: 'loan',
    Investment: 'investment',
    Other: 'other'
} as const;
export type AccountType = typeof AccountType[keyof typeof AccountType];


export function instanceOfAccountType(value: any): boolean {
    for (const key in AccountType) {
        if (Object.prototype.hasOwnProperty.call(AccountType, key)) {
            if (AccountType[key as keyof typeof AccountType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function AccountTypeFromJSON(json: any): AccountType {
    return AccountTypeFromJSONTyped(json, false);
}

export function AccountTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccountType {
    return json as AccountType;
}

export function AccountTypeToJSON(value?: AccountType | null): any {
    return value as any;
}

export function AccountTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): AccountType {
    return value as AccountType;
}

