/* tslint:disable */
/* eslint-disable */
/**
 * Finbot application service
 * API documentation for appwsrv
 *
 * The version of the OpenAPI document: v0.0.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AggregationDescription
 */
export interface AggregationDescription {
    /**
     * 
     * @type {string}
     * @memberof AggregationDescription
     */
    asStr: string;
}

/**
 * Check if a given object implements the AggregationDescription interface.
 */
export function instanceOfAggregationDescription(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "asStr" in value;

    return isInstance;
}

export function AggregationDescriptionFromJSON(json: any): AggregationDescription {
    return AggregationDescriptionFromJSONTyped(json, false);
}

export function AggregationDescriptionFromJSONTyped(json: any, ignoreDiscriminator: boolean): AggregationDescription {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'asStr': json['as_str'],
    };
}

export function AggregationDescriptionToJSON(value?: AggregationDescription | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'as_str': value.asStr,
    };
}

