/* tslint:disable */
/* eslint-disable */
/**
 * Finbot application service
 * API documentation for appwsrv
 *
 * The version of the OpenAPI document: v0.0.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface AppCreateOrUpdateProviderRequest
 */
export interface AppCreateOrUpdateProviderRequest {
  /**
   *
   * @type {string}
   * @memberof AppCreateOrUpdateProviderRequest
   */
  id: string;
  /**
   *
   * @type {string}
   * @memberof AppCreateOrUpdateProviderRequest
   */
  description: string;
  /**
   *
   * @type {string}
   * @memberof AppCreateOrUpdateProviderRequest
   */
  websiteUrl: string;
  /**
   *
   * @type {object}
   * @memberof AppCreateOrUpdateProviderRequest
   */
  credentialsSchema: object;
}

/**
 * Check if a given object implements the AppCreateOrUpdateProviderRequest interface.
 */
export function instanceOfAppCreateOrUpdateProviderRequest(
  value: object,
): boolean {
  let isInstance = true;
  isInstance = isInstance && "id" in value;
  isInstance = isInstance && "description" in value;
  isInstance = isInstance && "websiteUrl" in value;
  isInstance = isInstance && "credentialsSchema" in value;

  return isInstance;
}

export function AppCreateOrUpdateProviderRequestFromJSON(
  json: any,
): AppCreateOrUpdateProviderRequest {
  return AppCreateOrUpdateProviderRequestFromJSONTyped(json, false);
}

export function AppCreateOrUpdateProviderRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): AppCreateOrUpdateProviderRequest {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    id: json["id"],
    description: json["description"],
    websiteUrl: json["website_url"],
    credentialsSchema: json["credentials_schema"],
  };
}

export function AppCreateOrUpdateProviderRequestToJSON(
  value?: AppCreateOrUpdateProviderRequest | null,
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    id: value.id,
    description: value.description,
    website_url: value.websiteUrl,
    credentials_schema: value.credentialsSchema,
  };
}
