/* tslint:disable */
/* eslint-disable */
/**
 * Finbot application service
 * API documentation for appwsrv
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface AppCreateOrUpdateProviderRequest
 */
export interface AppCreateOrUpdateProviderRequest {
  /**
   *
   * @type {string}
   * @memberof AppCreateOrUpdateProviderRequest
   */
  id: string;
  /**
   *
   * @type {string}
   * @memberof AppCreateOrUpdateProviderRequest
   */
  description: string;
  /**
   *
   * @type {string}
   * @memberof AppCreateOrUpdateProviderRequest
   */
  websiteUrl: string;
  /**
   *
   * @type {object}
   * @memberof AppCreateOrUpdateProviderRequest
   */
  credentialsSchema: object;
}

/**
 * Check if a given object implements the AppCreateOrUpdateProviderRequest interface.
 */
export function instanceOfAppCreateOrUpdateProviderRequest(
  value: object,
): value is AppCreateOrUpdateProviderRequest {
  if (!("id" in value) || value["id"] === undefined) return false;
  if (!("description" in value) || value["description"] === undefined)
    return false;
  if (!("websiteUrl" in value) || value["websiteUrl"] === undefined)
    return false;
  if (
    !("credentialsSchema" in value) ||
    value["credentialsSchema"] === undefined
  )
    return false;
  return true;
}

export function AppCreateOrUpdateProviderRequestFromJSON(
  json: any,
): AppCreateOrUpdateProviderRequest {
  return AppCreateOrUpdateProviderRequestFromJSONTyped(json, false);
}

export function AppCreateOrUpdateProviderRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): AppCreateOrUpdateProviderRequest {
  if (json == null) {
    return json;
  }
  return {
    id: json["id"],
    description: json["description"],
    websiteUrl: json["website_url"],
    credentialsSchema: json["credentials_schema"],
  };
}

export function AppCreateOrUpdateProviderRequestToJSON(
  value?: AppCreateOrUpdateProviderRequest | null,
): any {
  if (value == null) {
    return value;
  }
  return {
    id: value["id"],
    description: value["description"],
    website_url: value["websiteUrl"],
    credentials_schema: value["credentialsSchema"],
  };
}
