/* tslint:disable */
/* eslint-disable */
/**
 * Finbot application service
 * API documentation for appwsrv
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import type { ValuationTree } from "./ValuationTree";
import {
  ValuationTreeFromJSON,
  ValuationTreeFromJSONTyped,
  ValuationTreeToJSON,
} from "./ValuationTree";

/**
 *
 * @export
 * @interface AppGetHoldingsReportResponse
 */
export interface AppGetHoldingsReportResponse {
  /**
   *
   * @type {ValuationTree}
   * @memberof AppGetHoldingsReportResponse
   */
  report: ValuationTree;
}

/**
 * Check if a given object implements the AppGetHoldingsReportResponse interface.
 */
export function instanceOfAppGetHoldingsReportResponse(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && "report" in value;

  return isInstance;
}

export function AppGetHoldingsReportResponseFromJSON(
  json: any,
): AppGetHoldingsReportResponse {
  return AppGetHoldingsReportResponseFromJSONTyped(json, false);
}

export function AppGetHoldingsReportResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): AppGetHoldingsReportResponse {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    report: ValuationTreeFromJSON(json["report"]),
  };
}

export function AppGetHoldingsReportResponseToJSON(
  value?: AppGetHoldingsReportResponse | null,
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    report: ValuationTreeToJSON(value.report),
  };
}
