/* tslint:disable */
/* eslint-disable */
/**
 * Finbot application service
 * API documentation for appwsrv
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import type { UserAccountSettings } from "./UserAccountSettings";
import {
  UserAccountSettingsFromJSON,
  UserAccountSettingsFromJSONTyped,
  UserAccountSettingsToJSON,
} from "./UserAccountSettings";

/**
 *
 * @export
 * @interface AppGetUserAccountSettingsResponse
 */
export interface AppGetUserAccountSettingsResponse {
  /**
   *
   * @type {UserAccountSettings}
   * @memberof AppGetUserAccountSettingsResponse
   */
  settings: UserAccountSettings;
}

/**
 * Check if a given object implements the AppGetUserAccountSettingsResponse interface.
 */
export function instanceOfAppGetUserAccountSettingsResponse(
  value: object,
): boolean {
  let isInstance = true;
  isInstance = isInstance && "settings" in value;

  return isInstance;
}

export function AppGetUserAccountSettingsResponseFromJSON(
  json: any,
): AppGetUserAccountSettingsResponse {
  return AppGetUserAccountSettingsResponseFromJSONTyped(json, false);
}

export function AppGetUserAccountSettingsResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): AppGetUserAccountSettingsResponse {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    settings: UserAccountSettingsFromJSON(json["settings"]),
  };
}

export function AppGetUserAccountSettingsResponseToJSON(
  value?: AppGetUserAccountSettingsResponse | null,
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    settings: UserAccountSettingsToJSON(value.settings),
  };
}
