/* tslint:disable */
/* eslint-disable */
/**
 * Finbot application service
 * API documentation for appwsrv
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import type { AuthenticationPayload } from "./AuthenticationPayload";
import {
  AuthenticationPayloadFromJSON,
  AuthenticationPayloadFromJSONTyped,
  AuthenticationPayloadToJSON,
} from "./AuthenticationPayload";
import type { UserAccount } from "./UserAccount";
import {
  UserAccountFromJSON,
  UserAccountFromJSONTyped,
  UserAccountToJSON,
} from "./UserAccount";

/**
 *
 * @export
 * @interface AppLoginResponse
 */
export interface AppLoginResponse {
  /**
   *
   * @type {AuthenticationPayload}
   * @memberof AppLoginResponse
   */
  auth: AuthenticationPayload;
  /**
   *
   * @type {UserAccount}
   * @memberof AppLoginResponse
   */
  account: UserAccount;
}

/**
 * Check if a given object implements the AppLoginResponse interface.
 */
export function instanceOfAppLoginResponse(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && "auth" in value;
  isInstance = isInstance && "account" in value;

  return isInstance;
}

export function AppLoginResponseFromJSON(json: any): AppLoginResponse {
  return AppLoginResponseFromJSONTyped(json, false);
}

export function AppLoginResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): AppLoginResponse {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    auth: AuthenticationPayloadFromJSON(json["auth"]),
    account: UserAccountFromJSON(json["account"]),
  };
}

export function AppLoginResponseToJSON(value?: AppLoginResponse | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    auth: AuthenticationPayloadToJSON(value.auth),
    account: UserAccountToJSON(value.account),
  };
}
