/* tslint:disable */
/* eslint-disable */
/**
 * Finbot application service
 * API documentation for appwsrv
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface AppSetEmailDeliverySettingsParams
 */
export interface AppSetEmailDeliverySettingsParams {
  /**
   *
   * @type {boolean}
   * @memberof AppSetEmailDeliverySettingsParams
   */
  validate?: boolean;
}

/**
 * Check if a given object implements the AppSetEmailDeliverySettingsParams interface.
 */
export function instanceOfAppSetEmailDeliverySettingsParams(
  value: object,
): value is AppSetEmailDeliverySettingsParams {
  return true;
}

export function AppSetEmailDeliverySettingsParamsFromJSON(
  json: any,
): AppSetEmailDeliverySettingsParams {
  return AppSetEmailDeliverySettingsParamsFromJSONTyped(json, false);
}

export function AppSetEmailDeliverySettingsParamsFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): AppSetEmailDeliverySettingsParams {
  if (json == null) {
    return json;
  }
  return {
    validate: json["validate"] == null ? undefined : json["validate"],
  };
}

export function AppSetEmailDeliverySettingsParamsToJSON(
  value?: AppSetEmailDeliverySettingsParams | null,
): any {
  if (value == null) {
    return value;
  }
  return {
    validate: value["validate"],
  };
}
