/* tslint:disable */
/* eslint-disable */
/**
 * Finbot application service
 * API documentation for appwsrv
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { SystemReport } from "./SystemReport";
import {
  SystemReportFromJSON,
  SystemReportFromJSONTyped,
  SystemReportToJSON,
} from "./SystemReport";

/**
 *
 * @export
 * @interface AppSystemReportResponse
 */
export interface AppSystemReportResponse {
  /**
   *
   * @type {SystemReport}
   * @memberof AppSystemReportResponse
   */
  systemReport: SystemReport;
}

/**
 * Check if a given object implements the AppSystemReportResponse interface.
 */
export function instanceOfAppSystemReportResponse(
  value: object,
): value is AppSystemReportResponse {
  if (!("systemReport" in value) || value["systemReport"] === undefined)
    return false;
  return true;
}

export function AppSystemReportResponseFromJSON(
  json: any,
): AppSystemReportResponse {
  return AppSystemReportResponseFromJSONTyped(json, false);
}

export function AppSystemReportResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): AppSystemReportResponse {
  if (json == null) {
    return json;
  }
  return {
    systemReport: SystemReportFromJSON(json["system_report"]),
  };
}

export function AppSystemReportResponseToJSON(
  value?: AppSystemReportResponse | null,
): any {
  if (value == null) {
    return value;
  }
  return {
    system_report: SystemReportToJSON(value["systemReport"]),
  };
}
