/* tslint:disable */
/* eslint-disable */
/**
 * Finbot application service
 * API documentation for appwsrv
 *
 * The version of the OpenAPI document: v0.0.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import type { SystemReport } from "./SystemReport";
import {
  SystemReportFromJSON,
  SystemReportFromJSONTyped,
  SystemReportToJSON,
} from "./SystemReport";

/**
 *
 * @export
 * @interface AppSystemReportResponse
 */
export interface AppSystemReportResponse {
  /**
   *
   * @type {SystemReport}
   * @memberof AppSystemReportResponse
   */
  systemReport: SystemReport;
}

/**
 * Check if a given object implements the AppSystemReportResponse interface.
 */
export function instanceOfAppSystemReportResponse(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && "systemReport" in value;

  return isInstance;
}

export function AppSystemReportResponseFromJSON(
  json: any,
): AppSystemReportResponse {
  return AppSystemReportResponseFromJSONTyped(json, false);
}

export function AppSystemReportResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): AppSystemReportResponse {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    systemReport: SystemReportFromJSON(json["system_report"]),
  };
}

export function AppSystemReportResponseToJSON(
  value?: AppSystemReportResponse | null,
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    system_report: SystemReportToJSON(value.systemReport),
  };
}
