/* tslint:disable */
/* eslint-disable */
/**
 * Finbot application service
 * API documentation for appwsrv
 *
 * The version of the OpenAPI document: v0.8.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface AppSetEmailDeliverySettingsParams
 */
export interface AppSetEmailDeliverySettingsParams {
  /**
   *
   * @type {boolean}
   * @memberof AppSetEmailDeliverySettingsParams
   */
  validate?: boolean;
}

/**
 * Check if a given object implements the AppSetEmailDeliverySettingsParams interface.
 */
export function instanceOfAppSetEmailDeliverySettingsParams(
  value: object,
): boolean {
  let isInstance = true;

  return isInstance;
}

export function AppSetEmailDeliverySettingsParamsFromJSON(
  json: any,
): AppSetEmailDeliverySettingsParams {
  return AppSetEmailDeliverySettingsParamsFromJSONTyped(json, false);
}

export function AppSetEmailDeliverySettingsParamsFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): AppSetEmailDeliverySettingsParams {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    validate: !exists(json, "validate") ? undefined : json["validate"],
  };
}

export function AppSetEmailDeliverySettingsParamsToJSON(
  value?: AppSetEmailDeliverySettingsParams | null,
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    validate: value.validate,
  };
}
