/* tslint:disable */
/* eslint-disable */
/**
 * Finbot application service
 * API documentation for appwsrv
 *
 * The version of the OpenAPI document: v0.8.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface AppUpdateUserAccountPasswordRequest
 */
export interface AppUpdateUserAccountPasswordRequest {
  /**
   *
   * @type {string}
   * @memberof AppUpdateUserAccountPasswordRequest
   */
  oldPassword: string;
  /**
   *
   * @type {string}
   * @memberof AppUpdateUserAccountPasswordRequest
   */
  newPassword: string;
}

/**
 * Check if a given object implements the AppUpdateUserAccountPasswordRequest interface.
 */
export function instanceOfAppUpdateUserAccountPasswordRequest(
  value: object,
): boolean {
  let isInstance = true;
  isInstance = isInstance && "oldPassword" in value;
  isInstance = isInstance && "newPassword" in value;

  return isInstance;
}

export function AppUpdateUserAccountPasswordRequestFromJSON(
  json: any,
): AppUpdateUserAccountPasswordRequest {
  return AppUpdateUserAccountPasswordRequestFromJSONTyped(json, false);
}

export function AppUpdateUserAccountPasswordRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): AppUpdateUserAccountPasswordRequest {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    oldPassword: json["old_password"],
    newPassword: json["new_password"],
  };
}

export function AppUpdateUserAccountPasswordRequestToJSON(
  value?: AppUpdateUserAccountPasswordRequest | null,
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    old_password: value.oldPassword,
    new_password: value.newPassword,
  };
}
