/* tslint:disable */
/* eslint-disable */
/**
 * Finbot application service
 * API documentation for appwsrv
 *
 * The version of the OpenAPI document: v0.8.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface AppUpdateLinkedAccountMetadataRequest
 */
export interface AppUpdateLinkedAccountMetadataRequest {
  /**
   *
   * @type {string}
   * @memberof AppUpdateLinkedAccountMetadataRequest
   */
  accountName?: string;
  /**
   *
   * @type {string}
   * @memberof AppUpdateLinkedAccountMetadataRequest
   */
  accountColour?: string;
  /**
   *
   * @type {boolean}
   * @memberof AppUpdateLinkedAccountMetadataRequest
   */
  frozen?: boolean;
}

/**
 * Check if a given object implements the AppUpdateLinkedAccountMetadataRequest interface.
 */
export function instanceOfAppUpdateLinkedAccountMetadataRequest(
  value: object,
): boolean {
  let isInstance = true;

  return isInstance;
}

export function AppUpdateLinkedAccountMetadataRequestFromJSON(
  json: any,
): AppUpdateLinkedAccountMetadataRequest {
  return AppUpdateLinkedAccountMetadataRequestFromJSONTyped(json, false);
}

export function AppUpdateLinkedAccountMetadataRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): AppUpdateLinkedAccountMetadataRequest {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    accountName: !exists(json, "account_name")
      ? undefined
      : json["account_name"],
    accountColour: !exists(json, "account_colour")
      ? undefined
      : json["account_colour"],
    frozen: !exists(json, "frozen") ? undefined : json["frozen"],
  };
}

export function AppUpdateLinkedAccountMetadataRequestToJSON(
  value?: AppUpdateLinkedAccountMetadataRequest | null,
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    account_name: value.accountName,
    account_colour: value.accountColour,
    frozen: value.frozen,
  };
}
