/* tslint:disable */
/* eslint-disable */
/**
 * Finbot application service
 * API documentation for appwsrv
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AssetType } from './AssetType';
import {
    AssetTypeFromJSON,
    AssetTypeFromJSONTyped,
    AssetTypeToJSON,
    AssetTypeToJSONTyped,
} from './AssetType';

/**
 * 
 * @export
 * @interface AssetTypeFormattingRule
 */
export interface AssetTypeFormattingRule {
    /**
     * 
     * @type {AssetType}
     * @memberof AssetTypeFormattingRule
     */
    assetType: AssetType;
    /**
     * 
     * @type {string}
     * @memberof AssetTypeFormattingRule
     */
    prettyName: string;
    /**
     * 
     * @type {string}
     * @memberof AssetTypeFormattingRule
     */
    abbreviatedName: string;
}



/**
 * Check if a given object implements the AssetTypeFormattingRule interface.
 */
export function instanceOfAssetTypeFormattingRule(value: object): value is AssetTypeFormattingRule {
    if (!('assetType' in value) || value['assetType'] === undefined) return false;
    if (!('prettyName' in value) || value['prettyName'] === undefined) return false;
    if (!('abbreviatedName' in value) || value['abbreviatedName'] === undefined) return false;
    return true;
}

export function AssetTypeFormattingRuleFromJSON(json: any): AssetTypeFormattingRule {
    return AssetTypeFormattingRuleFromJSONTyped(json, false);
}

export function AssetTypeFormattingRuleFromJSONTyped(json: any, ignoreDiscriminator: boolean): AssetTypeFormattingRule {
    if (json == null) {
        return json;
    }
    return {
        
        'assetType': AssetTypeFromJSON(json['asset_type']),
        'prettyName': json['pretty_name'],
        'abbreviatedName': json['abbreviated_name'],
    };
}

export function AssetTypeFormattingRuleToJSON(json: any): AssetTypeFormattingRule {
    return AssetTypeFormattingRuleToJSONTyped(json, false);
}

export function AssetTypeFormattingRuleToJSONTyped(value?: AssetTypeFormattingRule | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'asset_type': AssetTypeToJSON(value['assetType']),
        'pretty_name': value['prettyName'],
        'abbreviated_name': value['abbreviatedName'],
    };
}

