/* tslint:disable */
/* eslint-disable */
/**
 * Finbot application service
 * API documentation for appwsrv
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const AssetType = {
    Cash: 'cash',
    Bond: 'bond',
    Stock: 'stock',
    Option: 'option',
    Future: 'future',
    Etf: 'ETF',
    Etn: 'ETN',
    Etc: 'ETC',
    GenericFund: 'generic_fund',
    Loan: 'loan',
    PreciousMetal: 'precious_metal',
    CryptoCurrency: 'crypto_currency',
    UtilityToken: 'utility_token',
    SecurityToken: 'security_token',
    StableCoin: 'stable_coin',
    CommercialProperty: 'commercial_property',
    ResidentialProperty: 'residential_property',
    LandProperty: 'land_property'
} as const;
export type AssetType = typeof AssetType[keyof typeof AssetType];


export function instanceOfAssetType(value: any): boolean {
    for (const key in AssetType) {
        if (Object.prototype.hasOwnProperty.call(AssetType, key)) {
            if (AssetType[key as keyof typeof AssetType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function AssetTypeFromJSON(json: any): AssetType {
    return AssetTypeFromJSONTyped(json, false);
}

export function AssetTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): AssetType {
    return json as AssetType;
}

export function AssetTypeToJSON(value?: AssetType | null): any {
    return value as any;
}

export function AssetTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): AssetType {
    return value as AssetType;
}

