/* tslint:disable */
/* eslint-disable */
/**
 * Finbot application service
 * API documentation for appwsrv
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CashFlowTimeSeriesEntry
 */
export interface CashFlowTimeSeriesEntry {
    /**
     * 
     * @type {string}
     * @memberof CashFlowTimeSeriesEntry
     */
    period: string;
    /**
     * 
     * @type {number}
     * @memberof CashFlowTimeSeriesEntry
     */
    income: number;
    /**
     * 
     * @type {number}
     * @memberof CashFlowTimeSeriesEntry
     */
    expense: number;
    /**
     * 
     * @type {number}
     * @memberof CashFlowTimeSeriesEntry
     */
    net: number;
}

/**
 * Check if a given object implements the CashFlowTimeSeriesEntry interface.
 */
export function instanceOfCashFlowTimeSeriesEntry(value: object): value is CashFlowTimeSeriesEntry {
    if (!('period' in value) || value['period'] === undefined) return false;
    if (!('income' in value) || value['income'] === undefined) return false;
    if (!('expense' in value) || value['expense'] === undefined) return false;
    if (!('net' in value) || value['net'] === undefined) return false;
    return true;
}

export function CashFlowTimeSeriesEntryFromJSON(json: any): CashFlowTimeSeriesEntry {
    return CashFlowTimeSeriesEntryFromJSONTyped(json, false);
}

export function CashFlowTimeSeriesEntryFromJSONTyped(json: any, ignoreDiscriminator: boolean): CashFlowTimeSeriesEntry {
    if (json == null) {
        return json;
    }
    return {
        
        'period': json['period'],
        'income': json['income'],
        'expense': json['expense'],
        'net': json['net'],
    };
}

export function CashFlowTimeSeriesEntryToJSON(json: any): CashFlowTimeSeriesEntry {
    return CashFlowTimeSeriesEntryToJSONTyped(json, false);
}

export function CashFlowTimeSeriesEntryToJSONTyped(value?: CashFlowTimeSeriesEntry | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'period': value['period'],
        'income': value['income'],
        'expense': value['expense'],
        'net': value['net'],
    };
}

