/* tslint:disable */
/* eslint-disable */
/**
 * Finbot application service
 * API documentation for appwsrv
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ConversionPreviewHolding
 */
export interface ConversionPreviewHolding {
    /**
     * 
     * @type {string}
     * @memberof ConversionPreviewHolding
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof ConversionPreviewHolding
     */
    value: number;
    /**
     * 
     * @type {string}
     * @memberof ConversionPreviewHolding
     */
    currency: string;
    /**
     * 
     * @type {boolean}
     * @memberof ConversionPreviewHolding
     */
    isLiability: boolean;
}

/**
 * Check if a given object implements the ConversionPreviewHolding interface.
 */
export function instanceOfConversionPreviewHolding(value: object): value is ConversionPreviewHolding {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('value' in value) || value['value'] === undefined) return false;
    if (!('currency' in value) || value['currency'] === undefined) return false;
    if (!('isLiability' in value) || value['isLiability'] === undefined) return false;
    return true;
}

export function ConversionPreviewHoldingFromJSON(json: any): ConversionPreviewHolding {
    return ConversionPreviewHoldingFromJSONTyped(json, false);
}

export function ConversionPreviewHoldingFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConversionPreviewHolding {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'value': json['value'],
        'currency': json['currency'],
        'isLiability': json['is_liability'],
    };
}

export function ConversionPreviewHoldingToJSON(json: any): ConversionPreviewHolding {
    return ConversionPreviewHoldingToJSONTyped(json, false);
}

export function ConversionPreviewHoldingToJSONTyped(value?: ConversionPreviewHolding | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'value': value['value'],
        'currency': value['currency'],
        'is_liability': value['isLiability'],
    };
}

