/* tslint:disable */
/* eslint-disable */
/**
 * Finbot application service
 * API documentation for appwsrv
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ConvertLinkedAccountRequest
 */
export interface ConvertLinkedAccountRequest {
    /**
     * 
     * @type {number}
     * @memberof ConvertLinkedAccountRequest
     */
    linkedAccountId: number;
}

/**
 * Check if a given object implements the ConvertLinkedAccountRequest interface.
 */
export function instanceOfConvertLinkedAccountRequest(value: object): value is ConvertLinkedAccountRequest {
    if (!('linkedAccountId' in value) || value['linkedAccountId'] === undefined) return false;
    return true;
}

export function ConvertLinkedAccountRequestFromJSON(json: any): ConvertLinkedAccountRequest {
    return ConvertLinkedAccountRequestFromJSONTyped(json, false);
}

export function ConvertLinkedAccountRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConvertLinkedAccountRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'linkedAccountId': json['linked_account_id'],
    };
}

export function ConvertLinkedAccountRequestToJSON(json: any): ConvertLinkedAccountRequest {
    return ConvertLinkedAccountRequestToJSONTyped(json, false);
}

export function ConvertLinkedAccountRequestToJSONTyped(value?: ConvertLinkedAccountRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'linked_account_id': value['linkedAccountId'],
    };
}

