/* tslint:disable */
/* eslint-disable */
/**
 * Finbot application service
 * API documentation for appwsrv
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Portfolio } from './Portfolio';
import {
    PortfolioFromJSON,
    PortfolioFromJSONTyped,
    PortfolioToJSON,
    PortfolioToJSONTyped,
} from './Portfolio';

/**
 * 
 * @export
 * @interface ConvertLinkedAccountResponse
 */
export interface ConvertLinkedAccountResponse {
    /**
     * 
     * @type {Portfolio}
     * @memberof ConvertLinkedAccountResponse
     */
    portfolio: Portfolio;
}

/**
 * Check if a given object implements the ConvertLinkedAccountResponse interface.
 */
export function instanceOfConvertLinkedAccountResponse(value: object): value is ConvertLinkedAccountResponse {
    if (!('portfolio' in value) || value['portfolio'] === undefined) return false;
    return true;
}

export function ConvertLinkedAccountResponseFromJSON(json: any): ConvertLinkedAccountResponse {
    return ConvertLinkedAccountResponseFromJSONTyped(json, false);
}

export function ConvertLinkedAccountResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConvertLinkedAccountResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'portfolio': PortfolioFromJSON(json['portfolio']),
    };
}

export function ConvertLinkedAccountResponseToJSON(json: any): ConvertLinkedAccountResponse {
    return ConvertLinkedAccountResponseToJSONTyped(json, false);
}

export function ConvertLinkedAccountResponseToJSONTyped(value?: ConvertLinkedAccountResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'portfolio': PortfolioToJSON(value['portfolio']),
    };
}

