/* tslint:disable */
/* eslint-disable */
/**
 * Finbot application service
 * API documentation for appwsrv
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Portfolio } from './Portfolio';
import {
    PortfolioFromJSON,
    PortfolioFromJSONTyped,
    PortfolioToJSON,
    PortfolioToJSONTyped,
} from './Portfolio';

/**
 * 
 * @export
 * @interface CreatePortfolioSectionResponse
 */
export interface CreatePortfolioSectionResponse {
    /**
     * 
     * @type {Portfolio}
     * @memberof CreatePortfolioSectionResponse
     */
    portfolio: Portfolio;
}

/**
 * Check if a given object implements the CreatePortfolioSectionResponse interface.
 */
export function instanceOfCreatePortfolioSectionResponse(value: object): value is CreatePortfolioSectionResponse {
    if (!('portfolio' in value) || value['portfolio'] === undefined) return false;
    return true;
}

export function CreatePortfolioSectionResponseFromJSON(json: any): CreatePortfolioSectionResponse {
    return CreatePortfolioSectionResponseFromJSONTyped(json, false);
}

export function CreatePortfolioSectionResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreatePortfolioSectionResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'portfolio': PortfolioFromJSON(json['portfolio']),
    };
}

export function CreatePortfolioSectionResponseToJSON(json: any): CreatePortfolioSectionResponse {
    return CreatePortfolioSectionResponseToJSONTyped(json, false);
}

export function CreatePortfolioSectionResponseToJSONTyped(value?: CreatePortfolioSectionResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'portfolio': PortfolioToJSON(value['portfolio']),
    };
}

