/* tslint:disable */
/* eslint-disable */
/**
 * Finbot application service
 * API documentation for appwsrv
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { UserAccountCreationSettings } from "./UserAccountCreationSettings";
import {
  UserAccountCreationSettingsFromJSON,
  UserAccountCreationSettingsFromJSONTyped,
  UserAccountCreationSettingsToJSON,
  UserAccountCreationSettingsToJSONTyped,
} from "./UserAccountCreationSettings";

/**
 *
 * @export
 * @interface CreateUserAccountRequest
 */
export interface CreateUserAccountRequest {
  /**
   *
   * @type {string}
   * @memberof CreateUserAccountRequest
   */
  email: string;
  /**
   *
   * @type {string}
   * @memberof CreateUserAccountRequest
   */
  password: string;
  /**
   *
   * @type {string}
   * @memberof CreateUserAccountRequest
   */
  fullName: string;
  /**
   *
   * @type {UserAccountCreationSettings}
   * @memberof CreateUserAccountRequest
   */
  settings: UserAccountCreationSettings;
}

/**
 * Check if a given object implements the CreateUserAccountRequest interface.
 */
export function instanceOfCreateUserAccountRequest(
  value: object,
): value is CreateUserAccountRequest {
  if (!("email" in value) || value["email"] === undefined) return false;
  if (!("password" in value) || value["password"] === undefined) return false;
  if (!("fullName" in value) || value["fullName"] === undefined) return false;
  if (!("settings" in value) || value["settings"] === undefined) return false;
  return true;
}

export function CreateUserAccountRequestFromJSON(
  json: any,
): CreateUserAccountRequest {
  return CreateUserAccountRequestFromJSONTyped(json, false);
}

export function CreateUserAccountRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CreateUserAccountRequest {
  if (json == null) {
    return json;
  }
  return {
    email: json["email"],
    password: json["password"],
    fullName: json["full_name"],
    settings: UserAccountCreationSettingsFromJSON(json["settings"]),
  };
}

export function CreateUserAccountRequestToJSON(
  json: any,
): CreateUserAccountRequest {
  return CreateUserAccountRequestToJSONTyped(json, false);
}

export function CreateUserAccountRequestToJSONTyped(
  value?: CreateUserAccountRequest | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    email: value["email"],
    password: value["password"],
    full_name: value["fullName"],
    settings: UserAccountCreationSettingsToJSON(value["settings"]),
  };
}
