/* tslint:disable */
/* eslint-disable */
/**
 * Finbot application service
 * API documentation for appwsrv
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Portfolio } from './Portfolio';
import {
    PortfolioFromJSON,
    PortfolioFromJSONTyped,
    PortfolioToJSON,
    PortfolioToJSONTyped,
} from './Portfolio';

/**
 * 
 * @export
 * @interface CreatePortfolioResponse
 */
export interface CreatePortfolioResponse {
    /**
     * 
     * @type {Portfolio}
     * @memberof CreatePortfolioResponse
     */
    portfolio: Portfolio;
}

/**
 * Check if a given object implements the CreatePortfolioResponse interface.
 */
export function instanceOfCreatePortfolioResponse(value: object): value is CreatePortfolioResponse {
    if (!('portfolio' in value) || value['portfolio'] === undefined) return false;
    return true;
}

export function CreatePortfolioResponseFromJSON(json: any): CreatePortfolioResponse {
    return CreatePortfolioResponseFromJSONTyped(json, false);
}

export function CreatePortfolioResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreatePortfolioResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'portfolio': PortfolioFromJSON(json['portfolio']),
    };
}

export function CreatePortfolioResponseToJSON(json: any): CreatePortfolioResponse {
    return CreatePortfolioResponseToJSONTyped(json, false);
}

export function CreatePortfolioResponseToJSONTyped(value?: CreatePortfolioResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'portfolio': PortfolioToJSON(value['portfolio']),
    };
}

