/* tslint:disable */
/* eslint-disable */
/**
 * Finbot application service
 * API documentation for appwsrv
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Portfolio } from './Portfolio';
import {
    PortfolioFromJSON,
    PortfolioFromJSONTyped,
    PortfolioToJSON,
    PortfolioToJSONTyped,
} from './Portfolio';

/**
 * 
 * @export
 * @interface CreatePortfolioEntryResponse
 */
export interface CreatePortfolioEntryResponse {
    /**
     * 
     * @type {Portfolio}
     * @memberof CreatePortfolioEntryResponse
     */
    portfolio: Portfolio;
}

/**
 * Check if a given object implements the CreatePortfolioEntryResponse interface.
 */
export function instanceOfCreatePortfolioEntryResponse(value: object): value is CreatePortfolioEntryResponse {
    if (!('portfolio' in value) || value['portfolio'] === undefined) return false;
    return true;
}

export function CreatePortfolioEntryResponseFromJSON(json: any): CreatePortfolioEntryResponse {
    return CreatePortfolioEntryResponseFromJSONTyped(json, false);
}

export function CreatePortfolioEntryResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreatePortfolioEntryResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'portfolio': PortfolioFromJSON(json['portfolio']),
    };
}

export function CreatePortfolioEntryResponseToJSON(json: any): CreatePortfolioEntryResponse {
    return CreatePortfolioEntryResponseToJSONTyped(json, false);
}

export function CreatePortfolioEntryResponseToJSONTyped(value?: CreatePortfolioEntryResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'portfolio': PortfolioToJSON(value['portfolio']),
    };
}

