/* tslint:disable */
/* eslint-disable */
/**
 * Finbot application service
 * API documentation for appwsrv
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Portfolio } from './Portfolio';
import {
    PortfolioFromJSON,
    PortfolioFromJSONTyped,
    PortfolioToJSON,
    PortfolioToJSONTyped,
} from './Portfolio';

/**
 * 
 * @export
 * @interface DeletePortfolioEntryResponse
 */
export interface DeletePortfolioEntryResponse {
    /**
     * 
     * @type {Portfolio}
     * @memberof DeletePortfolioEntryResponse
     */
    portfolio: Portfolio;
}

/**
 * Check if a given object implements the DeletePortfolioEntryResponse interface.
 */
export function instanceOfDeletePortfolioEntryResponse(value: object): value is DeletePortfolioEntryResponse {
    if (!('portfolio' in value) || value['portfolio'] === undefined) return false;
    return true;
}

export function DeletePortfolioEntryResponseFromJSON(json: any): DeletePortfolioEntryResponse {
    return DeletePortfolioEntryResponseFromJSONTyped(json, false);
}

export function DeletePortfolioEntryResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeletePortfolioEntryResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'portfolio': PortfolioFromJSON(json['portfolio']),
    };
}

export function DeletePortfolioEntryResponseToJSON(json: any): DeletePortfolioEntryResponse {
    return DeletePortfolioEntryResponseToJSONTyped(json, false);
}

export function DeletePortfolioEntryResponseToJSONTyped(value?: DeletePortfolioEntryResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'portfolio': PortfolioToJSON(value['portfolio']),
    };
}

