/* tslint:disable */
/* eslint-disable */
/**
 * Finbot application service
 * API documentation for appwsrv
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DismissNotificationResponse
 */
export interface DismissNotificationResponse {
    /**
     * 
     * @type {number}
     * @memberof DismissNotificationResponse
     */
    unreadCount: number;
}

/**
 * Check if a given object implements the DismissNotificationResponse interface.
 */
export function instanceOfDismissNotificationResponse(value: object): value is DismissNotificationResponse {
    if (!('unreadCount' in value) || value['unreadCount'] === undefined) return false;
    return true;
}

export function DismissNotificationResponseFromJSON(json: any): DismissNotificationResponse {
    return DismissNotificationResponseFromJSONTyped(json, false);
}

export function DismissNotificationResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DismissNotificationResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'unreadCount': json['unread_count'],
    };
}

export function DismissNotificationResponseToJSON(json: any): DismissNotificationResponse {
    return DismissNotificationResponseToJSONTyped(json, false);
}

export function DismissNotificationResponseToJSONTyped(value?: DismissNotificationResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'unread_count': value['unreadCount'],
    };
}

