/* tslint:disable */
/* eslint-disable */
/**
 * Finbot application service
 * API documentation for appwsrv
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { Metrics } from "./Metrics";
import {
  MetricsFromJSON,
  MetricsFromJSONTyped,
  MetricsToJSON,
  MetricsToJSONTyped,
} from "./Metrics";
import type { ReportEntry } from "./ReportEntry";
import {
  ReportEntryFromJSON,
  ReportEntryFromJSONTyped,
  ReportEntryToJSON,
  ReportEntryToJSONTyped,
} from "./ReportEntry";

/**
 *
 * @export
 * @interface EarningsReport
 */
export interface EarningsReport {
  /**
   *
   * @type {string}
   * @memberof EarningsReport
   */
  currency: string;
  /**
   *
   * @type {Array<ReportEntry>}
   * @memberof EarningsReport
   */
  entries: Array<ReportEntry>;
  /**
   *
   * @type {Metrics}
   * @memberof EarningsReport
   */
  rollup: Metrics;
}

/**
 * Check if a given object implements the EarningsReport interface.
 */
export function instanceOfEarningsReport(
  value: object,
): value is EarningsReport {
  if (!("currency" in value) || value["currency"] === undefined) return false;
  if (!("entries" in value) || value["entries"] === undefined) return false;
  if (!("rollup" in value) || value["rollup"] === undefined) return false;
  return true;
}

export function EarningsReportFromJSON(json: any): EarningsReport {
  return EarningsReportFromJSONTyped(json, false);
}

export function EarningsReportFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): EarningsReport {
  if (json == null) {
    return json;
  }
  return {
    currency: json["currency"],
    entries: (json["entries"] as Array<any>).map(ReportEntryFromJSON),
    rollup: MetricsFromJSON(json["rollup"]),
  };
}

export function EarningsReportToJSON(json: any): EarningsReport {
  return EarningsReportToJSONTyped(json, false);
}

export function EarningsReportToJSONTyped(
  value?: EarningsReport | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    currency: value["currency"],
    entries: (value["entries"] as Array<any>).map(ReportEntryToJSON),
    rollup: MetricsToJSON(value["rollup"]),
  };
}
