/* tslint:disable */
/* eslint-disable */
/**
 * Finbot application service
 * API documentation for appwsrv
 *
 * The version of the OpenAPI document: v0.0.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface ErrorMetadata
 */
export interface ErrorMetadata {
  /**
   *
   * @type {string}
   * @memberof ErrorMetadata
   */
  userMessage: string;
  /**
   *
   * @type {string}
   * @memberof ErrorMetadata
   */
  debugMessage?: string;
  /**
   *
   * @type {string}
   * @memberof ErrorMetadata
   */
  errorCode?: string;
  /**
   *
   * @type {string}
   * @memberof ErrorMetadata
   */
  exceptionType?: string;
  /**
   *
   * @type {string}
   * @memberof ErrorMetadata
   */
  trace?: string;
}

/**
 * Check if a given object implements the ErrorMetadata interface.
 */
export function instanceOfErrorMetadata(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && "userMessage" in value;

  return isInstance;
}

export function ErrorMetadataFromJSON(json: any): ErrorMetadata {
  return ErrorMetadataFromJSONTyped(json, false);
}

export function ErrorMetadataFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ErrorMetadata {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    userMessage: json["user_message"],
    debugMessage: !exists(json, "debug_message")
      ? undefined
      : json["debug_message"],
    errorCode: !exists(json, "error_code") ? undefined : json["error_code"],
    exceptionType: !exists(json, "exception_type")
      ? undefined
      : json["exception_type"],
    trace: !exists(json, "trace") ? undefined : json["trace"],
  };
}

export function ErrorMetadataToJSON(value?: ErrorMetadata | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    user_message: value.userMessage,
    debug_message: value.debugMessage,
    error_code: value.errorCode,
    exception_type: value.exceptionType,
    trace: value.trace,
  };
}
