/* tslint:disable */
/* eslint-disable */
/**
 * Finbot application service
 * API documentation for appwsrv
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface ErrorMetadata
 */
export interface ErrorMetadata {
  /**
   *
   * @type {string}
   * @memberof ErrorMetadata
   */
  userMessage: string;
  /**
   *
   * @type {string}
   * @memberof ErrorMetadata
   */
  debugMessage: string | null;
  /**
   *
   * @type {string}
   * @memberof ErrorMetadata
   */
  errorCode: string | null;
  /**
   *
   * @type {string}
   * @memberof ErrorMetadata
   */
  exceptionType: string | null;
  /**
   *
   * @type {string}
   * @memberof ErrorMetadata
   */
  trace: string | null;
}

/**
 * Check if a given object implements the ErrorMetadata interface.
 */
export function instanceOfErrorMetadata(value: object): value is ErrorMetadata {
  if (!("userMessage" in value) || value["userMessage"] === undefined)
    return false;
  if (!("debugMessage" in value) || value["debugMessage"] === undefined)
    return false;
  if (!("errorCode" in value) || value["errorCode"] === undefined) return false;
  if (!("exceptionType" in value) || value["exceptionType"] === undefined)
    return false;
  if (!("trace" in value) || value["trace"] === undefined) return false;
  return true;
}

export function ErrorMetadataFromJSON(json: any): ErrorMetadata {
  return ErrorMetadataFromJSONTyped(json, false);
}

export function ErrorMetadataFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ErrorMetadata {
  if (json == null) {
    return json;
  }
  return {
    userMessage: json["user_message"],
    debugMessage: json["debug_message"],
    errorCode: json["error_code"],
    exceptionType: json["exception_type"],
    trace: json["trace"],
  };
}

export function ErrorMetadataToJSON(json: any): ErrorMetadata {
  return ErrorMetadataToJSONTyped(json, false);
}

export function ErrorMetadataToJSONTyped(
  value?: ErrorMetadata | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    user_message: value["userMessage"],
    debug_message: value["debugMessage"],
    error_code: value["errorCode"],
    exception_type: value["exceptionType"],
    trace: value["trace"],
  };
}
