/* tslint:disable */
/* eslint-disable */
/**
 * Finbot application service
 * API documentation for appwsrv
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AssetClassFormattingRule } from './AssetClassFormattingRule';
import {
    AssetClassFormattingRuleFromJSON,
    AssetClassFormattingRuleFromJSONTyped,
    AssetClassFormattingRuleToJSON,
    AssetClassFormattingRuleToJSONTyped,
} from './AssetClassFormattingRule';
import type { AssetTypeFormattingRule } from './AssetTypeFormattingRule';
import {
    AssetTypeFormattingRuleFromJSON,
    AssetTypeFormattingRuleFromJSONTyped,
    AssetTypeFormattingRuleToJSON,
    AssetTypeFormattingRuleToJSONTyped,
} from './AssetTypeFormattingRule';

/**
 * 
 * @export
 * @interface GetAssetsFormattingRulesResponse
 */
export interface GetAssetsFormattingRulesResponse {
    /**
     * 
     * @type {Array<AssetClassFormattingRule>}
     * @memberof GetAssetsFormattingRulesResponse
     */
    assetClasses: Array<AssetClassFormattingRule>;
    /**
     * 
     * @type {Array<AssetTypeFormattingRule>}
     * @memberof GetAssetsFormattingRulesResponse
     */
    assetTypes: Array<AssetTypeFormattingRule>;
}

/**
 * Check if a given object implements the GetAssetsFormattingRulesResponse interface.
 */
export function instanceOfGetAssetsFormattingRulesResponse(value: object): value is GetAssetsFormattingRulesResponse {
    if (!('assetClasses' in value) || value['assetClasses'] === undefined) return false;
    if (!('assetTypes' in value) || value['assetTypes'] === undefined) return false;
    return true;
}

export function GetAssetsFormattingRulesResponseFromJSON(json: any): GetAssetsFormattingRulesResponse {
    return GetAssetsFormattingRulesResponseFromJSONTyped(json, false);
}

export function GetAssetsFormattingRulesResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetAssetsFormattingRulesResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'assetClasses': ((json['asset_classes'] as Array<any>).map(AssetClassFormattingRuleFromJSON)),
        'assetTypes': ((json['asset_types'] as Array<any>).map(AssetTypeFormattingRuleFromJSON)),
    };
}

export function GetAssetsFormattingRulesResponseToJSON(json: any): GetAssetsFormattingRulesResponse {
    return GetAssetsFormattingRulesResponseToJSONTyped(json, false);
}

export function GetAssetsFormattingRulesResponseToJSONTyped(value?: GetAssetsFormattingRulesResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'asset_classes': ((value['assetClasses'] as Array<any>).map(AssetClassFormattingRuleToJSON)),
        'asset_types': ((value['assetTypes'] as Array<any>).map(AssetTypeFormattingRuleToJSON)),
    };
}

