/* tslint:disable */
/* eslint-disable */
/**
 * Finbot application service
 * API documentation for appwsrv
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CashFlowSummary } from './CashFlowSummary';
import {
    CashFlowSummaryFromJSON,
    CashFlowSummaryFromJSONTyped,
    CashFlowSummaryToJSON,
    CashFlowSummaryToJSONTyped,
} from './CashFlowSummary';

/**
 * 
 * @export
 * @interface GetCashFlowSummaryResponse
 */
export interface GetCashFlowSummaryResponse {
    /**
     * 
     * @type {CashFlowSummary}
     * @memberof GetCashFlowSummaryResponse
     */
    report: CashFlowSummary;
}

/**
 * Check if a given object implements the GetCashFlowSummaryResponse interface.
 */
export function instanceOfGetCashFlowSummaryResponse(value: object): value is GetCashFlowSummaryResponse {
    if (!('report' in value) || value['report'] === undefined) return false;
    return true;
}

export function GetCashFlowSummaryResponseFromJSON(json: any): GetCashFlowSummaryResponse {
    return GetCashFlowSummaryResponseFromJSONTyped(json, false);
}

export function GetCashFlowSummaryResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetCashFlowSummaryResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'report': CashFlowSummaryFromJSON(json['report']),
    };
}

export function GetCashFlowSummaryResponseToJSON(json: any): GetCashFlowSummaryResponse {
    return GetCashFlowSummaryResponseToJSONTyped(json, false);
}

export function GetCashFlowSummaryResponseToJSONTyped(value?: GetCashFlowSummaryResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'report': CashFlowSummaryToJSON(value['report']),
    };
}

