/* tslint:disable */
/* eslint-disable */
/**
 * Finbot application service
 * API documentation for appwsrv
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { HistoricalValuation } from "./HistoricalValuation";
import {
  HistoricalValuationFromJSON,
  HistoricalValuationFromJSONTyped,
  HistoricalValuationToJSON,
  HistoricalValuationToJSONTyped,
} from "./HistoricalValuation";

/**
 *
 * @export
 * @interface GetLinkedAccountsHistoricalValuation
 */
export interface GetLinkedAccountsHistoricalValuation {
  /**
   *
   * @type {HistoricalValuation}
   * @memberof GetLinkedAccountsHistoricalValuation
   */
  historicalValuation: HistoricalValuation;
}

/**
 * Check if a given object implements the GetLinkedAccountsHistoricalValuation interface.
 */
export function instanceOfGetLinkedAccountsHistoricalValuation(
  value: object,
): value is GetLinkedAccountsHistoricalValuation {
  if (
    !("historicalValuation" in value) ||
    value["historicalValuation"] === undefined
  )
    return false;
  return true;
}

export function GetLinkedAccountsHistoricalValuationFromJSON(
  json: any,
): GetLinkedAccountsHistoricalValuation {
  return GetLinkedAccountsHistoricalValuationFromJSONTyped(json, false);
}

export function GetLinkedAccountsHistoricalValuationFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): GetLinkedAccountsHistoricalValuation {
  if (json == null) {
    return json;
  }
  return {
    historicalValuation: HistoricalValuationFromJSON(
      json["historical_valuation"],
    ),
  };
}

export function GetLinkedAccountsHistoricalValuationToJSON(
  json: any,
): GetLinkedAccountsHistoricalValuation {
  return GetLinkedAccountsHistoricalValuationToJSONTyped(json, false);
}

export function GetLinkedAccountsHistoricalValuationToJSONTyped(
  value?: GetLinkedAccountsHistoricalValuation | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    historical_valuation: HistoricalValuationToJSON(
      value["historicalValuation"],
    ),
  };
}
