/* tslint:disable */
/* eslint-disable */
/**
 * Finbot application service
 * API documentation for appwsrv
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { LinkedAccountsValuation } from "./LinkedAccountsValuation";
import {
  LinkedAccountsValuationFromJSON,
  LinkedAccountsValuationFromJSONTyped,
  LinkedAccountsValuationToJSON,
  LinkedAccountsValuationToJSONTyped,
} from "./LinkedAccountsValuation";

/**
 *
 * @export
 * @interface GetLinkedAccountsValuationResponse
 */
export interface GetLinkedAccountsValuationResponse {
  [key: string]: any | any;
  /**
   *
   * @type {LinkedAccountsValuation}
   * @memberof GetLinkedAccountsValuationResponse
   */
  valuation: LinkedAccountsValuation;
}

/**
 * Check if a given object implements the GetLinkedAccountsValuationResponse interface.
 */
export function instanceOfGetLinkedAccountsValuationResponse(
  value: object,
): value is GetLinkedAccountsValuationResponse {
  if (!("valuation" in value) || value["valuation"] === undefined) return false;
  return true;
}

export function GetLinkedAccountsValuationResponseFromJSON(
  json: any,
): GetLinkedAccountsValuationResponse {
  return GetLinkedAccountsValuationResponseFromJSONTyped(json, false);
}

export function GetLinkedAccountsValuationResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): GetLinkedAccountsValuationResponse {
  if (json == null) {
    return json;
  }
  return {
    ...json,
    valuation: LinkedAccountsValuationFromJSON(json["valuation"]),
  };
}

export function GetLinkedAccountsValuationResponseToJSON(
  json: any,
): GetLinkedAccountsValuationResponse {
  return GetLinkedAccountsValuationResponseToJSONTyped(json, false);
}

export function GetLinkedAccountsValuationResponseToJSONTyped(
  value?: GetLinkedAccountsValuationResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    ...value,
    valuation: LinkedAccountsValuationToJSON(value["valuation"]),
  };
}
