/* tslint:disable */
/* eslint-disable */
/**
 * Finbot application service
 * API documentation for appwsrv
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { Provider } from "./Provider";
import {
  ProviderFromJSON,
  ProviderFromJSONTyped,
  ProviderToJSON,
  ProviderToJSONTyped,
} from "./Provider";

/**
 *
 * @export
 * @interface GetProviderResponse
 */
export interface GetProviderResponse {
  /**
   *
   * @type {Provider}
   * @memberof GetProviderResponse
   */
  provider: Provider;
}

/**
 * Check if a given object implements the GetProviderResponse interface.
 */
export function instanceOfGetProviderResponse(
  value: object,
): value is GetProviderResponse {
  if (!("provider" in value) || value["provider"] === undefined) return false;
  return true;
}

export function GetProviderResponseFromJSON(json: any): GetProviderResponse {
  return GetProviderResponseFromJSONTyped(json, false);
}

export function GetProviderResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): GetProviderResponse {
  if (json == null) {
    return json;
  }
  return {
    provider: ProviderFromJSON(json["provider"]),
  };
}

export function GetProviderResponseToJSON(json: any): GetProviderResponse {
  return GetProviderResponseToJSONTyped(json, false);
}

export function GetProviderResponseToJSONTyped(
  value?: GetProviderResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    provider: ProviderToJSON(value["provider"]),
  };
}
