/* tslint:disable */
/* eslint-disable */
/**
 * Finbot application service
 * API documentation for appwsrv
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Portfolio } from './Portfolio';
import {
    PortfolioFromJSON,
    PortfolioFromJSONTyped,
    PortfolioToJSON,
    PortfolioToJSONTyped,
} from './Portfolio';

/**
 * 
 * @export
 * @interface GetPortfolioResponse
 */
export interface GetPortfolioResponse {
    /**
     * 
     * @type {Portfolio}
     * @memberof GetPortfolioResponse
     */
    portfolio: Portfolio;
}

/**
 * Check if a given object implements the GetPortfolioResponse interface.
 */
export function instanceOfGetPortfolioResponse(value: object): value is GetPortfolioResponse {
    if (!('portfolio' in value) || value['portfolio'] === undefined) return false;
    return true;
}

export function GetPortfolioResponseFromJSON(json: any): GetPortfolioResponse {
    return GetPortfolioResponseFromJSONTyped(json, false);
}

export function GetPortfolioResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetPortfolioResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'portfolio': PortfolioFromJSON(json['portfolio']),
    };
}

export function GetPortfolioResponseToJSON(json: any): GetPortfolioResponse {
    return GetPortfolioResponseToJSONTyped(json, false);
}

export function GetPortfolioResponseToJSONTyped(value?: GetPortfolioResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'portfolio': PortfolioToJSON(value['portfolio']),
    };
}

