/* tslint:disable */
/* eslint-disable */
/**
 * Finbot application service
 * API documentation for appwsrv
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SpendingCalendarReport } from './SpendingCalendarReport';
import {
    SpendingCalendarReportFromJSON,
    SpendingCalendarReportFromJSONTyped,
    SpendingCalendarReportToJSON,
    SpendingCalendarReportToJSONTyped,
} from './SpendingCalendarReport';

/**
 * 
 * @export
 * @interface GetSpendingCalendarResponse
 */
export interface GetSpendingCalendarResponse {
    /**
     * 
     * @type {SpendingCalendarReport}
     * @memberof GetSpendingCalendarResponse
     */
    report: SpendingCalendarReport;
}

/**
 * Check if a given object implements the GetSpendingCalendarResponse interface.
 */
export function instanceOfGetSpendingCalendarResponse(value: object): value is GetSpendingCalendarResponse {
    if (!('report' in value) || value['report'] === undefined) return false;
    return true;
}

export function GetSpendingCalendarResponseFromJSON(json: any): GetSpendingCalendarResponse {
    return GetSpendingCalendarResponseFromJSONTyped(json, false);
}

export function GetSpendingCalendarResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetSpendingCalendarResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'report': SpendingCalendarReportFromJSON(json['report']),
    };
}

export function GetSpendingCalendarResponseToJSON(json: any): GetSpendingCalendarResponse {
    return GetSpendingCalendarResponseToJSONTyped(json, false);
}

export function GetSpendingCalendarResponseToJSONTyped(value?: GetSpendingCalendarResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'report': SpendingCalendarReportToJSON(value['report']),
    };
}

