/* tslint:disable */
/* eslint-disable */
/**
 * Finbot application service
 * API documentation for appwsrv
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SubscriptionsReport } from './SubscriptionsReport';
import {
    SubscriptionsReportFromJSON,
    SubscriptionsReportFromJSONTyped,
    SubscriptionsReportToJSON,
    SubscriptionsReportToJSONTyped,
} from './SubscriptionsReport';

/**
 * 
 * @export
 * @interface GetSubscriptionsReportResponse
 */
export interface GetSubscriptionsReportResponse {
    /**
     * 
     * @type {SubscriptionsReport}
     * @memberof GetSubscriptionsReportResponse
     */
    report: SubscriptionsReport;
}

/**
 * Check if a given object implements the GetSubscriptionsReportResponse interface.
 */
export function instanceOfGetSubscriptionsReportResponse(value: object): value is GetSubscriptionsReportResponse {
    if (!('report' in value) || value['report'] === undefined) return false;
    return true;
}

export function GetSubscriptionsReportResponseFromJSON(json: any): GetSubscriptionsReportResponse {
    return GetSubscriptionsReportResponseFromJSONTyped(json, false);
}

export function GetSubscriptionsReportResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetSubscriptionsReportResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'report': SubscriptionsReportFromJSON(json['report']),
    };
}

export function GetSubscriptionsReportResponseToJSON(json: any): GetSubscriptionsReportResponse {
    return GetSubscriptionsReportResponseToJSONTyped(json, false);
}

export function GetSubscriptionsReportResponseToJSONTyped(value?: GetSubscriptionsReportResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'report': SubscriptionsReportToJSON(value['report']),
    };
}

