/* tslint:disable */
/* eslint-disable */
/**
 * Finbot application service
 * API documentation for appwsrv
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SpendingBreakdown } from './SpendingBreakdown';
import {
    SpendingBreakdownFromJSON,
    SpendingBreakdownFromJSONTyped,
    SpendingBreakdownToJSON,
    SpendingBreakdownToJSONTyped,
} from './SpendingBreakdown';

/**
 * 
 * @export
 * @interface GetSpendingBreakdownResponse
 */
export interface GetSpendingBreakdownResponse {
    /**
     * 
     * @type {SpendingBreakdown}
     * @memberof GetSpendingBreakdownResponse
     */
    report: SpendingBreakdown;
}

/**
 * Check if a given object implements the GetSpendingBreakdownResponse interface.
 */
export function instanceOfGetSpendingBreakdownResponse(value: object): value is GetSpendingBreakdownResponse {
    if (!('report' in value) || value['report'] === undefined) return false;
    return true;
}

export function GetSpendingBreakdownResponseFromJSON(json: any): GetSpendingBreakdownResponse {
    return GetSpendingBreakdownResponseFromJSONTyped(json, false);
}

export function GetSpendingBreakdownResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetSpendingBreakdownResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'report': SpendingBreakdownFromJSON(json['report']),
    };
}

export function GetSpendingBreakdownResponseToJSON(json: any): GetSpendingBreakdownResponse {
    return GetSpendingBreakdownResponseToJSONTyped(json, false);
}

export function GetSpendingBreakdownResponseToJSONTyped(value?: GetSpendingBreakdownResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'report': SpendingBreakdownToJSON(value['report']),
    };
}

