/* tslint:disable */
/* eslint-disable */
/**
 * Finbot application service
 * API documentation for appwsrv
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TransactionDetail } from './TransactionDetail';
import {
    TransactionDetailFromJSON,
    TransactionDetailFromJSONTyped,
    TransactionDetailToJSON,
    TransactionDetailToJSONTyped,
} from './TransactionDetail';

/**
 * 
 * @export
 * @interface GetTransactionDetailResponse
 */
export interface GetTransactionDetailResponse {
    /**
     * 
     * @type {TransactionDetail}
     * @memberof GetTransactionDetailResponse
     */
    transaction: TransactionDetail;
}

/**
 * Check if a given object implements the GetTransactionDetailResponse interface.
 */
export function instanceOfGetTransactionDetailResponse(value: object): value is GetTransactionDetailResponse {
    if (!('transaction' in value) || value['transaction'] === undefined) return false;
    return true;
}

export function GetTransactionDetailResponseFromJSON(json: any): GetTransactionDetailResponse {
    return GetTransactionDetailResponseFromJSONTyped(json, false);
}

export function GetTransactionDetailResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetTransactionDetailResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'transaction': TransactionDetailFromJSON(json['transaction']),
    };
}

export function GetTransactionDetailResponseToJSON(json: any): GetTransactionDetailResponse {
    return GetTransactionDetailResponseToJSONTyped(json, false);
}

export function GetTransactionDetailResponseToJSONTyped(value?: GetTransactionDetailResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'transaction': TransactionDetailToJSON(value['transaction']),
    };
}

