/* tslint:disable */
/* eslint-disable */
/**
 * Finbot application service
 * API documentation for appwsrv
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { UserAccountSettings } from "./UserAccountSettings";
import {
  UserAccountSettingsFromJSON,
  UserAccountSettingsFromJSONTyped,
  UserAccountSettingsToJSON,
  UserAccountSettingsToJSONTyped,
} from "./UserAccountSettings";

/**
 *
 * @export
 * @interface GetUserAccountSettingsResponse
 */
export interface GetUserAccountSettingsResponse {
  [key: string]: any | any;
  /**
   *
   * @type {UserAccountSettings}
   * @memberof GetUserAccountSettingsResponse
   */
  settings: UserAccountSettings;
}

/**
 * Check if a given object implements the GetUserAccountSettingsResponse interface.
 */
export function instanceOfGetUserAccountSettingsResponse(
  value: object,
): value is GetUserAccountSettingsResponse {
  if (!("settings" in value) || value["settings"] === undefined) return false;
  return true;
}

export function GetUserAccountSettingsResponseFromJSON(
  json: any,
): GetUserAccountSettingsResponse {
  return GetUserAccountSettingsResponseFromJSONTyped(json, false);
}

export function GetUserAccountSettingsResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): GetUserAccountSettingsResponse {
  if (json == null) {
    return json;
  }
  return {
    ...json,
    settings: UserAccountSettingsFromJSON(json["settings"]),
  };
}

export function GetUserAccountSettingsResponseToJSON(
  json: any,
): GetUserAccountSettingsResponse {
  return GetUserAccountSettingsResponseToJSONTyped(json, false);
}

export function GetUserAccountSettingsResponseToJSONTyped(
  value?: GetUserAccountSettingsResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    ...value,
    settings: UserAccountSettingsToJSON(value["settings"]),
  };
}
