/* tslint:disable */
/* eslint-disable */
/**
 * Finbot application service
 * API documentation for appwsrv
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { HistoricalValuation } from "./HistoricalValuation";
import {
  HistoricalValuationFromJSON,
  HistoricalValuationFromJSONTyped,
  HistoricalValuationToJSON,
  HistoricalValuationToJSONTyped,
} from "./HistoricalValuation";

/**
 *
 * @export
 * @interface GetUserAccountValuationHistoryByAssetTypeResponse
 */
export interface GetUserAccountValuationHistoryByAssetTypeResponse {
  [key: string]: any | any;
  /**
   *
   * @type {HistoricalValuation}
   * @memberof GetUserAccountValuationHistoryByAssetTypeResponse
   */
  historicalValuation: HistoricalValuation;
}

/**
 * Check if a given object implements the GetUserAccountValuationHistoryByAssetTypeResponse interface.
 */
export function instanceOfGetUserAccountValuationHistoryByAssetTypeResponse(
  value: object,
): value is GetUserAccountValuationHistoryByAssetTypeResponse {
  if (
    !("historicalValuation" in value) ||
    value["historicalValuation"] === undefined
  )
    return false;
  return true;
}

export function GetUserAccountValuationHistoryByAssetTypeResponseFromJSON(
  json: any,
): GetUserAccountValuationHistoryByAssetTypeResponse {
  return GetUserAccountValuationHistoryByAssetTypeResponseFromJSONTyped(
    json,
    false,
  );
}

export function GetUserAccountValuationHistoryByAssetTypeResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): GetUserAccountValuationHistoryByAssetTypeResponse {
  if (json == null) {
    return json;
  }
  return {
    ...json,
    historicalValuation: HistoricalValuationFromJSON(
      json["historical_valuation"],
    ),
  };
}

export function GetUserAccountValuationHistoryByAssetTypeResponseToJSON(
  json: any,
): GetUserAccountValuationHistoryByAssetTypeResponse {
  return GetUserAccountValuationHistoryByAssetTypeResponseToJSONTyped(
    json,
    false,
  );
}

export function GetUserAccountValuationHistoryByAssetTypeResponseToJSONTyped(
  value?: GetUserAccountValuationHistoryByAssetTypeResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    ...value,
    historical_valuation: HistoricalValuationToJSON(
      value["historicalValuation"],
    ),
  };
}
