/* tslint:disable */
/* eslint-disable */
/**
 * Finbot application service
 * API documentation for appwsrv
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { HistoricalValuation } from "./HistoricalValuation";
import {
  HistoricalValuationFromJSON,
  HistoricalValuationFromJSONTyped,
  HistoricalValuationToJSON,
  HistoricalValuationToJSONTyped,
} from "./HistoricalValuation";

/**
 *
 * @export
 * @interface GetUserAccountValuationHistoryResponse
 */
export interface GetUserAccountValuationHistoryResponse {
  [key: string]: any | any;
  /**
   *
   * @type {HistoricalValuation}
   * @memberof GetUserAccountValuationHistoryResponse
   */
  historicalValuation: HistoricalValuation;
}

/**
 * Check if a given object implements the GetUserAccountValuationHistoryResponse interface.
 */
export function instanceOfGetUserAccountValuationHistoryResponse(
  value: object,
): value is GetUserAccountValuationHistoryResponse {
  if (
    !("historicalValuation" in value) ||
    value["historicalValuation"] === undefined
  )
    return false;
  return true;
}

export function GetUserAccountValuationHistoryResponseFromJSON(
  json: any,
): GetUserAccountValuationHistoryResponse {
  return GetUserAccountValuationHistoryResponseFromJSONTyped(json, false);
}

export function GetUserAccountValuationHistoryResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): GetUserAccountValuationHistoryResponse {
  if (json == null) {
    return json;
  }
  return {
    ...json,
    historicalValuation: HistoricalValuationFromJSON(
      json["historical_valuation"],
    ),
  };
}

export function GetUserAccountValuationHistoryResponseToJSON(
  json: any,
): GetUserAccountValuationHistoryResponse {
  return GetUserAccountValuationHistoryResponseToJSONTyped(json, false);
}

export function GetUserAccountValuationHistoryResponseToJSONTyped(
  value?: GetUserAccountValuationHistoryResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    ...value,
    historical_valuation: HistoricalValuationToJSON(
      value["historicalValuation"],
    ),
  };
}
