/* tslint:disable */
/* eslint-disable */
/**
 * Finbot application service
 * API documentation for appwsrv
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { ValuationByAssetType } from "./ValuationByAssetType";
import {
  ValuationByAssetTypeFromJSON,
  ValuationByAssetTypeFromJSONTyped,
  ValuationByAssetTypeToJSON,
  ValuationByAssetTypeToJSONTyped,
} from "./ValuationByAssetType";

/**
 *
 * @export
 * @interface GetUserAccountValuationByAssetTypeResponse
 */
export interface GetUserAccountValuationByAssetTypeResponse {
  [key: string]: any | any;
  /**
   *
   * @type {ValuationByAssetType}
   * @memberof GetUserAccountValuationByAssetTypeResponse
   */
  valuation: ValuationByAssetType;
}

/**
 * Check if a given object implements the GetUserAccountValuationByAssetTypeResponse interface.
 */
export function instanceOfGetUserAccountValuationByAssetTypeResponse(
  value: object,
): value is GetUserAccountValuationByAssetTypeResponse {
  if (!("valuation" in value) || value["valuation"] === undefined) return false;
  return true;
}

export function GetUserAccountValuationByAssetTypeResponseFromJSON(
  json: any,
): GetUserAccountValuationByAssetTypeResponse {
  return GetUserAccountValuationByAssetTypeResponseFromJSONTyped(json, false);
}

export function GetUserAccountValuationByAssetTypeResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): GetUserAccountValuationByAssetTypeResponse {
  if (json == null) {
    return json;
  }
  return {
    ...json,
    valuation: ValuationByAssetTypeFromJSON(json["valuation"]),
  };
}

export function GetUserAccountValuationByAssetTypeResponseToJSON(
  json: any,
): GetUserAccountValuationByAssetTypeResponse {
  return GetUserAccountValuationByAssetTypeResponseToJSONTyped(json, false);
}

export function GetUserAccountValuationByAssetTypeResponseToJSONTyped(
  value?: GetUserAccountValuationByAssetTypeResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    ...value,
    valuation: ValuationByAssetTypeToJSON(value["valuation"]),
  };
}
