/* tslint:disable */
/* eslint-disable */
/**
 * Finbot application service
 * API documentation for appwsrv
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface IsUserAccountConfiguredResponse
 */
export interface IsUserAccountConfiguredResponse {
  [key: string]: any | any;
  /**
   *
   * @type {boolean}
   * @memberof IsUserAccountConfiguredResponse
   */
  configured: boolean;
}

/**
 * Check if a given object implements the IsUserAccountConfiguredResponse interface.
 */
export function instanceOfIsUserAccountConfiguredResponse(
  value: object,
): value is IsUserAccountConfiguredResponse {
  if (!("configured" in value) || value["configured"] === undefined)
    return false;
  return true;
}

export function IsUserAccountConfiguredResponseFromJSON(
  json: any,
): IsUserAccountConfiguredResponse {
  return IsUserAccountConfiguredResponseFromJSONTyped(json, false);
}

export function IsUserAccountConfiguredResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): IsUserAccountConfiguredResponse {
  if (json == null) {
    return json;
  }
  return {
    ...json,
    configured: json["configured"],
  };
}

export function IsUserAccountConfiguredResponseToJSON(
  json: any,
): IsUserAccountConfiguredResponse {
  return IsUserAccountConfiguredResponseToJSONTyped(json, false);
}

export function IsUserAccountConfiguredResponseToJSONTyped(
  value?: IsUserAccountConfiguredResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    ...value,
    configured: value["configured"],
  };
}
