/* tslint:disable */
/* eslint-disable */
/**
 * Finbot application service
 * API documentation for appwsrv
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { ValuationChange } from "./ValuationChange";
import {
  ValuationChangeFromJSON,
  ValuationChangeFromJSONTyped,
  ValuationChangeToJSON,
  ValuationChangeToJSONTyped,
} from "./ValuationChange";

/**
 *
 * @export
 * @interface LinkedAccountValuation
 */
export interface LinkedAccountValuation {
  /**
   *
   * @type {Date}
   * @memberof LinkedAccountValuation
   */
  date: Date;
  /**
   *
   * @type {string}
   * @memberof LinkedAccountValuation
   */
  currency: string;
  /**
   *
   * @type {number}
   * @memberof LinkedAccountValuation
   */
  value: number;
  /**
   *
   * @type {ValuationChange}
   * @memberof LinkedAccountValuation
   */
  change: ValuationChange;
}

/**
 * Check if a given object implements the LinkedAccountValuation interface.
 */
export function instanceOfLinkedAccountValuation(
  value: object,
): value is LinkedAccountValuation {
  if (!("date" in value) || value["date"] === undefined) return false;
  if (!("currency" in value) || value["currency"] === undefined) return false;
  if (!("value" in value) || value["value"] === undefined) return false;
  if (!("change" in value) || value["change"] === undefined) return false;
  return true;
}

export function LinkedAccountValuationFromJSON(
  json: any,
): LinkedAccountValuation {
  return LinkedAccountValuationFromJSONTyped(json, false);
}

export function LinkedAccountValuationFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): LinkedAccountValuation {
  if (json == null) {
    return json;
  }
  return {
    date: new Date(json["date"]),
    currency: json["currency"],
    value: json["value"],
    change: ValuationChangeFromJSON(json["change"]),
  };
}

export function LinkedAccountValuationToJSON(
  json: any,
): LinkedAccountValuation {
  return LinkedAccountValuationToJSONTyped(json, false);
}

export function LinkedAccountValuationToJSONTyped(
  value?: LinkedAccountValuation | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    date: value["date"].toISOString(),
    currency: value["currency"],
    value: value["value"],
    change: ValuationChangeToJSON(value["change"]),
  };
}
