/* tslint:disable */
/* eslint-disable */
/**
 * Finbot application service
 * API documentation for appwsrv
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface LinkAccountRequest
 */
export interface LinkAccountRequest {
  [key: string]: any | any;
  /**
   *
   * @type {string}
   * @memberof LinkAccountRequest
   */
  providerId: string;
  /**
   *
   * @type {{ [key: string]: any; }}
   * @memberof LinkAccountRequest
   */
  credentials: { [key: string]: any };
  /**
   *
   * @type {string}
   * @memberof LinkAccountRequest
   */
  accountName: string;
  /**
   *
   * @type {string}
   * @memberof LinkAccountRequest
   */
  accountColour: string;
}

/**
 * Check if a given object implements the LinkAccountRequest interface.
 */
export function instanceOfLinkAccountRequest(
  value: object,
): value is LinkAccountRequest {
  if (!("providerId" in value) || value["providerId"] === undefined)
    return false;
  if (!("credentials" in value) || value["credentials"] === undefined)
    return false;
  if (!("accountName" in value) || value["accountName"] === undefined)
    return false;
  if (!("accountColour" in value) || value["accountColour"] === undefined)
    return false;
  return true;
}

export function LinkAccountRequestFromJSON(json: any): LinkAccountRequest {
  return LinkAccountRequestFromJSONTyped(json, false);
}

export function LinkAccountRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): LinkAccountRequest {
  if (json == null) {
    return json;
  }
  return {
    ...json,
    providerId: json["provider_id"],
    credentials: json["credentials"],
    accountName: json["account_name"],
    accountColour: json["account_colour"],
  };
}

export function LinkAccountRequestToJSON(json: any): LinkAccountRequest {
  return LinkAccountRequestToJSONTyped(json, false);
}

export function LinkAccountRequestToJSONTyped(
  value?: LinkAccountRequest | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    ...value,
    provider_id: value["providerId"],
    credentials: value["credentials"],
    account_name: value["accountName"],
    account_colour: value["accountColour"],
  };
}
