/* tslint:disable */
/* eslint-disable */
/**
 * Finbot application service
 * API documentation for appwsrv
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MarkNotificationsReadResponse
 */
export interface MarkNotificationsReadResponse {
    /**
     * 
     * @type {number}
     * @memberof MarkNotificationsReadResponse
     */
    unreadCount: number;
}

/**
 * Check if a given object implements the MarkNotificationsReadResponse interface.
 */
export function instanceOfMarkNotificationsReadResponse(value: object): value is MarkNotificationsReadResponse {
    if (!('unreadCount' in value) || value['unreadCount'] === undefined) return false;
    return true;
}

export function MarkNotificationsReadResponseFromJSON(json: any): MarkNotificationsReadResponse {
    return MarkNotificationsReadResponseFromJSONTyped(json, false);
}

export function MarkNotificationsReadResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): MarkNotificationsReadResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'unreadCount': json['unread_count'],
    };
}

export function MarkNotificationsReadResponseToJSON(json: any): MarkNotificationsReadResponse {
    return MarkNotificationsReadResponseToJSONTyped(json, false);
}

export function MarkNotificationsReadResponseToJSONTyped(value?: MarkNotificationsReadResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'unread_count': value['unreadCount'],
    };
}

