/* tslint:disable */
/* eslint-disable */
/**
 * Finbot application service
 * API documentation for appwsrv
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MatchDetail
 */
export interface MatchDetail {
    /**
     * 
     * @type {number}
     * @memberof MatchDetail
     */
    matchConfidence: number;
    /**
     * 
     * @type {string}
     * @memberof MatchDetail
     */
    matchStatus: string;
    /**
     * 
     * @type {number}
     * @memberof MatchDetail
     */
    counterpartTransactionId: number;
    /**
     * 
     * @type {string}
     * @memberof MatchDetail
     */
    counterpartAccountName: string;
    /**
     * 
     * @type {string}
     * @memberof MatchDetail
     */
    counterpartDescription: string;
    /**
     * 
     * @type {number}
     * @memberof MatchDetail
     */
    counterpartAmount: number;
    /**
     * 
     * @type {string}
     * @memberof MatchDetail
     */
    counterpartCurrency: string;
}

/**
 * Check if a given object implements the MatchDetail interface.
 */
export function instanceOfMatchDetail(value: object): value is MatchDetail {
    if (!('matchConfidence' in value) || value['matchConfidence'] === undefined) return false;
    if (!('matchStatus' in value) || value['matchStatus'] === undefined) return false;
    if (!('counterpartTransactionId' in value) || value['counterpartTransactionId'] === undefined) return false;
    if (!('counterpartAccountName' in value) || value['counterpartAccountName'] === undefined) return false;
    if (!('counterpartDescription' in value) || value['counterpartDescription'] === undefined) return false;
    if (!('counterpartAmount' in value) || value['counterpartAmount'] === undefined) return false;
    if (!('counterpartCurrency' in value) || value['counterpartCurrency'] === undefined) return false;
    return true;
}

export function MatchDetailFromJSON(json: any): MatchDetail {
    return MatchDetailFromJSONTyped(json, false);
}

export function MatchDetailFromJSONTyped(json: any, ignoreDiscriminator: boolean): MatchDetail {
    if (json == null) {
        return json;
    }
    return {
        
        'matchConfidence': json['match_confidence'],
        'matchStatus': json['match_status'],
        'counterpartTransactionId': json['counterpart_transaction_id'],
        'counterpartAccountName': json['counterpart_account_name'],
        'counterpartDescription': json['counterpart_description'],
        'counterpartAmount': json['counterpart_amount'],
        'counterpartCurrency': json['counterpart_currency'],
    };
}

export function MatchDetailToJSON(json: any): MatchDetail {
    return MatchDetailToJSONTyped(json, false);
}

export function MatchDetailToJSONTyped(value?: MatchDetail | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'match_confidence': value['matchConfidence'],
        'match_status': value['matchStatus'],
        'counterpart_transaction_id': value['counterpartTransactionId'],
        'counterpart_account_name': value['counterpartAccountName'],
        'counterpart_description': value['counterpartDescription'],
        'counterpart_amount': value['counterpartAmount'],
        'counterpart_currency': value['counterpartCurrency'],
    };
}

