/* tslint:disable */
/* eslint-disable */
/**
 * Finbot application service
 * API documentation for appwsrv
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PortfolioSection } from './PortfolioSection';
import {
    PortfolioSectionFromJSON,
    PortfolioSectionFromJSONTyped,
    PortfolioSectionToJSON,
    PortfolioSectionToJSONTyped,
} from './PortfolioSection';

/**
 * 
 * @export
 * @interface Portfolio
 */
export interface Portfolio {
    /**
     * 
     * @type {number}
     * @memberof Portfolio
     */
    id: number;
    /**
     * 
     * @type {number}
     * @memberof Portfolio
     */
    linkedAccountId: number;
    /**
     * 
     * @type {string}
     * @memberof Portfolio
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof Portfolio
     */
    colour: string;
    /**
     * 
     * @type {boolean}
     * @memberof Portfolio
     */
    frozen: boolean;
    /**
     * 
     * @type {number}
     * @memberof Portfolio
     */
    estimatedValue: number | null;
    /**
     * 
     * @type {string}
     * @memberof Portfolio
     */
    valuationCcy: string;
    /**
     * 
     * @type {Array<PortfolioSection>}
     * @memberof Portfolio
     */
    sections: Array<PortfolioSection>;
    /**
     * 
     * @type {Date}
     * @memberof Portfolio
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof Portfolio
     */
    updatedAt: Date | null;
}

/**
 * Check if a given object implements the Portfolio interface.
 */
export function instanceOfPortfolio(value: object): value is Portfolio {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('linkedAccountId' in value) || value['linkedAccountId'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('colour' in value) || value['colour'] === undefined) return false;
    if (!('frozen' in value) || value['frozen'] === undefined) return false;
    if (!('estimatedValue' in value) || value['estimatedValue'] === undefined) return false;
    if (!('valuationCcy' in value) || value['valuationCcy'] === undefined) return false;
    if (!('sections' in value) || value['sections'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function PortfolioFromJSON(json: any): Portfolio {
    return PortfolioFromJSONTyped(json, false);
}

export function PortfolioFromJSONTyped(json: any, ignoreDiscriminator: boolean): Portfolio {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'linkedAccountId': json['linked_account_id'],
        'name': json['name'],
        'colour': json['colour'],
        'frozen': json['frozen'],
        'estimatedValue': json['estimated_value'],
        'valuationCcy': json['valuation_ccy'],
        'sections': ((json['sections'] as Array<any>).map(PortfolioSectionFromJSON)),
        'createdAt': (new Date(json['created_at'])),
        'updatedAt': (json['updated_at'] == null ? null : new Date(json['updated_at'])),
    };
}

export function PortfolioToJSON(json: any): Portfolio {
    return PortfolioToJSONTyped(json, false);
}

export function PortfolioToJSONTyped(value?: Portfolio | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'linked_account_id': value['linkedAccountId'],
        'name': value['name'],
        'colour': value['colour'],
        'frozen': value['frozen'],
        'estimated_value': value['estimatedValue'],
        'valuation_ccy': value['valuationCcy'],
        'sections': ((value['sections'] as Array<any>).map(PortfolioSectionToJSON)),
        'created_at': ((value['createdAt']).toISOString()),
        'updated_at': (value['updatedAt'] == null ? null : (value['updatedAt'] as any).toISOString()),
    };
}

