/* tslint:disable */
/* eslint-disable */
/**
 * Finbot application service
 * API documentation for appwsrv
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AssetType } from './AssetType';
import {
    AssetTypeFromJSON,
    AssetTypeFromJSONTyped,
    AssetTypeToJSON,
    AssetTypeToJSONTyped,
} from './AssetType';
import type { AssetClass } from './AssetClass';
import {
    AssetClassFromJSON,
    AssetClassFromJSONTyped,
    AssetClassToJSON,
    AssetClassToJSONTyped,
} from './AssetClass';

/**
 * 
 * @export
 * @interface PortfolioEntry
 */
export interface PortfolioEntry {
    /**
     * 
     * @type {number}
     * @memberof PortfolioEntry
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof PortfolioEntry
     */
    itemType: PortfolioEntryItemTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof PortfolioEntry
     */
    name: string;
    /**
     * 
     * @type {AssetClass}
     * @memberof PortfolioEntry
     */
    assetClass: AssetClass | null;
    /**
     * 
     * @type {AssetType}
     * @memberof PortfolioEntry
     */
    assetType: AssetType | null;
    /**
     * 
     * @type {string}
     * @memberof PortfolioEntry
     */
    liabilityType: string | null;
    /**
     * 
     * @type {string}
     * @memberof PortfolioEntry
     */
    currency: string;
    /**
     * 
     * @type {number}
     * @memberof PortfolioEntry
     */
    units: number;
    /**
     * 
     * @type {string}
     * @memberof PortfolioEntry
     */
    priceSource: PortfolioEntryPriceSourceEnum;
    /**
     * 
     * @type {number}
     * @memberof PortfolioEntry
     */
    unitPrice: number | null;
    /**
     * 
     * @type {number}
     * @memberof PortfolioEntry
     */
    manualUnitPrice: number | null;
    /**
     * 
     * @type {Date}
     * @memberof PortfolioEntry
     */
    manualPriceUpdatedAt: Date | null;
    /**
     * 
     * @type {string}
     * @memberof PortfolioEntry
     */
    proxySymbol: string | null;
    /**
     * 
     * @type {string}
     * @memberof PortfolioEntry
     */
    proxyName: string | null;
    /**
     * 
     * @type {number}
     * @memberof PortfolioEntry
     */
    lastResolvedUnitPrice: number | null;
    /**
     * 
     * @type {Date}
     * @memberof PortfolioEntry
     */
    lastResolvedPriceAt: Date | null;
    /**
     * 
     * @type {string}
     * @memberof PortfolioEntry
     */
    isinCode: string | null;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof PortfolioEntry
     */
    customValues: { [key: string]: string; };
    /**
     * 
     * @type {number}
     * @memberof PortfolioEntry
     */
    value: number | null;
    /**
     * 
     * @type {number}
     * @memberof PortfolioEntry
     */
    estimatedValue: number | null;
    /**
     * 
     * @type {number}
     * @memberof PortfolioEntry
     */
    displayOrder: number;
}


/**
 * @export
 */
export const PortfolioEntryItemTypeEnum = {
    Asset: 'asset',
    Liability: 'liability'
} as const;
export type PortfolioEntryItemTypeEnum = typeof PortfolioEntryItemTypeEnum[keyof typeof PortfolioEntryItemTypeEnum];

/**
 * @export
 */
export const PortfolioEntryPriceSourceEnum = {
    Manual: 'manual',
    Proxy: 'proxy'
} as const;
export type PortfolioEntryPriceSourceEnum = typeof PortfolioEntryPriceSourceEnum[keyof typeof PortfolioEntryPriceSourceEnum];


/**
 * Check if a given object implements the PortfolioEntry interface.
 */
export function instanceOfPortfolioEntry(value: object): value is PortfolioEntry {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('itemType' in value) || value['itemType'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('assetClass' in value) || value['assetClass'] === undefined) return false;
    if (!('assetType' in value) || value['assetType'] === undefined) return false;
    if (!('liabilityType' in value) || value['liabilityType'] === undefined) return false;
    if (!('currency' in value) || value['currency'] === undefined) return false;
    if (!('units' in value) || value['units'] === undefined) return false;
    if (!('priceSource' in value) || value['priceSource'] === undefined) return false;
    if (!('unitPrice' in value) || value['unitPrice'] === undefined) return false;
    if (!('manualUnitPrice' in value) || value['manualUnitPrice'] === undefined) return false;
    if (!('manualPriceUpdatedAt' in value) || value['manualPriceUpdatedAt'] === undefined) return false;
    if (!('proxySymbol' in value) || value['proxySymbol'] === undefined) return false;
    if (!('proxyName' in value) || value['proxyName'] === undefined) return false;
    if (!('lastResolvedUnitPrice' in value) || value['lastResolvedUnitPrice'] === undefined) return false;
    if (!('lastResolvedPriceAt' in value) || value['lastResolvedPriceAt'] === undefined) return false;
    if (!('isinCode' in value) || value['isinCode'] === undefined) return false;
    if (!('customValues' in value) || value['customValues'] === undefined) return false;
    if (!('value' in value) || value['value'] === undefined) return false;
    if (!('estimatedValue' in value) || value['estimatedValue'] === undefined) return false;
    if (!('displayOrder' in value) || value['displayOrder'] === undefined) return false;
    return true;
}

export function PortfolioEntryFromJSON(json: any): PortfolioEntry {
    return PortfolioEntryFromJSONTyped(json, false);
}

export function PortfolioEntryFromJSONTyped(json: any, ignoreDiscriminator: boolean): PortfolioEntry {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'itemType': json['item_type'],
        'name': json['name'],
        'assetClass': AssetClassFromJSON(json['asset_class']),
        'assetType': AssetTypeFromJSON(json['asset_type']),
        'liabilityType': json['liability_type'],
        'currency': json['currency'],
        'units': json['units'],
        'priceSource': json['price_source'],
        'unitPrice': json['unit_price'],
        'manualUnitPrice': json['manual_unit_price'],
        'manualPriceUpdatedAt': (json['manual_price_updated_at'] == null ? null : new Date(json['manual_price_updated_at'])),
        'proxySymbol': json['proxy_symbol'],
        'proxyName': json['proxy_name'],
        'lastResolvedUnitPrice': json['last_resolved_unit_price'],
        'lastResolvedPriceAt': (json['last_resolved_price_at'] == null ? null : new Date(json['last_resolved_price_at'])),
        'isinCode': json['isin_code'],
        'customValues': json['custom_values'],
        'value': json['value'],
        'estimatedValue': json['estimated_value'],
        'displayOrder': json['display_order'],
    };
}

export function PortfolioEntryToJSON(json: any): PortfolioEntry {
    return PortfolioEntryToJSONTyped(json, false);
}

export function PortfolioEntryToJSONTyped(value?: PortfolioEntry | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'item_type': value['itemType'],
        'name': value['name'],
        'asset_class': AssetClassToJSON(value['assetClass']),
        'asset_type': AssetTypeToJSON(value['assetType']),
        'liability_type': value['liabilityType'],
        'currency': value['currency'],
        'units': value['units'],
        'price_source': value['priceSource'],
        'unit_price': value['unitPrice'],
        'manual_unit_price': value['manualUnitPrice'],
        'manual_price_updated_at': (value['manualPriceUpdatedAt'] == null ? null : (value['manualPriceUpdatedAt'] as any).toISOString()),
        'proxy_symbol': value['proxySymbol'],
        'proxy_name': value['proxyName'],
        'last_resolved_unit_price': value['lastResolvedUnitPrice'],
        'last_resolved_price_at': (value['lastResolvedPriceAt'] == null ? null : (value['lastResolvedPriceAt'] as any).toISOString()),
        'isin_code': value['isinCode'],
        'custom_values': value['customValues'],
        'value': value['value'],
        'estimated_value': value['estimatedValue'],
        'display_order': value['displayOrder'],
    };
}

