/* tslint:disable */
/* eslint-disable */
/**
 * Finbot application service
 * API documentation for appwsrv
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PortfolioCustomColumn
 */
export interface PortfolioCustomColumn {
    /**
     * 
     * @type {string}
     * @memberof PortfolioCustomColumn
     */
    key: string;
    /**
     * 
     * @type {string}
     * @memberof PortfolioCustomColumn
     */
    label: string;
    /**
     * 
     * @type {string}
     * @memberof PortfolioCustomColumn
     */
    type?: PortfolioCustomColumnTypeEnum;
}


/**
 * @export
 */
export const PortfolioCustomColumnTypeEnum = {
    Text: 'text',
    Number: 'number',
    Date: 'date'
} as const;
export type PortfolioCustomColumnTypeEnum = typeof PortfolioCustomColumnTypeEnum[keyof typeof PortfolioCustomColumnTypeEnum];


/**
 * Check if a given object implements the PortfolioCustomColumn interface.
 */
export function instanceOfPortfolioCustomColumn(value: object): value is PortfolioCustomColumn {
    if (!('key' in value) || value['key'] === undefined) return false;
    if (!('label' in value) || value['label'] === undefined) return false;
    return true;
}

export function PortfolioCustomColumnFromJSON(json: any): PortfolioCustomColumn {
    return PortfolioCustomColumnFromJSONTyped(json, false);
}

export function PortfolioCustomColumnFromJSONTyped(json: any, ignoreDiscriminator: boolean): PortfolioCustomColumn {
    if (json == null) {
        return json;
    }
    return {
        
        'key': json['key'],
        'label': json['label'],
        'type': json['type'] == null ? undefined : json['type'],
    };
}

export function PortfolioCustomColumnToJSON(json: any): PortfolioCustomColumn {
    return PortfolioCustomColumnToJSONTyped(json, false);
}

export function PortfolioCustomColumnToJSONTyped(value?: PortfolioCustomColumn | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'key': value['key'],
        'label': value['label'],
        'type': value['type'],
    };
}

