/* tslint:disable */
/* eslint-disable */
/**
 * Finbot application service
 * API documentation for appwsrv
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PortfolioCustomColumn } from './PortfolioCustomColumn';
import {
    PortfolioCustomColumnFromJSON,
    PortfolioCustomColumnFromJSONTyped,
    PortfolioCustomColumnToJSON,
    PortfolioCustomColumnToJSONTyped,
} from './PortfolioCustomColumn';
import type { AccountType } from './AccountType';
import {
    AccountTypeFromJSON,
    AccountTypeFromJSONTyped,
    AccountTypeToJSON,
    AccountTypeToJSONTyped,
} from './AccountType';

/**
 * Full description of a portfolio section: used to both create and replace sections.
 * @export
 * @interface PortfolioSectionPayload
 */
export interface PortfolioSectionPayload {
    /**
     * 
     * @type {string}
     * @memberof PortfolioSectionPayload
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof PortfolioSectionPayload
     */
    currency: string;
    /**
     * 
     * @type {AccountType}
     * @memberof PortfolioSectionPayload
     */
    accountType: AccountType;
    /**
     * 
     * @type {string}
     * @memberof PortfolioSectionPayload
     */
    accountSubType?: string | null;
    /**
     * 
     * @type {Array<PortfolioCustomColumn>}
     * @memberof PortfolioSectionPayload
     */
    customColumns?: Array<PortfolioCustomColumn>;
}



/**
 * Check if a given object implements the PortfolioSectionPayload interface.
 */
export function instanceOfPortfolioSectionPayload(value: object): value is PortfolioSectionPayload {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('currency' in value) || value['currency'] === undefined) return false;
    if (!('accountType' in value) || value['accountType'] === undefined) return false;
    return true;
}

export function PortfolioSectionPayloadFromJSON(json: any): PortfolioSectionPayload {
    return PortfolioSectionPayloadFromJSONTyped(json, false);
}

export function PortfolioSectionPayloadFromJSONTyped(json: any, ignoreDiscriminator: boolean): PortfolioSectionPayload {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'currency': json['currency'],
        'accountType': AccountTypeFromJSON(json['account_type']),
        'accountSubType': json['account_sub_type'] == null ? undefined : json['account_sub_type'],
        'customColumns': json['custom_columns'] == null ? undefined : ((json['custom_columns'] as Array<any>).map(PortfolioCustomColumnFromJSON)),
    };
}

export function PortfolioSectionPayloadToJSON(json: any): PortfolioSectionPayload {
    return PortfolioSectionPayloadToJSONTyped(json, false);
}

export function PortfolioSectionPayloadToJSONTyped(value?: PortfolioSectionPayload | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'currency': value['currency'],
        'account_type': AccountTypeToJSON(value['accountType']),
        'account_sub_type': value['accountSubType'],
        'custom_columns': value['customColumns'] == null ? undefined : ((value['customColumns'] as Array<any>).map(PortfolioCustomColumnToJSON)),
    };
}

