/* tslint:disable */
/* eslint-disable */
/**
 * Finbot application service
 * API documentation for appwsrv
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PortfolioCustomColumn } from './PortfolioCustomColumn';
import {
    PortfolioCustomColumnFromJSON,
    PortfolioCustomColumnFromJSONTyped,
    PortfolioCustomColumnToJSON,
    PortfolioCustomColumnToJSONTyped,
} from './PortfolioCustomColumn';
import type { PortfolioEntry } from './PortfolioEntry';
import {
    PortfolioEntryFromJSON,
    PortfolioEntryFromJSONTyped,
    PortfolioEntryToJSON,
    PortfolioEntryToJSONTyped,
} from './PortfolioEntry';
import type { AccountType } from './AccountType';
import {
    AccountTypeFromJSON,
    AccountTypeFromJSONTyped,
    AccountTypeToJSON,
    AccountTypeToJSONTyped,
} from './AccountType';

/**
 * 
 * @export
 * @interface PortfolioSection
 */
export interface PortfolioSection {
    /**
     * 
     * @type {number}
     * @memberof PortfolioSection
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof PortfolioSection
     */
    sectionId: string;
    /**
     * 
     * @type {string}
     * @memberof PortfolioSection
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof PortfolioSection
     */
    currency: string;
    /**
     * 
     * @type {AccountType}
     * @memberof PortfolioSection
     */
    accountType: AccountType;
    /**
     * 
     * @type {string}
     * @memberof PortfolioSection
     */
    accountSubType: string | null;
    /**
     * 
     * @type {Array<PortfolioCustomColumn>}
     * @memberof PortfolioSection
     */
    customColumns: Array<PortfolioCustomColumn>;
    /**
     * 
     * @type {number}
     * @memberof PortfolioSection
     */
    displayOrder: number;
    /**
     * 
     * @type {number}
     * @memberof PortfolioSection
     */
    estimatedValue: number | null;
    /**
     * 
     * @type {Array<PortfolioEntry>}
     * @memberof PortfolioSection
     */
    entries: Array<PortfolioEntry>;
}



/**
 * Check if a given object implements the PortfolioSection interface.
 */
export function instanceOfPortfolioSection(value: object): value is PortfolioSection {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('sectionId' in value) || value['sectionId'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('currency' in value) || value['currency'] === undefined) return false;
    if (!('accountType' in value) || value['accountType'] === undefined) return false;
    if (!('accountSubType' in value) || value['accountSubType'] === undefined) return false;
    if (!('customColumns' in value) || value['customColumns'] === undefined) return false;
    if (!('displayOrder' in value) || value['displayOrder'] === undefined) return false;
    if (!('estimatedValue' in value) || value['estimatedValue'] === undefined) return false;
    if (!('entries' in value) || value['entries'] === undefined) return false;
    return true;
}

export function PortfolioSectionFromJSON(json: any): PortfolioSection {
    return PortfolioSectionFromJSONTyped(json, false);
}

export function PortfolioSectionFromJSONTyped(json: any, ignoreDiscriminator: boolean): PortfolioSection {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'sectionId': json['section_id'],
        'name': json['name'],
        'currency': json['currency'],
        'accountType': AccountTypeFromJSON(json['account_type']),
        'accountSubType': json['account_sub_type'],
        'customColumns': ((json['custom_columns'] as Array<any>).map(PortfolioCustomColumnFromJSON)),
        'displayOrder': json['display_order'],
        'estimatedValue': json['estimated_value'],
        'entries': ((json['entries'] as Array<any>).map(PortfolioEntryFromJSON)),
    };
}

export function PortfolioSectionToJSON(json: any): PortfolioSection {
    return PortfolioSectionToJSONTyped(json, false);
}

export function PortfolioSectionToJSONTyped(value?: PortfolioSection | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'section_id': value['sectionId'],
        'name': value['name'],
        'currency': value['currency'],
        'account_type': AccountTypeToJSON(value['accountType']),
        'account_sub_type': value['accountSubType'],
        'custom_columns': ((value['customColumns'] as Array<any>).map(PortfolioCustomColumnToJSON)),
        'display_order': value['displayOrder'],
        'estimated_value': value['estimatedValue'],
        'entries': ((value['entries'] as Array<any>).map(PortfolioEntryToJSON)),
    };
}

