/* tslint:disable */
/* eslint-disable */
/**
 * Finbot application service
 * API documentation for appwsrv
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PortfolioSummary
 */
export interface PortfolioSummary {
    /**
     * 
     * @type {number}
     * @memberof PortfolioSummary
     */
    id: number;
    /**
     * 
     * @type {number}
     * @memberof PortfolioSummary
     */
    linkedAccountId: number;
    /**
     * 
     * @type {string}
     * @memberof PortfolioSummary
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof PortfolioSummary
     */
    colour: string;
    /**
     * 
     * @type {boolean}
     * @memberof PortfolioSummary
     */
    frozen: boolean;
    /**
     * 
     * @type {number}
     * @memberof PortfolioSummary
     */
    sectionsCount: number;
    /**
     * 
     * @type {number}
     * @memberof PortfolioSummary
     */
    entriesCount: number;
    /**
     * 
     * @type {number}
     * @memberof PortfolioSummary
     */
    estimatedValue: number | null;
    /**
     * 
     * @type {string}
     * @memberof PortfolioSummary
     */
    valuationCcy: string;
    /**
     * 
     * @type {Date}
     * @memberof PortfolioSummary
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof PortfolioSummary
     */
    updatedAt: Date | null;
}

/**
 * Check if a given object implements the PortfolioSummary interface.
 */
export function instanceOfPortfolioSummary(value: object): value is PortfolioSummary {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('linkedAccountId' in value) || value['linkedAccountId'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('colour' in value) || value['colour'] === undefined) return false;
    if (!('frozen' in value) || value['frozen'] === undefined) return false;
    if (!('sectionsCount' in value) || value['sectionsCount'] === undefined) return false;
    if (!('entriesCount' in value) || value['entriesCount'] === undefined) return false;
    if (!('estimatedValue' in value) || value['estimatedValue'] === undefined) return false;
    if (!('valuationCcy' in value) || value['valuationCcy'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function PortfolioSummaryFromJSON(json: any): PortfolioSummary {
    return PortfolioSummaryFromJSONTyped(json, false);
}

export function PortfolioSummaryFromJSONTyped(json: any, ignoreDiscriminator: boolean): PortfolioSummary {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'linkedAccountId': json['linked_account_id'],
        'name': json['name'],
        'colour': json['colour'],
        'frozen': json['frozen'],
        'sectionsCount': json['sections_count'],
        'entriesCount': json['entries_count'],
        'estimatedValue': json['estimated_value'],
        'valuationCcy': json['valuation_ccy'],
        'createdAt': (new Date(json['created_at'])),
        'updatedAt': (json['updated_at'] == null ? null : new Date(json['updated_at'])),
    };
}

export function PortfolioSummaryToJSON(json: any): PortfolioSummary {
    return PortfolioSummaryToJSONTyped(json, false);
}

export function PortfolioSummaryToJSONTyped(value?: PortfolioSummary | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'linked_account_id': value['linkedAccountId'],
        'name': value['name'],
        'colour': value['colour'],
        'frozen': value['frozen'],
        'sections_count': value['sectionsCount'],
        'entries_count': value['entriesCount'],
        'estimated_value': value['estimatedValue'],
        'valuation_ccy': value['valuationCcy'],
        'created_at': ((value['createdAt']).toISOString()),
        'updated_at': (value['updatedAt'] == null ? null : (value['updatedAt'] as any).toISOString()),
    };
}

