/* tslint:disable */
/* eslint-disable */
/**
 * Finbot application service
 * API documentation for appwsrv
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RecurringGroupDetail
 */
export interface RecurringGroupDetail {
    /**
     * 
     * @type {number}
     * @memberof RecurringGroupDetail
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof RecurringGroupDetail
     */
    currency: string;
    /**
     * 
     * @type {number}
     * @memberof RecurringGroupDetail
     */
    avgAmount: number;
    /**
     * 
     * @type {number}
     * @memberof RecurringGroupDetail
     */
    avgIntervalDays: number;
    /**
     * 
     * @type {number}
     * @memberof RecurringGroupDetail
     */
    transactionCount: number;
    /**
     * 
     * @type {number}
     * @memberof RecurringGroupDetail
     */
    totalSpent: number;
    /**
     * 
     * @type {number}
     * @memberof RecurringGroupDetail
     */
    totalSpentCcy: number | null;
    /**
     * 
     * @type {number}
     * @memberof RecurringGroupDetail
     */
    yearlyCost: number;
    /**
     * 
     * @type {Date}
     * @memberof RecurringGroupDetail
     */
    firstSeen: Date;
    /**
     * 
     * @type {Date}
     * @memberof RecurringGroupDetail
     */
    lastSeen: Date;
    /**
     * 
     * @type {string}
     * @memberof RecurringGroupDetail
     */
    description?: string | null;
}

/**
 * Check if a given object implements the RecurringGroupDetail interface.
 */
export function instanceOfRecurringGroupDetail(value: object): value is RecurringGroupDetail {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('currency' in value) || value['currency'] === undefined) return false;
    if (!('avgAmount' in value) || value['avgAmount'] === undefined) return false;
    if (!('avgIntervalDays' in value) || value['avgIntervalDays'] === undefined) return false;
    if (!('transactionCount' in value) || value['transactionCount'] === undefined) return false;
    if (!('totalSpent' in value) || value['totalSpent'] === undefined) return false;
    if (!('totalSpentCcy' in value) || value['totalSpentCcy'] === undefined) return false;
    if (!('yearlyCost' in value) || value['yearlyCost'] === undefined) return false;
    if (!('firstSeen' in value) || value['firstSeen'] === undefined) return false;
    if (!('lastSeen' in value) || value['lastSeen'] === undefined) return false;
    return true;
}

export function RecurringGroupDetailFromJSON(json: any): RecurringGroupDetail {
    return RecurringGroupDetailFromJSONTyped(json, false);
}

export function RecurringGroupDetailFromJSONTyped(json: any, ignoreDiscriminator: boolean): RecurringGroupDetail {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'currency': json['currency'],
        'avgAmount': json['avg_amount'],
        'avgIntervalDays': json['avg_interval_days'],
        'transactionCount': json['transaction_count'],
        'totalSpent': json['total_spent'],
        'totalSpentCcy': json['total_spent_ccy'],
        'yearlyCost': json['yearly_cost'],
        'firstSeen': (new Date(json['first_seen'])),
        'lastSeen': (new Date(json['last_seen'])),
        'description': json['description'] == null ? undefined : json['description'],
    };
}

export function RecurringGroupDetailToJSON(json: any): RecurringGroupDetail {
    return RecurringGroupDetailToJSONTyped(json, false);
}

export function RecurringGroupDetailToJSONTyped(value?: RecurringGroupDetail | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'currency': value['currency'],
        'avg_amount': value['avgAmount'],
        'avg_interval_days': value['avgIntervalDays'],
        'transaction_count': value['transactionCount'],
        'total_spent': value['totalSpent'],
        'total_spent_ccy': value['totalSpentCcy'],
        'yearly_cost': value['yearlyCost'],
        'first_seen': ((value['firstSeen']).toISOString()),
        'last_seen': ((value['lastSeen']).toISOString()),
        'description': value['description'],
    };
}

