/* tslint:disable */
/* eslint-disable */
/**
 * Finbot application service
 * API documentation for appwsrv
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SecurityQuote } from './SecurityQuote';
import {
    SecurityQuoteFromJSON,
    SecurityQuoteFromJSONTyped,
    SecurityQuoteToJSON,
    SecurityQuoteToJSONTyped,
} from './SecurityQuote';

/**
 * 
 * @export
 * @interface ResolveSecurityResponse
 */
export interface ResolveSecurityResponse {
    /**
     * 
     * @type {SecurityQuote}
     * @memberof ResolveSecurityResponse
     */
    quote: SecurityQuote;
}

/**
 * Check if a given object implements the ResolveSecurityResponse interface.
 */
export function instanceOfResolveSecurityResponse(value: object): value is ResolveSecurityResponse {
    if (!('quote' in value) || value['quote'] === undefined) return false;
    return true;
}

export function ResolveSecurityResponseFromJSON(json: any): ResolveSecurityResponse {
    return ResolveSecurityResponseFromJSONTyped(json, false);
}

export function ResolveSecurityResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResolveSecurityResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'quote': SecurityQuoteFromJSON(json['quote']),
    };
}

export function ResolveSecurityResponseToJSON(json: any): ResolveSecurityResponse {
    return ResolveSecurityResponseToJSONTyped(json, false);
}

export function ResolveSecurityResponseToJSONTyped(value?: ResolveSecurityResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'quote': SecurityQuoteToJSON(value['quote']),
    };
}

