/* tslint:disable */
/* eslint-disable */
/**
 * Finbot application service
 * API documentation for appwsrv
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SecurityQuote
 */
export interface SecurityQuote {
    /**
     * 
     * @type {string}
     * @memberof SecurityQuote
     */
    symbol: string;
    /**
     * 
     * @type {string}
     * @memberof SecurityQuote
     */
    name: string | null;
    /**
     * 
     * @type {string}
     * @memberof SecurityQuote
     */
    currency: string;
    /**
     * 
     * @type {number}
     * @memberof SecurityQuote
     */
    price: number;
    /**
     * 
     * @type {Date}
     * @memberof SecurityQuote
     */
    asOf: Date;
}

/**
 * Check if a given object implements the SecurityQuote interface.
 */
export function instanceOfSecurityQuote(value: object): value is SecurityQuote {
    if (!('symbol' in value) || value['symbol'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('currency' in value) || value['currency'] === undefined) return false;
    if (!('price' in value) || value['price'] === undefined) return false;
    if (!('asOf' in value) || value['asOf'] === undefined) return false;
    return true;
}

export function SecurityQuoteFromJSON(json: any): SecurityQuote {
    return SecurityQuoteFromJSONTyped(json, false);
}

export function SecurityQuoteFromJSONTyped(json: any, ignoreDiscriminator: boolean): SecurityQuote {
    if (json == null) {
        return json;
    }
    return {
        
        'symbol': json['symbol'],
        'name': json['name'],
        'currency': json['currency'],
        'price': json['price'],
        'asOf': (new Date(json['as_of'])),
    };
}

export function SecurityQuoteToJSON(json: any): SecurityQuote {
    return SecurityQuoteToJSONTyped(json, false);
}

export function SecurityQuoteToJSONTyped(value?: SecurityQuote | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'symbol': value['symbol'],
        'name': value['name'],
        'currency': value['currency'],
        'price': value['price'],
        'as_of': ((value['asOf']).toISOString()),
    };
}

