/* tslint:disable */
/* eslint-disable */
/**
 * Finbot application service
 * API documentation for appwsrv
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { SeriesDescriptionDataInner } from "./SeriesDescriptionDataInner";
import {
  SeriesDescriptionDataInnerFromJSON,
  SeriesDescriptionDataInnerFromJSONTyped,
  SeriesDescriptionDataInnerToJSON,
  SeriesDescriptionDataInnerToJSONTyped,
} from "./SeriesDescriptionDataInner";

/**
 *
 * @export
 * @interface SeriesDescription
 */
export interface SeriesDescription {
  [key: string]: any | any;
  /**
   *
   * @type {string}
   * @memberof SeriesDescription
   */
  name: string;
  /**
   *
   * @type {Array<SeriesDescriptionDataInner>}
   * @memberof SeriesDescription
   */
  data: Array<SeriesDescriptionDataInner>;
  /**
   *
   * @type {string}
   * @memberof SeriesDescription
   */
  colour: string;
}

/**
 * Check if a given object implements the SeriesDescription interface.
 */
export function instanceOfSeriesDescription(
  value: object,
): value is SeriesDescription {
  if (!("name" in value) || value["name"] === undefined) return false;
  if (!("data" in value) || value["data"] === undefined) return false;
  if (!("colour" in value) || value["colour"] === undefined) return false;
  return true;
}

export function SeriesDescriptionFromJSON(json: any): SeriesDescription {
  return SeriesDescriptionFromJSONTyped(json, false);
}

export function SeriesDescriptionFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): SeriesDescription {
  if (json == null) {
    return json;
  }
  return {
    ...json,
    name: json["name"],
    data: (json["data"] as Array<any>).map(SeriesDescriptionDataInnerFromJSON),
    colour: json["colour"],
  };
}

export function SeriesDescriptionToJSON(json: any): SeriesDescription {
  return SeriesDescriptionToJSONTyped(json, false);
}

export function SeriesDescriptionToJSONTyped(
  value?: SeriesDescription | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    ...value,
    name: value["name"],
    data: (value["data"] as Array<any>).map(SeriesDescriptionDataInnerToJSON),
    colour: value["colour"],
  };
}
