/* tslint:disable */
/* eslint-disable */
/**
 * Finbot application service
 * API documentation for appwsrv
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SpendingCalendarRecurringPayment
 */
export interface SpendingCalendarRecurringPayment {
    /**
     * 
     * @type {number}
     * @memberof SpendingCalendarRecurringPayment
     */
    subscriptionId: number;
    /**
     * 
     * @type {string}
     * @memberof SpendingCalendarRecurringPayment
     */
    merchantName: string;
    /**
     * 
     * @type {string}
     * @memberof SpendingCalendarRecurringPayment
     */
    description: string | null;
    /**
     * 
     * @type {string}
     * @memberof SpendingCalendarRecurringPayment
     */
    currency: string;
    /**
     * 
     * @type {number}
     * @memberof SpendingCalendarRecurringPayment
     */
    avgAmount: number;
    /**
     * 
     * @type {boolean}
     * @memberof SpendingCalendarRecurringPayment
     */
    isProjected: boolean;
}

/**
 * Check if a given object implements the SpendingCalendarRecurringPayment interface.
 */
export function instanceOfSpendingCalendarRecurringPayment(value: object): value is SpendingCalendarRecurringPayment {
    if (!('subscriptionId' in value) || value['subscriptionId'] === undefined) return false;
    if (!('merchantName' in value) || value['merchantName'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('currency' in value) || value['currency'] === undefined) return false;
    if (!('avgAmount' in value) || value['avgAmount'] === undefined) return false;
    if (!('isProjected' in value) || value['isProjected'] === undefined) return false;
    return true;
}

export function SpendingCalendarRecurringPaymentFromJSON(json: any): SpendingCalendarRecurringPayment {
    return SpendingCalendarRecurringPaymentFromJSONTyped(json, false);
}

export function SpendingCalendarRecurringPaymentFromJSONTyped(json: any, ignoreDiscriminator: boolean): SpendingCalendarRecurringPayment {
    if (json == null) {
        return json;
    }
    return {
        
        'subscriptionId': json['subscription_id'],
        'merchantName': json['merchant_name'],
        'description': json['description'],
        'currency': json['currency'],
        'avgAmount': json['avg_amount'],
        'isProjected': json['is_projected'],
    };
}

export function SpendingCalendarRecurringPaymentToJSON(json: any): SpendingCalendarRecurringPayment {
    return SpendingCalendarRecurringPaymentToJSONTyped(json, false);
}

export function SpendingCalendarRecurringPaymentToJSONTyped(value?: SpendingCalendarRecurringPayment | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'subscription_id': value['subscriptionId'],
        'merchant_name': value['merchantName'],
        'description': value['description'],
        'currency': value['currency'],
        'avg_amount': value['avgAmount'],
        'is_projected': value['isProjected'],
    };
}

