/* tslint:disable */
/* eslint-disable */
/**
 * Finbot application service
 * API documentation for appwsrv
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SpendingCalendarRecurringPayment } from './SpendingCalendarRecurringPayment';
import {
    SpendingCalendarRecurringPaymentFromJSON,
    SpendingCalendarRecurringPaymentFromJSONTyped,
    SpendingCalendarRecurringPaymentToJSON,
    SpendingCalendarRecurringPaymentToJSONTyped,
} from './SpendingCalendarRecurringPayment';

/**
 * 
 * @export
 * @interface SpendingCalendarDay
 */
export interface SpendingCalendarDay {
    /**
     * 
     * @type {Date}
     * @memberof SpendingCalendarDay
     */
    date: Date;
    /**
     * 
     * @type {number}
     * @memberof SpendingCalendarDay
     */
    totalSpending: number;
    /**
     * 
     * @type {Array<SpendingCalendarRecurringPayment>}
     * @memberof SpendingCalendarDay
     */
    recurringPayments: Array<SpendingCalendarRecurringPayment>;
}

/**
 * Check if a given object implements the SpendingCalendarDay interface.
 */
export function instanceOfSpendingCalendarDay(value: object): value is SpendingCalendarDay {
    if (!('date' in value) || value['date'] === undefined) return false;
    if (!('totalSpending' in value) || value['totalSpending'] === undefined) return false;
    if (!('recurringPayments' in value) || value['recurringPayments'] === undefined) return false;
    return true;
}

export function SpendingCalendarDayFromJSON(json: any): SpendingCalendarDay {
    return SpendingCalendarDayFromJSONTyped(json, false);
}

export function SpendingCalendarDayFromJSONTyped(json: any, ignoreDiscriminator: boolean): SpendingCalendarDay {
    if (json == null) {
        return json;
    }
    return {
        
        'date': (new Date(json['date'])),
        'totalSpending': json['total_spending'],
        'recurringPayments': ((json['recurring_payments'] as Array<any>).map(SpendingCalendarRecurringPaymentFromJSON)),
    };
}

export function SpendingCalendarDayToJSON(json: any): SpendingCalendarDay {
    return SpendingCalendarDayToJSONTyped(json, false);
}

export function SpendingCalendarDayToJSONTyped(value?: SpendingCalendarDay | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'date': ((value['date']).toISOString().substring(0,10)),
        'total_spending': value['totalSpending'],
        'recurring_payments': ((value['recurringPayments'] as Array<any>).map(SpendingCalendarRecurringPaymentToJSON)),
    };
}

