/* tslint:disable */
/* eslint-disable */
/**
 * Finbot application service
 * API documentation for appwsrv
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SpendingCalendarDay } from './SpendingCalendarDay';
import {
    SpendingCalendarDayFromJSON,
    SpendingCalendarDayFromJSONTyped,
    SpendingCalendarDayToJSON,
    SpendingCalendarDayToJSONTyped,
} from './SpendingCalendarDay';

/**
 * 
 * @export
 * @interface SpendingCalendarReport
 */
export interface SpendingCalendarReport {
    /**
     * 
     * @type {string}
     * @memberof SpendingCalendarReport
     */
    valuationCcy: string;
    /**
     * 
     * @type {Date}
     * @memberof SpendingCalendarReport
     */
    startDate: Date;
    /**
     * 
     * @type {Date}
     * @memberof SpendingCalendarReport
     */
    endDate: Date;
    /**
     * 
     * @type {number}
     * @memberof SpendingCalendarReport
     */
    maxDailySpending: number;
    /**
     * 
     * @type {Array<SpendingCalendarDay>}
     * @memberof SpendingCalendarReport
     */
    days: Array<SpendingCalendarDay>;
}

/**
 * Check if a given object implements the SpendingCalendarReport interface.
 */
export function instanceOfSpendingCalendarReport(value: object): value is SpendingCalendarReport {
    if (!('valuationCcy' in value) || value['valuationCcy'] === undefined) return false;
    if (!('startDate' in value) || value['startDate'] === undefined) return false;
    if (!('endDate' in value) || value['endDate'] === undefined) return false;
    if (!('maxDailySpending' in value) || value['maxDailySpending'] === undefined) return false;
    if (!('days' in value) || value['days'] === undefined) return false;
    return true;
}

export function SpendingCalendarReportFromJSON(json: any): SpendingCalendarReport {
    return SpendingCalendarReportFromJSONTyped(json, false);
}

export function SpendingCalendarReportFromJSONTyped(json: any, ignoreDiscriminator: boolean): SpendingCalendarReport {
    if (json == null) {
        return json;
    }
    return {
        
        'valuationCcy': json['valuation_ccy'],
        'startDate': (new Date(json['start_date'])),
        'endDate': (new Date(json['end_date'])),
        'maxDailySpending': json['max_daily_spending'],
        'days': ((json['days'] as Array<any>).map(SpendingCalendarDayFromJSON)),
    };
}

export function SpendingCalendarReportToJSON(json: any): SpendingCalendarReport {
    return SpendingCalendarReportToJSONTyped(json, false);
}

export function SpendingCalendarReportToJSONTyped(value?: SpendingCalendarReport | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'valuation_ccy': value['valuationCcy'],
        'start_date': ((value['startDate']).toISOString().substring(0,10)),
        'end_date': ((value['endDate']).toISOString().substring(0,10)),
        'max_daily_spending': value['maxDailySpending'],
        'days': ((value['days'] as Array<any>).map(SpendingCalendarDayToJSON)),
    };
}

