/* tslint:disable */
/* eslint-disable */
/**
 * Finbot application service
 * API documentation for appwsrv
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface SubAccountDescription
 */
export interface SubAccountDescription {
  /**
   *
   * @type {string}
   * @memberof SubAccountDescription
   */
  id: string;
  /**
   *
   * @type {string}
   * @memberof SubAccountDescription
   */
  currency: string;
  /**
   *
   * @type {string}
   * @memberof SubAccountDescription
   */
  description: string;
  /**
   *
   * @type {string}
   * @memberof SubAccountDescription
   */
  type: string;
}

/**
 * Check if a given object implements the SubAccountDescription interface.
 */
export function instanceOfSubAccountDescription(
  value: object,
): value is SubAccountDescription {
  if (!("id" in value) || value["id"] === undefined) return false;
  if (!("currency" in value) || value["currency"] === undefined) return false;
  if (!("description" in value) || value["description"] === undefined)
    return false;
  if (!("type" in value) || value["type"] === undefined) return false;
  return true;
}

export function SubAccountDescriptionFromJSON(
  json: any,
): SubAccountDescription {
  return SubAccountDescriptionFromJSONTyped(json, false);
}

export function SubAccountDescriptionFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): SubAccountDescription {
  if (json == null) {
    return json;
  }
  return {
    id: json["id"],
    currency: json["currency"],
    description: json["description"],
    type: json["type"],
  };
}

export function SubAccountDescriptionToJSON(
  value?: SubAccountDescription | null,
): any {
  if (value == null) {
    return value;
  }
  return {
    id: value["id"],
    currency: value["currency"],
    description: value["description"],
    type: value["type"],
  };
}
