/* tslint:disable */
/* eslint-disable */
/**
 * Finbot application service
 * API documentation for appwsrv
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SubscriptionEntry } from './SubscriptionEntry';
import {
    SubscriptionEntryFromJSON,
    SubscriptionEntryFromJSONTyped,
    SubscriptionEntryToJSON,
    SubscriptionEntryToJSONTyped,
} from './SubscriptionEntry';

/**
 * 
 * @export
 * @interface SubscriptionsReport
 */
export interface SubscriptionsReport {
    /**
     * 
     * @type {string}
     * @memberof SubscriptionsReport
     */
    valuationCcy: string;
    /**
     * 
     * @type {number}
     * @memberof SubscriptionsReport
     */
    estimatedYearlyTotal: number;
    /**
     * 
     * @type {number}
     * @memberof SubscriptionsReport
     */
    totalSpentThisYear: number;
    /**
     * 
     * @type {Array<SubscriptionEntry>}
     * @memberof SubscriptionsReport
     */
    subscriptions: Array<SubscriptionEntry>;
}

/**
 * Check if a given object implements the SubscriptionsReport interface.
 */
export function instanceOfSubscriptionsReport(value: object): value is SubscriptionsReport {
    if (!('valuationCcy' in value) || value['valuationCcy'] === undefined) return false;
    if (!('estimatedYearlyTotal' in value) || value['estimatedYearlyTotal'] === undefined) return false;
    if (!('totalSpentThisYear' in value) || value['totalSpentThisYear'] === undefined) return false;
    if (!('subscriptions' in value) || value['subscriptions'] === undefined) return false;
    return true;
}

export function SubscriptionsReportFromJSON(json: any): SubscriptionsReport {
    return SubscriptionsReportFromJSONTyped(json, false);
}

export function SubscriptionsReportFromJSONTyped(json: any, ignoreDiscriminator: boolean): SubscriptionsReport {
    if (json == null) {
        return json;
    }
    return {
        
        'valuationCcy': json['valuation_ccy'],
        'estimatedYearlyTotal': json['estimated_yearly_total'],
        'totalSpentThisYear': json['total_spent_this_year'],
        'subscriptions': ((json['subscriptions'] as Array<any>).map(SubscriptionEntryFromJSON)),
    };
}

export function SubscriptionsReportToJSON(json: any): SubscriptionsReport {
    return SubscriptionsReportToJSONTyped(json, false);
}

export function SubscriptionsReportToJSONTyped(value?: SubscriptionsReport | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'valuation_ccy': value['valuationCcy'],
        'estimated_yearly_total': value['estimatedYearlyTotal'],
        'total_spent_this_year': value['totalSpentThisYear'],
        'subscriptions': ((value['subscriptions'] as Array<any>).map(SubscriptionEntryToJSON)),
    };
}

