/* tslint:disable */
/* eslint-disable */
/**
 * Finbot application service
 * API documentation for appwsrv
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { SystemReport } from "./SystemReport";
import {
  SystemReportFromJSON,
  SystemReportFromJSONTyped,
  SystemReportToJSON,
  SystemReportToJSONTyped,
} from "./SystemReport";

/**
 *
 * @export
 * @interface SystemReportResponse
 */
export interface SystemReportResponse {
  [key: string]: any | any;
  /**
   *
   * @type {SystemReport}
   * @memberof SystemReportResponse
   */
  systemReport: SystemReport;
}

/**
 * Check if a given object implements the SystemReportResponse interface.
 */
export function instanceOfSystemReportResponse(
  value: object,
): value is SystemReportResponse {
  if (!("systemReport" in value) || value["systemReport"] === undefined)
    return false;
  return true;
}

export function SystemReportResponseFromJSON(json: any): SystemReportResponse {
  return SystemReportResponseFromJSONTyped(json, false);
}

export function SystemReportResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): SystemReportResponse {
  if (json == null) {
    return json;
  }
  return {
    ...json,
    systemReport: SystemReportFromJSON(json["system_report"]),
  };
}

export function SystemReportResponseToJSON(json: any): SystemReportResponse {
  return SystemReportResponseToJSONTyped(json, false);
}

export function SystemReportResponseToJSONTyped(
  value?: SystemReportResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    ...value,
    system_report: SystemReportToJSON(value["systemReport"]),
  };
}
