/* tslint:disable */
/* eslint-disable */
/**
 * Finbot application service
 * API documentation for appwsrv
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TransactionEntry
 */
export interface TransactionEntry {
    /**
     * 
     * @type {number}
     * @memberof TransactionEntry
     */
    id: number;
    /**
     * 
     * @type {number}
     * @memberof TransactionEntry
     */
    linkedAccountId: number;
    /**
     * 
     * @type {string}
     * @memberof TransactionEntry
     */
    linkedAccountName: string;
    /**
     * 
     * @type {string}
     * @memberof TransactionEntry
     */
    subAccountId: string;
    /**
     * 
     * @type {string}
     * @memberof TransactionEntry
     */
    subAccountName: string;
    /**
     * 
     * @type {Date}
     * @memberof TransactionEntry
     */
    transactionDate: Date;
    /**
     * 
     * @type {string}
     * @memberof TransactionEntry
     */
    transactionType: string;
    /**
     * 
     * @type {number}
     * @memberof TransactionEntry
     */
    amount: number;
    /**
     * 
     * @type {number}
     * @memberof TransactionEntry
     */
    amountSnapshotCcy: number | null;
    /**
     * 
     * @type {string}
     * @memberof TransactionEntry
     */
    currency: string;
    /**
     * 
     * @type {string}
     * @memberof TransactionEntry
     */
    description: string;
    /**
     * 
     * @type {string}
     * @memberof TransactionEntry
     */
    symbol: string | null;
    /**
     * 
     * @type {number}
     * @memberof TransactionEntry
     */
    units: number | null;
    /**
     * 
     * @type {number}
     * @memberof TransactionEntry
     */
    unitPrice: number | null;
    /**
     * 
     * @type {number}
     * @memberof TransactionEntry
     */
    fee: number | null;
    /**
     * 
     * @type {string}
     * @memberof TransactionEntry
     */
    counterparty: string | null;
    /**
     * 
     * @type {string}
     * @memberof TransactionEntry
     */
    spendingCategoryPrimary: string | null;
    /**
     * 
     * @type {string}
     * @memberof TransactionEntry
     */
    spendingCategoryDetailed: string | null;
    /**
     *
     * @type {number}
     * @memberof TransactionEntry
     */
    matchedTransactionId: number | null;
    /**
     *
     * @type {number}
     * @memberof TransactionEntry
     */
    merchantId?: number | null;
    /**
     *
     * @type {string}
     * @memberof TransactionEntry
     */
    merchantName?: string | null;
    /**
     *
     * @type {string}
     * @memberof TransactionEntry
     */
    merchantWebsiteUrl?: string | null;
}

/**
 * Check if a given object implements the TransactionEntry interface.
 */
export function instanceOfTransactionEntry(value: object): value is TransactionEntry {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('linkedAccountId' in value) || value['linkedAccountId'] === undefined) return false;
    if (!('linkedAccountName' in value) || value['linkedAccountName'] === undefined) return false;
    if (!('subAccountId' in value) || value['subAccountId'] === undefined) return false;
    if (!('subAccountName' in value) || value['subAccountName'] === undefined) return false;
    if (!('transactionDate' in value) || value['transactionDate'] === undefined) return false;
    if (!('transactionType' in value) || value['transactionType'] === undefined) return false;
    if (!('amount' in value) || value['amount'] === undefined) return false;
    if (!('amountSnapshotCcy' in value) || value['amountSnapshotCcy'] === undefined) return false;
    if (!('currency' in value) || value['currency'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('symbol' in value) || value['symbol'] === undefined) return false;
    if (!('units' in value) || value['units'] === undefined) return false;
    if (!('unitPrice' in value) || value['unitPrice'] === undefined) return false;
    if (!('fee' in value) || value['fee'] === undefined) return false;
    if (!('counterparty' in value) || value['counterparty'] === undefined) return false;
    if (!('spendingCategoryPrimary' in value) || value['spendingCategoryPrimary'] === undefined) return false;
    if (!('spendingCategoryDetailed' in value) || value['spendingCategoryDetailed'] === undefined) return false;
    if (!('matchedTransactionId' in value) || value['matchedTransactionId'] === undefined) return false;
    return true;
}

export function TransactionEntryFromJSON(json: any): TransactionEntry {
    return TransactionEntryFromJSONTyped(json, false);
}

export function TransactionEntryFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransactionEntry {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'linkedAccountId': json['linked_account_id'],
        'linkedAccountName': json['linked_account_name'],
        'subAccountId': json['sub_account_id'],
        'subAccountName': json['sub_account_name'],
        'transactionDate': (new Date(json['transaction_date'])),
        'transactionType': json['transaction_type'],
        'amount': json['amount'],
        'amountSnapshotCcy': json['amount_snapshot_ccy'],
        'currency': json['currency'],
        'description': json['description'],
        'symbol': json['symbol'],
        'units': json['units'],
        'unitPrice': json['unit_price'],
        'fee': json['fee'],
        'counterparty': json['counterparty'],
        'spendingCategoryPrimary': json['spending_category_primary'],
        'spendingCategoryDetailed': json['spending_category_detailed'],
        'matchedTransactionId': json['matched_transaction_id'],
        'merchantId': json['merchant_id'] == null ? undefined : json['merchant_id'],
        'merchantName': json['merchant_name'] == null ? undefined : json['merchant_name'],
        'merchantWebsiteUrl': json['merchant_website_url'] == null ? undefined : json['merchant_website_url'],
    };
}

export function TransactionEntryToJSON(json: any): TransactionEntry {
    return TransactionEntryToJSONTyped(json, false);
}

export function TransactionEntryToJSONTyped(value?: TransactionEntry | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'linked_account_id': value['linkedAccountId'],
        'linked_account_name': value['linkedAccountName'],
        'sub_account_id': value['subAccountId'],
        'sub_account_name': value['subAccountName'],
        'transaction_date': ((value['transactionDate']).toISOString()),
        'transaction_type': value['transactionType'],
        'amount': value['amount'],
        'amount_snapshot_ccy': value['amountSnapshotCcy'],
        'currency': value['currency'],
        'description': value['description'],
        'symbol': value['symbol'],
        'units': value['units'],
        'unit_price': value['unitPrice'],
        'fee': value['fee'],
        'counterparty': value['counterparty'],
        'spending_category_primary': value['spendingCategoryPrimary'],
        'spending_category_detailed': value['spendingCategoryDetailed'],
        'matched_transaction_id': value['matchedTransactionId'],
        'merchant_id': value['merchantId'],
        'merchant_name': value['merchantName'],
        'merchant_website_url': value['merchantWebsiteUrl'],
    };
}

