/* tslint:disable */
/* eslint-disable */
/**
 * Finbot application service
 * API documentation for appwsrv
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TriggerLinkedAccountValuationResponse
 */
export interface TriggerLinkedAccountValuationResponse {
    /**
     * 
     * @type {string}
     * @memberof TriggerLinkedAccountValuationResponse
     */
    jobId: string | null;
}

/**
 * Check if a given object implements the TriggerLinkedAccountValuationResponse interface.
 */
export function instanceOfTriggerLinkedAccountValuationResponse(value: object): value is TriggerLinkedAccountValuationResponse {
    if (!('jobId' in value) || value['jobId'] === undefined) return false;
    return true;
}

export function TriggerLinkedAccountValuationResponseFromJSON(json: any): TriggerLinkedAccountValuationResponse {
    return TriggerLinkedAccountValuationResponseFromJSONTyped(json, false);
}

export function TriggerLinkedAccountValuationResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TriggerLinkedAccountValuationResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'jobId': json['job_id'],
    };
}

export function TriggerLinkedAccountValuationResponseToJSON(json: any): TriggerLinkedAccountValuationResponse {
    return TriggerLinkedAccountValuationResponseToJSONTyped(json, false);
}

export function TriggerLinkedAccountValuationResponseToJSONTyped(value?: TriggerLinkedAccountValuationResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'job_id': value['jobId'],
    };
}

