/* tslint:disable */
/* eslint-disable */
/**
 * Finbot application service
 * API documentation for appwsrv
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TriggerUserAccountValuationResponse
 */
export interface TriggerUserAccountValuationResponse {
    /**
     * 
     * @type {string}
     * @memberof TriggerUserAccountValuationResponse
     */
    jobId: string | null;
}

/**
 * Check if a given object implements the TriggerUserAccountValuationResponse interface.
 */
export function instanceOfTriggerUserAccountValuationResponse(value: object): value is TriggerUserAccountValuationResponse {
    if (!('jobId' in value) || value['jobId'] === undefined) return false;
    return true;
}

export function TriggerUserAccountValuationResponseFromJSON(json: any): TriggerUserAccountValuationResponse {
    return TriggerUserAccountValuationResponseFromJSONTyped(json, false);
}

export function TriggerUserAccountValuationResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TriggerUserAccountValuationResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'jobId': json['job_id'],
    };
}

export function TriggerUserAccountValuationResponseToJSON(json: any): TriggerUserAccountValuationResponse {
    return TriggerUserAccountValuationResponseToJSONTyped(json, false);
}

export function TriggerUserAccountValuationResponseToJSONTyped(value?: TriggerUserAccountValuationResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'job_id': value['jobId'],
    };
}

