/* tslint:disable */
/* eslint-disable */
/**
 * Finbot application service
 * API documentation for appwsrv
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface UpdatedAt
 */
export interface UpdatedAt {}

/**
 * Check if a given object implements the UpdatedAt interface.
 */
export function instanceOfUpdatedAt(value: object): value is UpdatedAt {
  return true;
}

export function UpdatedAtFromJSON(json: any): UpdatedAt {
  return UpdatedAtFromJSONTyped(json, false);
}

export function UpdatedAtFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): UpdatedAt {
  return json;
}

export function UpdatedAtToJSON(json: any): UpdatedAt {
  return UpdatedAtToJSONTyped(json, false);
}

export function UpdatedAtToJSONTyped(
  value?: UpdatedAt | null,
  ignoreDiscriminator: boolean = false,
): any {
  return value;
}
