/* tslint:disable */
/* eslint-disable */
/**
 * Finbot application service
 * API documentation for appwsrv
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Portfolio } from './Portfolio';
import {
    PortfolioFromJSON,
    PortfolioFromJSONTyped,
    PortfolioToJSON,
    PortfolioToJSONTyped,
} from './Portfolio';

/**
 * 
 * @export
 * @interface UpdatePortfolioEntryResponse
 */
export interface UpdatePortfolioEntryResponse {
    /**
     * 
     * @type {Portfolio}
     * @memberof UpdatePortfolioEntryResponse
     */
    portfolio: Portfolio;
}

/**
 * Check if a given object implements the UpdatePortfolioEntryResponse interface.
 */
export function instanceOfUpdatePortfolioEntryResponse(value: object): value is UpdatePortfolioEntryResponse {
    if (!('portfolio' in value) || value['portfolio'] === undefined) return false;
    return true;
}

export function UpdatePortfolioEntryResponseFromJSON(json: any): UpdatePortfolioEntryResponse {
    return UpdatePortfolioEntryResponseFromJSONTyped(json, false);
}

export function UpdatePortfolioEntryResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdatePortfolioEntryResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'portfolio': PortfolioFromJSON(json['portfolio']),
    };
}

export function UpdatePortfolioEntryResponseToJSON(json: any): UpdatePortfolioEntryResponse {
    return UpdatePortfolioEntryResponseToJSONTyped(json, false);
}

export function UpdatePortfolioEntryResponseToJSONTyped(value?: UpdatePortfolioEntryResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'portfolio': PortfolioToJSON(value['portfolio']),
    };
}

