/* tslint:disable */
/* eslint-disable */
/**
 * Finbot application service
 * API documentation for appwsrv
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface UpdateLinkedAccountMetadataRequest
 */
export interface UpdateLinkedAccountMetadataRequest {
  /**
   *
   * @type {string}
   * @memberof UpdateLinkedAccountMetadataRequest
   */
  accountName?: string | null;
  /**
   *
   * @type {string}
   * @memberof UpdateLinkedAccountMetadataRequest
   */
  accountColour?: string | null;
  /**
   *
   * @type {boolean}
   * @memberof UpdateLinkedAccountMetadataRequest
   */
  frozen?: boolean | null;
}

/**
 * Check if a given object implements the UpdateLinkedAccountMetadataRequest interface.
 */
export function instanceOfUpdateLinkedAccountMetadataRequest(
  value: object,
): value is UpdateLinkedAccountMetadataRequest {
  return true;
}

export function UpdateLinkedAccountMetadataRequestFromJSON(
  json: any,
): UpdateLinkedAccountMetadataRequest {
  return UpdateLinkedAccountMetadataRequestFromJSONTyped(json, false);
}

export function UpdateLinkedAccountMetadataRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): UpdateLinkedAccountMetadataRequest {
  if (json == null) {
    return json;
  }
  return {
    accountName:
      json["account_name"] == null ? undefined : json["account_name"],
    accountColour:
      json["account_colour"] == null ? undefined : json["account_colour"],
    frozen: json["frozen"] == null ? undefined : json["frozen"],
  };
}

export function UpdateLinkedAccountMetadataRequestToJSON(
  json: any,
): UpdateLinkedAccountMetadataRequest {
  return UpdateLinkedAccountMetadataRequestToJSONTyped(json, false);
}

export function UpdateLinkedAccountMetadataRequestToJSONTyped(
  value?: UpdateLinkedAccountMetadataRequest | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    account_name: value["accountName"],
    account_colour: value["accountColour"],
    frozen: value["frozen"],
  };
}
