/* tslint:disable */
/* eslint-disable */
/**
 * Finbot application service
 * API documentation for appwsrv
 *
 * The version of the OpenAPI document: v0.0.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface UserAccountSettings
 */
export interface UserAccountSettings {
  /**
   *
   * @type {string}
   * @memberof UserAccountSettings
   */
  valuationCcy: string;
  /**
   *
   * @type {Date}
   * @memberof UserAccountSettings
   */
  createdAt: Date;
  /**
   *
   * @type {Date}
   * @memberof UserAccountSettings
   */
  updatedAt?: Date;
}

/**
 * Check if a given object implements the UserAccountSettings interface.
 */
export function instanceOfUserAccountSettings(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && "valuationCcy" in value;
  isInstance = isInstance && "createdAt" in value;

  return isInstance;
}

export function UserAccountSettingsFromJSON(json: any): UserAccountSettings {
  return UserAccountSettingsFromJSONTyped(json, false);
}

export function UserAccountSettingsFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): UserAccountSettings {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    valuationCcy: json["valuation_ccy"],
    createdAt: new Date(json["created_at"]),
    updatedAt: !exists(json, "updated_at")
      ? undefined
      : new Date(json["updated_at"]),
  };
}

export function UserAccountSettingsToJSON(
  value?: UserAccountSettings | null,
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    valuation_ccy: value.valuationCcy,
    created_at: value.createdAt.toISOString(),
    updated_at:
      value.updatedAt === undefined ? undefined : value.updatedAt.toISOString(),
  };
}
