/* tslint:disable */
/* eslint-disable */
/**
 * Finbot application service
 * API documentation for appwsrv
 *
 * The version of the OpenAPI document: v0.8.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import type { ValuationChange } from "./ValuationChange";
import {
  ValuationChangeFromJSON,
  ValuationChangeFromJSONTyped,
  ValuationChangeToJSON,
} from "./ValuationChange";

/**
 *
 * @export
 * @interface ValuationWithSparkline
 */
export interface ValuationWithSparkline {
  /**
   *
   * @type {string}
   * @memberof ValuationWithSparkline
   */
  currency: string;
  /**
   *
   * @type {number}
   * @memberof ValuationWithSparkline
   */
  value: number;
  /**
   *
   * @type {ValuationChange}
   * @memberof ValuationWithSparkline
   */
  change: ValuationChange;
  /**
   *
   * @type {Array<number>}
   * @memberof ValuationWithSparkline
   */
  sparkline: Array<number>;
}

/**
 * Check if a given object implements the ValuationWithSparkline interface.
 */
export function instanceOfValuationWithSparkline(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && "currency" in value;
  isInstance = isInstance && "value" in value;
  isInstance = isInstance && "change" in value;
  isInstance = isInstance && "sparkline" in value;

  return isInstance;
}

export function ValuationWithSparklineFromJSON(
  json: any,
): ValuationWithSparkline {
  return ValuationWithSparklineFromJSONTyped(json, false);
}

export function ValuationWithSparklineFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ValuationWithSparkline {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    currency: json["currency"],
    value: json["value"],
    change: ValuationChangeFromJSON(json["change"]),
    sparkline: json["sparkline"],
  };
}

export function ValuationWithSparklineToJSON(
  value?: ValuationWithSparkline | null,
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    currency: value.currency,
    value: value.value,
    change: ValuationChangeToJSON(value.change),
    sparkline: value.sparkline,
  };
}
