/* tslint:disable */
/* eslint-disable */
/**
 * Finbot application service
 * API documentation for appwsrv
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface XAxisDescriptionCategoriesInner
 */
export interface XAxisDescriptionCategoriesInner {}

/**
 * Check if a given object implements the XAxisDescriptionCategoriesInner interface.
 */
export function instanceOfXAxisDescriptionCategoriesInner(
  value: object,
): value is XAxisDescriptionCategoriesInner {
  return true;
}

export function XAxisDescriptionCategoriesInnerFromJSON(
  json: any,
): XAxisDescriptionCategoriesInner {
  return XAxisDescriptionCategoriesInnerFromJSONTyped(json, false);
}

export function XAxisDescriptionCategoriesInnerFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): XAxisDescriptionCategoriesInner {
  return json;
}

export function XAxisDescriptionCategoriesInnerToJSON(
  json: any,
): XAxisDescriptionCategoriesInner {
  return XAxisDescriptionCategoriesInnerToJSONTyped(json, false);
}

export function XAxisDescriptionCategoriesInnerToJSONTyped(
  value?: XAxisDescriptionCategoriesInner | null,
  ignoreDiscriminator: boolean = false,
): any {
  return value;
}
