/* tslint:disable */
/* eslint-disable */
/**
 * Finbot application service
 * API documentation for appwsrv
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { XAxisDescriptionCategoriesInner } from "./XAxisDescriptionCategoriesInner";
import {
  XAxisDescriptionCategoriesInnerFromJSON,
  XAxisDescriptionCategoriesInnerFromJSONTyped,
  XAxisDescriptionCategoriesInnerToJSON,
  XAxisDescriptionCategoriesInnerToJSONTyped,
} from "./XAxisDescriptionCategoriesInner";

/**
 *
 * @export
 * @interface XAxisDescription
 */
export interface XAxisDescription {
  [key: string]: any | any;
  /**
   *
   * @type {string}
   * @memberof XAxisDescription
   */
  type: string;
  /**
   *
   * @type {Array<XAxisDescriptionCategoriesInner>}
   * @memberof XAxisDescription
   */
  categories: Array<XAxisDescriptionCategoriesInner>;
}

/**
 * Check if a given object implements the XAxisDescription interface.
 */
export function instanceOfXAxisDescription(
  value: object,
): value is XAxisDescription {
  if (!("type" in value) || value["type"] === undefined) return false;
  if (!("categories" in value) || value["categories"] === undefined)
    return false;
  return true;
}

export function XAxisDescriptionFromJSON(json: any): XAxisDescription {
  return XAxisDescriptionFromJSONTyped(json, false);
}

export function XAxisDescriptionFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): XAxisDescription {
  if (json == null) {
    return json;
  }
  return {
    ...json,
    type: json["type"],
    categories: (json["categories"] as Array<any>).map(
      XAxisDescriptionCategoriesInnerFromJSON,
    ),
  };
}

export function XAxisDescriptionToJSON(json: any): XAxisDescription {
  return XAxisDescriptionToJSONTyped(json, false);
}

export function XAxisDescriptionToJSONTyped(
  value?: XAxisDescription | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    ...value,
    type: value["type"],
    categories: (value["categories"] as Array<any>).map(
      XAxisDescriptionCategoriesInnerToJSON,
    ),
  };
}
