#!/usr/bin/env bash
OWN_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source "${OWN_DIR}/bash-utils.sh"

watched="${1}"
shift

log_info "watching directory: ${watched}"
watchmedo auto-restart \
  --directory "${watched}" \
  --pattern '*.py' \
  --recursive \
  --signal SIGKILL \
    -- "$@"
