#!/usr/bin/env python3
import click
import logging

from finbot.core.logging import configure_logging
from finbot.model import ScopedSession
from finbot.workflows.write_valuation_history.matching import backfill_matches


configure_logging("INFO")
logger = logging.getLogger(__name__)


@click.command()
def main():
    with ScopedSession() as session:
        total = backfill_matches(session)
        logger.info("Backfill complete: %d matches created", total)


if __name__ == "__main__":
    main()
