#!/usr/bin/env python3
import asyncio
import click
import logging

from finbot.core.logging import configure_logging
from finbot.model import ScopedSession, TransactionHistoryEntry
from finbot.core.spending_categorizer import categorize_transaction_batch


configure_logging("INFO")
logger = logging.getLogger(__name__)


@click.command()
@click.option("--limit", type=int, default=None, help="Max transactions to categorize")
def main(limit: int | None):
    with ScopedSession() as session:
        query = (
            session.query(TransactionHistoryEntry.id)
            .filter(TransactionHistoryEntry.spending_category_source.is_(None))
            .order_by(TransactionHistoryEntry.transaction_date.desc())
        )
        if limit:
            query = query.limit(limit)
        ids = [row.id for row in query.all()]

        if not ids:
            logger.info("No uncategorized transactions found")
            return

        logger.info("Categorizing %d transactions", len(ids))
        asyncio.run(categorize_transaction_batch(ids, session))
        session.commit()
        logger.info("Done")


if __name__ == "__main__":
    main()
