#!/usr/bin/env bash
set -e

OWN_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source "${OWN_DIR}/bash-utils.sh"

log_info initializing finbot environment

log_info checking docker availability
which docker >/dev/null 2>&1 || die "'docker' is not available in this machine, install and try again"
log_info docker is available

log_info checking docker-compose availability
which docker-compose >/dev/null 2>&1 || die "'docker-compose' is not available on this machine, install and try again"
log_info docker-compose is available

docker_image="finbot/finbot:latest"
if ! docker_image_exists ${docker_image}
then
  log_info "finbot runtime image (${docker_image}) does not exist, building"
  make docker-build
else
  log_info "finbot runtime image (${docker_image}) already exists, skipping build"
fi

log_info "creating secret environment script"
cp secret.env.sh.tpl secret.env.sh && chmod 700 secret.env.sh
secret_key=$(docker_run_operator tools/crypt fernet-key | tail -n 1)
sed -i'' "s/FINBOT_SECRET_KEY_PLACEHOLDER/${secret_key}/g" secret.env.sh

log_info "starting finbot database container"
docker_run_operator env FINBOT_WAIT_DEPS=db make finbot-wait

log_info "creating finbot database schema"
docker_run_operator make finbotdb-rebuild

log_info "hydrating finbotdb with default data"
docker_run_operator make finbotdb-hydrate

log_info "stopping containers"
docker-compose down

log_info "finbot is ready to use"
log_info "start with ./finbotctl start"
