#!/usr/bin/env bash
OWN_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source "${OWN_DIR}/bash-utils.sh"

log_info "restarting finbot"

"${OWN_DIR}/finbotctl-stop"
"${OWN_DIR}/finbotctl-start"
