#!/usr/bin/env python3.7
from sqlalchemy.orm import sessionmaker
from sqlalchemy import create_engine
from finbot.model import Base
import sys


def main():
    action = sys.argv[1]
    engine = create_engine('postgresql+psycopg2://finbot:finbot@127.0.0.1/finbot')
    if action == "build":
        print("building finbotdb")
        Base.metadata.create_all(engine)

    elif action == "destroy":
        print("destroying finbotdb")
        Base.metadata.drop_all(engine)

    else:
        raise RuntimeError(f"unknown action '{action}'")


if __name__ == "__main__":
    main()