#!/usr/bin/env bash
set -e

OWN_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source "${OWN_DIR}/bash-utils.sh"

log_info initializing finbot environment

log_info checking docker availability
which docker >/dev/null 2>&1 || die "'docker' is not available in this machine, install and try again"
log_info docker is available

log_info checking docker-compose availability
which docker-compose >/dev/null 2>&1 || die "'docker-compose' is not available on this machine, install and try again"
log_info docker-compose is available

log_info "building docker images"
make docker-build-dev

log_info "creating secret environment"
cp envs/secrets.env.tpl envs/secrets.dev.env
secret_key=$(docker-compose run --rm operator tools/crypt fernet-key | tail -n 1)
sed -i'' "s/FINBOT_SECRET_KEY_PLACEHOLDER/${secret_key}/g" envs/secrets.dev.env
cp envs/secrets.dev.env envs/secrets.prod.env
chmod 700 envs/secrets*.env

log_info "starting finbot database container"
docker-compose run --rm operator env FINBOT_WAIT_DEPS=db ./tools/finbot-wait

log_info "creating finbot database schema"
docker-compose run --rm operator make finbotdb-rebuild

log_info "hydrating finbotdb with default data"
docker-compose run --rm operator make finbotdb-hydrate

log_info "stopping containers"
docker-compose down

log_info "finbot is ready to use"
log_info "start with ./finbotctl start"
