#!/usr/bin/env bash
OWN_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
. ${OWN_DIR}/bash-utils.sh

wait_dep () {
docker-compose run --rm operator \
  tools/with-env.sh docker \
    env FINBOT_WAIT_DEPS=${1} make finbot-wait >/dev/null 2>&1
}

log_info "starting finbot backend containers"
docker-compose up -d \
  appwsrv histwsrv snapwsrv finbotwsrv finbotdb schedsrv \
  || die failed to start containers

log_info "waiting for public endpoint availability"
wait_dep appwsrv

if [[ "${1}" != "--no-frontend" ]]
then
  log_info "starting finbot frontend container (webapp)"
  docker-compose up -d webapp || die failed to start containers
  log_info "waiting for frontend availability"
  wait_dep webapp

  webapp_url=$(tools/with-env.sh local tools/get-env.sh FINBOT_WEBAPP_ENDPOINT)
  log_info "you can now access finbot on: ${webapp_url}"
else
  log_info "skipping frontend container (--no-frontend provided)"
fi
