#!/usr/bin/env bash
OWN_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
. ${OWN_DIR}/bash-utils.sh

log_info "starting finbot backend containers"
docker-compose up -d \
  appwsrv histwsrv snapwsrv finbotwsrv finbotdb schedsrv \
  || die failed to start containers
deps=api

if [[ "${1}" != "--no-frontend" ]]
then
  log_info "starting finbot frontend container (webapp)"
  docker-compose up -d webapp || die failed to start containers
  deps="${deps},webapp"
else
  log_info "skipping frontend container (--no-frontend provided)"
fi

log_info "waiting for dependencies ${deps} to be available"

docker-compose run --rm operator \
  tools/with-env.sh docker \
    env FINBOT_WAIT_DEPS=${deps} make finbot-wait
