#!/usr/bin/env bash
set -e
root_dir=$(git rev-parse --show-toplevel)
work_dir=$(mktemp -d)
docker run --rm -w /finbot \
  -v "${root_dir}"/pyproject.toml:/finbot/pyproject.toml:ro \
  -v "${work_dir}":"${work_dir}" \
  python:3.13-bullseye bash -c "\
    set -e && \
    wget https://astral.sh/uv/install.sh -O /tmp/install-uv.sh && \
    env XDG_BIN_HOME=/usr/local/bin sh /tmp/install-uv.sh && \
    echo compiling prod requirements && \
    uv pip compile pyproject.toml --output-file requirements.txt && \
    echo compiling dev requirements && \
    uv pip compile pyproject.toml --extra dev --output-file requirements-dev.txt && \
    mv requirements*.txt ${work_dir}
"
mv "${work_dir}"/requirements*.txt "${root_dir}"/
