#!/usr/bin/env bash
set -e
workdir=$(mktemp -d)
finbot_root_dir=$(git rev-parse --show-toplevel)

mkdir -p "${workdir}/schema"
service_name=appwsrv
api_version=$(./tools/export-openapi-schema.py -s "${service_name}" --show-api-version)
./tools/export-openapi-schema.py -s "${service_name}" > "${workdir}/schema/appwsrv.openapi.json"
cp "${workdir}/schema/appwsrv.openapi.json" "${finbot_root_dir}/finbot/apps/appwsrv/appwsrv.openapi.json"

openapi-generator-cli generate \
  -i "${workdir}/schema/appwsrv.openapi.json" \
  -g typescript-fetch \
  --additional-properties=withSeparateModelsAndApi=true,useSingleRequestParameter=true,withInterfaces=true,supportsES6=true,disallowAdditionalPropertiesIfNotPresent=false \
  -o "${workdir}/output/"

git config --global --add safe.directory "*"
app_client_dir="${finbot_root_dir}/webapp/src/clients/app-client"
mkdir -p "${app_client_dir}"
rm -rf "${app_client_dir:?}"/*
mv "${workdir}/output/index.ts" "${app_client_dir}"
mv "${workdir}/output/runtime.ts" "${app_client_dir}"
mv "${workdir}/output/apis/" "${app_client_dir}"
mv "${workdir}/output/models/" "${app_client_dir}"

find "${app_client_dir}" -name '*.ts' -print0 | xargs -0 sed -i '/The version of the OpenAPI document/d'
echo "/* The version of the OpenAPI document: v${api_version} */" >> "${app_client_dir}/index.ts"
