#!/usr/bin/env python3.11
from finbot.clients.history import HistoryClient
from finbot.core.serialization import pretty_dump
from finbot.core.environment import get_histwsrv_endpoint
import argparse


def create_parser():
    parser = argparse.ArgumentParser("snapwsrv tester")
    parser.add_argument("--endpoint", type=str, default=get_histwsrv_endpoint())
    parser.add_argument("--snapshot-id", type=int)
    return parser


def main():
    parser = create_parser()
    settings = parser.parse_args()
    client = HistoryClient(settings.endpoint)
    print(f"will send history report request for snapshot {settings.snapshot_id}")
    print(f"history report finished {pretty_dump(client.write_history(settings.snapshot_id))}")


if __name__ == "__main__":
    main()
