#!/usr/bin/env python
import json
import logging
import sys
from argparse import ArgumentParser

from finbot.providers import factory as providers_factory
from finbot.providers.playwright_based import BrowserSettings


logging.basicConfig(stream=sys.stdout, level=logging.DEBUG)


def create_parser() -> ArgumentParser:
    parser = ArgumentParser("Test finbot provider")
    parser.add_argument(
        "-p", "--provider",
        choices=list(providers_factory.PROVIDERS.keys()),
        required=True,
        type=str,
        help="Provider"
    )
    parser.add_argument(
        "-a", "--auth-payload",
        type=str,
        required=False,
        default=None,
        help="Provider authentication payload (JSON)"
    )
    return parser


def main():
    api_settings = dict(
        playwright_settings=BrowserSettings(enable_virtual_display=False)
    )
    settings = create_parser().parse_args()
    auth_payload = json.loads(settings.auth_payload) if settings.auth_payload else None
    provider = providers_factory.get_provider(settings.provider)
    api_module = provider.api_module
    with api_module.Api(**api_settings) as provider_api:
        credentials = api_module.Credentials.init(auth_payload)
        provider_api.authenticate(credentials)
        balances = provider_api.get_balances()
        assets = provider_api.get_assets()
        print(json.dumps({
            "balances": balances,
            "assets": assets
        }, indent=2))


if __name__ == "__main__":
    main()
