#!/usr/bin/env bash
script_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
source "${script_dir}/bash-utils.sh"
service_name=$1

"${script_dir}/finbot-wait"

if [[ -z "${service_name}" ]]
then
  echo "usage: $0 < service name >"
  echo "usage: $0 -- < arguments >"
  exit 1
elif [[ "${service_name}" == "webapp" ]]
then
  exec "${script_dir}/run-webapp-dev.sh"
elif [[ "${service_name}" == "workersrv[temporal]" ]]
then
  exec python3 -m finbot.apps.workersrv_temporal
elif [[ "${service_name}" == "finbotwsrv" ]]
then
	xvfb-run -a "${script_dir}/run-web-service.sh" \
		--app finbotwsrv \
		--workers 4 \
		--port 5001
elif [[ "${service_name}" == "appwsrv" ]]
then
	exec "${script_dir}/run-web-service.sh" \
	  --app appwsrv \
	  --workers 4 \
	  --port 5003
elif [[ "${service_name}" == "--" ]]
then
  shift
  echo "running command: ${*}"
  exec "${@}"
else
  log_error "unknown service: ${service_name}"
  exit 1
fi
