#!/usr/bin/env python3.9
from finbot.clients.snap import SnapClient
from finbot.core.utils import pretty_dump
import argparse


def create_parser():
    parser = argparse.ArgumentParser("snapwsrv tester")
    parser.add_argument("--endpoint", type=str)
    parser.add_argument("--account-id", type=int)
    return parser


def main():
    parser = create_parser()
    settings = parser.parse_args()
    client = SnapClient(settings.endpoint)
    print(f"will send snapshot request for account id {settings.account_id}")
    print(f"snapshot finished {pretty_dump(client.take_snapshot(settings.account_id))}")


if __name__ == "__main__":
    main()
