name: Docker
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
    tags:
      - 'v*'

concurrency:
  group: ${{ github.head_ref || github.ref_type }}

jobs:
  publish-docker-images:
    name: publish-docker-images
    runs-on: ubuntu-latest
    strategy:
      matrix:
        build:
          - repository: finbotapp/runtime
            context: .
            target: runtime
            skip: ${{ github.event_name == 'pull_request' }}
          - repository: finbotapp/runtime-dev
            context: .
            target: runtime-dev
          - repository: finbotapp/webapp
            context: ./webapp
        exclude:
          - build:
              skip: true

    steps:
      - name: Check out finbot source
        uses: actions/checkout@v3
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ matrix.build.repository }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ${{ matrix.build.context }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          target: ${{ matrix.build.target }}