name: Lint (Python)
on:
  push:
    branches:
      - master
    paths:
      - "**.py"
      - "requirements*.txt"
  pull_request:
    branches:
      - master
    paths:
      - "**"
      - "requirements*.txt"

jobs:
  py-lint-check:
    strategy:
      matrix:
        check: ['flakes-check', 'black-check', 'mypy', 'isort-check', 'banned-keywords-check-py']
    runs-on: ubuntu-latest
    steps:
      - name: Check out finbot source
        uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.13
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - name: Install Python dependencies
        run: uv pip install --system -r requirements-dev.txt
      - name: Lint (${{ matrix.check }})
        run: make ${{ matrix.check }}
