name: Lint (Python)
on:
  push:
    branches:
      - master
    paths:
      - "**.py"
      - "requirements*.txt"
  pull_request:
    branches:
      - master
    paths:
      - "**.py"
      - "requirements*.txt"

jobs:
  ruff-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out finbot source
        uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.12
      - name: Install Python dependencies
        run: python3.12 -m pip install -r requirements-dev.txt
      - name: ruff lint
        run: make ruff
  black-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out finbot source
        uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.12
      - name: Install Python dependencies
        run: python3.12 -m pip install -r requirements-dev.txt
      - name: black lint
        run: make black-check
  mypy-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out finbot source
        uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.12
      - name: Install Python dependencies
        run: python3.12 -m pip install -r requirements-dev.txt
      - name: mypy lint
        run: make mypy
  isort-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out finbot source
        uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.12
      - name: Install Python dependencies
        run: python3.12 -m pip install -r requirements-dev.txt
      - name: isort lint
        run: make isort-check
  banned-keywords-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out finbot source
        uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.12
      - name: Install Python dependencies
        run: python3.12 -m pip install -r requirements-dev.txt
      - name: Check banned keywords
        run: make banned-keywords-check-py
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out finbot source
        uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.12
      - name: Install Python dependencies
        run: python3.12 -m pip install -r requirements-dev.txt
      - name: Run unit tests
        run: make unit-tests-py
