name: Lint (Python)
on:
  push:
    branches:
      - master
    paths:
      - "**.py"
  pull_request:
    branches:
      - master
    paths:
      - "**.py"

jobs:
  flake8-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out finbot source
        uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - name: flake8 lint
        uses: py-actions/flake8@v1
        with:
          ignore: "W503"
          max-line-length: "120"
          path: "finbot/"
  black-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out finbot source
        uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - name: Install Python dependencies
        run: python3.11 -m pip install -r requirements-dev.txt
      - name: black lint
        run: make black-check
  mypy-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out finbot source
        uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - name: Install Python dependencies
        run: python3.11 -m pip install -r requirements-dev.txt
      - name: mypy lint
        run: make mypy
  isort-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out finbot source
        uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - name: Install Python dependencies
        run: python3.11 -m pip install -r requirements-dev.txt
      - name: isort lint
        run: make isort-check
  banned-keywords-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out finbot source
        uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - name: Install Python dependencies
        run: python3.11 -m pip install -r requirements-dev.txt
      - name: Check banned keywords
        run: make banned-keywords-check-py
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out finbot source
        uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - name: Install Python dependencies
        run: python3.11 -m pip install -r requirements-dev.txt
      - name: Run unit tests
        run: make unit-tests-py
