name: System tests (Python)
on:
  push:
    branches:
      - master
    paths:
      - "**.py"
      - "requirements*.txt"
      - "Dockerfile"
      - "docker-compose.yml"
  pull_request:
    branches:
      - master
    paths:
      - "**.py"
      - "requirements*.txt"
      - "Dockerfile"
      - "docker-compose.yml"
jobs:
  run-system-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out finbot source
        uses: actions/checkout@v2
      - name: Initialise finbot environment
        run: ./finbotctl init
      - name: Start finbot backend
        run: ./finbotctl start --no-frontend
      - name: Run system tests
        run: make run-system-tests
      - name: Stop finbot backend
        run: ./finbotctl stop
