name: Unit tests (Python)
on:
  push:
    branches:
      - master
    paths:
      - "**.py"
      - "requirements*.txt"
  pull_request:
    branches:
      - master
    paths:
      - "**.py"
      - "requirements*.txt"
jobs:
  run-system-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out finbot source
        uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - name: Install Python dependencies
        run: python3.11 -m pip install -r requirements-dev.txt
      - name: Run unit tests
        run: make unit-tests-py
