name: Unit tests (Python)
on:
  push:
    branches:
      - master
    paths:
      - "**.py"
      - "requirements*.txt"
  pull_request:
    branches:
      - master
    paths:
      - "**.py"
      - "requirements*.txt"
jobs:
  run-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out finbot source
        uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.12
      - name: Install Python dependencies
        run: python3.12 -m pip install -r requirements-dev.txt
      - name: Start test database
        run: docker compose up finbotdb-test -d
      - name: Wait test database
        run: python -m finbot.scripts.wait_deps finbotdb-test
      - name: Run unit tests
        run: make unit-tests-py
