name: Versioning
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  tag-release:
    name: tag-release${{ github.event_name == 'pull_request' && '-dry-run' }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out finbot source
        uses: actions/checkout@v3
      - uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - name: Install Python dependencies
        run: python3.11 -m pip install -r requirements-dev.txt
      - run: echo "PYTHONPATH=$PWD:$PYTHONPATH" >> $GITHUB_ENV
      - name: Get current version
        id: meta
        run: echo "FINBOT_REL_VERSION=v$(./tools/versioning get-current-version)" >> $GITHUB_OUTPUT
      - run: '[[ -n "${{ steps.meta.outputs.FINBOT_REL_VERSION }}" ]] || exit 1'
      - name: Create release tag
        if: ${{ github.event_name != 'pull_request' }}
        uses: rickstaa/action-create-tag@v1
        with:
          tag: ${{ steps.meta.outputs.FINBOT_REL_VERSION }}
          tag_exists_error: true
          message: "Finbot release ${{ steps.meta.outputs.FINBOT_REL_VERSION }}"
      - name: Create release tag (dry-run)
        if: ${{ github.event_name == 'pull_request' }}
        run: echo "Finbot version ${{ steps.meta.outputs.FINBOT_REL_VERSION }} will be released after this MR is merged"
