name: Release
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  check-version-bump:
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out finbot source
        uses: actions/checkout@v3
      - uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - run: git fetch origin master:master
      - name: Install Python dependencies
        run: python3.11 -m pip install -r requirements-dev.txt
      - run: echo "PYTHONPATH=$PWD:$PYTHONPATH" >> $GITHUB_ENV
      - name: Check version bump
        run: ./tools/versioning check-version-bump

  tag-release:
    name: tag-release
    runs-on: ubuntu-latest
    steps:
      - name: Check out finbot source
        uses: actions/checkout@v3
      - uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - name: Install Python dependencies
        run: python3.11 -m pip install -r requirements-dev.txt
      - run: echo "PYTHONPATH=$PWD:$PYTHONPATH" >> $GITHUB_ENV
      - name: Get current version
        id: meta
        run: echo "FINBOT_REL_VERSION=v$(./tools/versioning get-current-version)" >> $GITHUB_OUTPUT
      - run: '[[ -n "${{ steps.meta.outputs.FINBOT_REL_VERSION }}" ]] || exit 1'
      - name: Create release tag
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: ${{ steps.meta.outputs.FINBOT_REL_VERSION }}
          dry_run: ${{ github.event_name == 'pull_request' }}
