name: System tests
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  run-system-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out finbot source
        uses: actions/checkout@v2
      - name: Initialise finbot environment
        run: ./finbotctl init
      - name: Start finbot backend
        run: ./finbotctl start --no-frontend
      - name: Run system tests
        run: make run-system-tests
      - name: Stop finbot backend
        run: ./finbotctl stop
