name: Lint (TS)
on:
  push:
    branches:
      - master
    paths:
      - "**.js"
      - "**.jsx"
      - "**.ts"
      - "**.tsx"
      - "package.json"
  pull_request:
    branches:
      - master
    paths:
      - "**.js"
      - "**.jsx"
      - "**.ts"
      - "**.tsx"
      - "package.json"

jobs:
  eslint-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out finbot source
        uses: actions/checkout@v2
      - name: Install JS dependencies
        working-directory: webapp/
        run: npm install
      - name: eslint check
        working-directory: webapp/
        run: npm run lint-check:prod
  typescript-build-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out finbot source
        uses: actions/checkout@v2
      - name: Install JS dependencies
        working-directory: webapp/
        run: npm install
      - name: TS to JS build check
        working-directory: webapp/
        run: npm run tsc-build-check
  prettier-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out finbot source
        uses: actions/checkout@v2
      - name: Install JS dependencies
        working-directory: webapp/
        run: npm install
      - name: prettier check
        working-directory: webapp/
        run: npm run prettier-check
  banned-keywords-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out finbot source
        uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Check banned keywords
        run: make banned-keywords-check-ts
